/**
 * External resource sources.
 *
 * This is the catalogue of the third-party libraries, generators and galleries
 * Cupric draws on — for two different jobs:
 *
 *   • `ui`    — patterns we mirror in the app's own interface (Lab components,
 *               glass chrome, Library cards, Studio panels).
 *   • `video` — material the local HTML → MP4 pipeline can render: backgrounds,
 *               shaders, illustrations, kinetic type, templates.
 *
 * Nothing here is bundled code. Each entry records *where* the material lives,
 * what licence story it has, and a `promptCue` the Arena/Gemini prompt builder
 * and the local generator can paste verbatim. That keeps the app honest: the
 * catalogue can list 40 sites while the repo stays small and MIT-clean.
 *
 * `resources/packs/sources.json` is generated from this file by
 * `npm run packs:build`, so the Library shows exactly what the code knows.
 */

export type SourceUse = 'ui' | 'video' | 'both'

export type SourceKind =
  | 'components'
  | 'shaders'
  | 'backgrounds'
  | 'illustrations'
  | 'icons'
  | 'motion'
  | 'templates'
  | 'generators'
  | 'inspiration'
  | 'prompts'

export type SourceEntry = {
  id: string
  name: string
  url: string
  kind: SourceKind
  use: SourceUse
  /** One line: what it actually gives us. */
  description: string
  /** Pasted into generation prompts and into the Arena brief. */
  promptCue: string
  /** How the material reaches Cupric: copy-paste, CLI registry, or reference only. */
  intake: 'copy' | 'registry' | 'reference' | 'export'
  /** Free / open-source unless noted. */
  license: string
  tags: string[]
}

export const SOURCES: SourceEntry[] = [
  /* ——— Component libraries ——— */
  {
    id: 'forge-ui',
    name: 'Forge UI',
    url: 'https://forgeui.in/components',
    kind: 'components',
    use: 'both',
    description:
      'Motion-first React components. Progress Stack and Stack Ripple are vendored into the Lab; Text Reveal and Velora drive HTML video templates.',
    promptCue:
      'Forge UI look: soft neutral gradient cards (from-neutral-100 to-neutral-50, dark from-neutral-800 to-neutral-950), 12px radius, inset hairline ring, spring motion (damping 15, stiffness 200).',
    intake: 'copy',
    license: 'Free tier, MIT-style copy-paste',
    tags: ['react', 'motion', 'cards', 'progress'],
  },
  {
    id: 'forge-ui-templates',
    name: 'Forge UI templates',
    url: 'https://forgeui.in/template',
    kind: 'templates',
    use: 'video',
    description: 'Full page templates used as scene layouts for HTML → MP4 renders (hero, pricing, feature grid).',
    promptCue:
      'Template scene: full-bleed hero, one headline at 64px/800 weight, one supporting line at 22px muted, content centred in a 1080×1920 safe area.',
    intake: 'copy',
    license: 'Free tier',
    tags: ['template', 'landing', 'scene'],
  },
  {
    id: 'forge-ui-illustrations',
    name: 'Forge UI illustrations',
    url: 'https://forgeui.in/illustrations',
    kind: 'illustrations',
    use: 'both',
    description: 'SVG illustrations for empty states in the app and as foreground art in generated video.',
    promptCue: 'Line-art SVG illustration, single accent colour on a near-black field, 2px strokes, no gradients.',
    intake: 'copy',
    license: 'Free tier',
    tags: ['svg', 'empty-state', 'art'],
  },
  {
    id: 'watermelon-ui',
    name: 'Watermelon UI',
    url: 'https://ui.watermelon.sh/home',
    kind: 'components',
    use: 'both',
    description: 'Playful animated React/Tailwind blocks — good source for Studio panel micro-states.',
    promptCue: 'Watermelon look: high-contrast rounded blocks, bouncy spring entrances, oversized type, one saturated accent.',
    intake: 'copy',
    license: 'Open source',
    tags: ['react', 'tailwind', 'animated'],
  },
  {
    id: 'shadcn-ui',
    name: 'shadcn/ui',
    url: 'https://ui.shadcn.com',
    kind: 'components',
    use: 'ui',
    description: 'The baseline primitive set and registry format every other source here plugs into.',
    promptCue: 'shadcn baseline: neutral tokens, 0.5rem radius, focus-visible ring, muted-foreground for secondary text.',
    intake: 'registry',
    license: 'MIT',
    tags: ['primitives', 'registry', 'tokens'],
  },
  {
    id: 'aceternity-ui',
    name: 'Aceternity UI',
    url: 'https://ui.aceternity.com',
    kind: 'components',
    use: 'both',
    description: '200+ animated React/Tailwind sections — spotlight cards, beams, aurora backgrounds.',
    promptCue: 'Aceternity look: aurora/beam background, spotlight that tracks the pointer, gradient borders, heavy blur.',
    intake: 'copy',
    license: 'MIT',
    tags: ['animated', 'hero', 'background'],
  },
  {
    id: 'magic-ui',
    name: 'Magic UI',
    url: 'https://magicui.design',
    kind: 'components',
    use: 'both',
    description: 'Marquees, number tickers, shine borders — most of them map 1:1 to a video overlay.',
    promptCue: 'Magic UI look: shimmering border sweep, number ticker counting up, marquee row of logos at 40s linear.',
    intake: 'copy',
    license: 'MIT',
    tags: ['marquee', 'ticker', 'border'],
  },
  {
    id: 'motion-primitives',
    name: 'Motion Primitives',
    url: 'https://motion-primitives.com',
    kind: 'motion',
    use: 'both',
    description: 'Small, composable motion behaviours — the closest match to the Studio text animations.',
    promptCue: 'Motion primitive: per-character stagger of 0.03s, blur 6px → 0, y 12px → 0, easeOut 0.4s.',
    intake: 'copy',
    license: 'MIT',
    tags: ['motion', 'stagger', 'text'],
  },
  {
    id: 'uiverse',
    name: 'Uiverse',
    url: 'https://uiverse.io',
    kind: 'components',
    use: 'ui',
    description: 'Community CSS-only buttons, loaders and toggles — pure CSS, so they drop straight into a render frame.',
    promptCue: 'CSS-only control, no JS: keyframes for the whole state change, hover and active handled in CSS.',
    intake: 'copy',
    license: 'MIT (per-snippet)',
    tags: ['css', 'buttons', 'loaders'],
  },
  {
    id: 'uiable',
    name: 'Uiable',
    url: 'https://uiable.com',
    kind: 'components',
    use: 'ui',
    description: 'Curated Tailwind blocks; used as layout reference for the Library and Review Room.',
    promptCue: 'Clean Tailwind block: 12-column grid, generous 24px gaps, hairline dividers instead of shadows.',
    intake: 'reference',
    license: 'Free tier',
    tags: ['blocks', 'layout'],
  },
  {
    id: 'mapcn',
    name: 'mapcn',
    url: 'https://mapcn.dev',
    kind: 'components',
    use: 'both',
    description: 'Map, marker, route and popup components — the route-draw animation is a ready video beat.',
    promptCue: 'Map beat: dark tiles, a single lime route drawn with stroke-dashoffset over 2s, marker pops at each stop.',
    intake: 'copy',
    license: 'MIT',
    tags: ['map', 'route', 'marker'],
  },
  {
    id: '21st-dev',
    name: '21st.dev',
    url: 'https://21st.dev',
    kind: 'components',
    use: 'ui',
    description: 'Component registry that plugs in over MCP — the fastest way to pull one more block into the app.',
    promptCue: 'Registry install: shadcn add <item>, then restyle to Cupric tokens (near-black #0B0B10, lime #C8F542).',
    intake: 'registry',
    license: 'Mixed, per item',
    tags: ['registry', 'mcp'],
  },
  {
    id: '23rd-dev',
    name: '23rd (shadcn registry)',
    url: 'https://23rd.dev',
    kind: 'shaders',
    use: 'both',
    description:
      'Shader Gradient / Fire / Sky, Live Orb, ASCII Logo, Logo Burst, Radiant Lines, Dithered 404 — installs via shadcn CLI, renders as video atmosphere.',
    promptCue:
      'Shader atmosphere behind content: full-bleed animated gradient in a relatively positioned, isolated section; UI sits in a later stacking context at z-10.',
    intake: 'registry',
    license: 'Open registry (per item)',
    tags: ['shader', 'webgl', 'background', 'ascii'],
  },
  {
    id: 'beautiful-ui',
    name: 'Beautiful UI',
    url: 'https://beautifului.dev',
    kind: 'components',
    use: 'ui',
    description: 'Polished marketing sections; used for spacing and type-scale reference.',
    promptCue: 'Editorial spacing: 96px section rhythm, 1.15 line-height headlines, -0.02em tracking.',
    intake: 'reference',
    license: 'Free tier',
    tags: ['marketing', 'typography'],
  },
  {
    id: 'metalforge',
    name: 'MetalForge',
    url: 'https://metalforge.xyz',
    kind: 'shaders',
    use: 'video',
    description: 'Metallic/chrome material studies — the best reference for the liquid-glass and chrome-title looks.',
    promptCue: 'Chrome title: brushed metal gradient with an animated specular sweep, 1px dark inner bevel, no drop shadow.',
    intake: 'reference',
    license: 'Reference only',
    tags: ['chrome', 'metal', 'title'],
  },
  {
    id: 'astryx',
    name: 'Astryx',
    url: 'https://astryx.atmeta.com/components',
    kind: 'components',
    use: 'both',
    description: 'Meta-built component set — dense, accessible patterns worth copying for the app chrome.',
    promptCue: 'Astryx look: restrained neutral surfaces, strong focus states, 4px spacing grid, motion under 200ms.',
    intake: 'reference',
    license: 'Per site terms',
    tags: ['accessible', 'chrome', 'dense'],
  },

  /* ——— Detail / micro-interaction ——— */
  {
    id: 'microkit',
    name: 'Microkit',
    url: 'https://microkit.co',
    kind: 'motion',
    use: 'ui',
    description: 'Micro-interactions — the small confirmations that make the Studio feel responsive.',
    promptCue: 'Micro-interaction: 120ms scale to 0.97 on press, 240ms spring back, haptic-style overshoot of 4%.',
    intake: 'copy',
    license: 'Free tier',
    tags: ['micro', 'feedback'],
  },
  {
    id: 'glass-refraction',
    name: 'Glass refraction',
    url: 'https://glass.samasante.com',
    kind: 'shaders',
    use: 'both',
    description: 'Glass refraction study; feeds the existing Liquid Glass preset parameters.',
    promptCue: 'Liquid glass: backdrop blur 18px, SVG displacement 24, 1px white inner ring at 20%, specular highlight top-left.',
    intake: 'reference',
    license: 'Reference only',
    tags: ['glass', 'refraction', 'blur'],
  },
  {
    id: 'text-effects',
    name: 'Text Effects (Colorion)',
    url: 'https://text-effects.colorion.co',
    kind: 'motion',
    use: 'video',
    description: 'Copy-paste CSS text effects — direct source for kinetic type beats.',
    promptCue: 'Text effect beat: gradient text with an animated background-position sweep over 2.4s linear infinite.',
    intake: 'copy',
    license: 'Free',
    tags: ['text', 'css', 'kinetic'],
  },
  {
    id: 'kinetics',
    name: 'Kinetics (Colorion)',
    url: 'https://kinetics.colorion.co',
    kind: 'motion',
    use: 'both',
    description: '150+ motion effects shipped with React code and a matching prompt for each.',
    promptCue: 'Kinetic effect: describe the motion in one clause (what moves, how far, over how long, with what easing).',
    intake: 'copy',
    license: 'Free',
    tags: ['motion', 'react', 'prompts'],
  },
  {
    id: 'circle-loaders',
    name: 'Circle Loaders',
    url: 'https://circleloaders.dominikakissi.com',
    kind: 'motion',
    use: 'both',
    description: 'Pure-CSS circular loaders — used for progress beats and the Render screen.',
    promptCue: 'Circular loader: 2px stroke, 270° arc, 1s linear rotation, accent stroke on a 12%-opacity track.',
    intake: 'copy',
    license: 'Free',
    tags: ['loader', 'css', 'progress'],
  },
  {
    id: 'gradient-buttons',
    name: 'Gradient Buttons',
    url: 'https://gradientbuttons.colorion.co',
    kind: 'components',
    use: 'ui',
    description: 'Gradient button recipes for the primary CTA family.',
    promptCue: 'Gradient CTA: 135° two-stop gradient, 1px lighter top edge, shadow only on hover.',
    intake: 'copy',
    license: 'Free',
    tags: ['button', 'gradient', 'cta'],
  },

  /* ——— Assets ——— */
  {
    id: 'kitbitz',
    name: 'Kitbitz',
    url: 'https://kitbitz.art',
    kind: 'illustrations',
    use: 'both',
    description: '2,000+ hand-drawn illustrations — foreground art for video and empty states in the app.',
    promptCue: 'Hand-drawn illustration, ink linework, slightly wobbly strokes, flat single-colour fills.',
    intake: 'export',
    license: 'Free tier',
    tags: ['illustration', 'hand-drawn'],
  },
  {
    id: '3dicons',
    name: '3dicons',
    url: 'https://3dicons.co',
    kind: 'icons',
    use: 'both',
    description: 'Free 3D icons (PNG/Blend) — hero props for video beats and Library category art.',
    promptCue: '3D icon prop: soft clay material, single key light from top-left, 15° tilt, transparent background.',
    intake: 'export',
    license: 'CC0',
    tags: ['3d', 'icon', 'prop'],
  },
  {
    id: 'animejs',
    name: 'Anime.js',
    url: 'https://animejs.com',
    kind: 'motion',
    use: 'video',
    description: 'Timeline animation library — the natural driver for `__seek(t)` HTML video templates.',
    promptCue: 'Anime.js timeline seeked by frame: build the full timeline, then call tl.seek(t * 1000) per frame.',
    intake: 'copy',
    license: 'MIT',
    tags: ['timeline', 'seek', 'render'],
  },

  /* ——— Generators ——— */
  {
    id: 'gradientool',
    name: 'Gradientool',
    url: 'https://gradientool.com',
    kind: 'generators',
    use: 'both',
    description: 'Gradient generator; exports CSS that drops into the backgrounds pack.',
    promptCue: 'Export as CSS `background-image` only, no vendor prefixes, sRGB stops.',
    intake: 'export',
    license: 'Free',
    tags: ['gradient', 'css'],
  },
  {
    id: 'gradient-lab',
    name: 'Backgrounds Supply — Gradient Lab',
    url: 'https://backgrounds.supply/gradient-lab',
    kind: 'backgrounds',
    use: 'video',
    description: 'Mesh gradient lab — full-bleed stage backgrounds for renders.',
    promptCue: 'Mesh gradient stage: 4 blurred colour blobs over #0B0B10, 120px blur, no visible banding.',
    intake: 'export',
    license: 'Free tier',
    tags: ['mesh', 'background', 'stage'],
  },
  {
    id: 'animos',
    name: 'Animos editor',
    url: 'https://animos.app/editor',
    kind: 'generators',
    use: 'video',
    description: 'Browser animation editor; its exported keyframes convert into Studio clips.',
    promptCue: 'Keyframe export: list of {t, props} pairs, linear between keys unless an easing is named.',
    intake: 'export',
    license: 'Free tier',
    tags: ['keyframes', 'editor'],
  },
  {
    id: 'cutting-mat',
    name: 'Cutting Mat Generator',
    url: 'https://cutting-mat-generator.vercel.app',
    kind: 'backgrounds',
    use: 'video',
    description: 'Self-healing cutting-mat grid — a distinctive SVG backdrop for product beats.',
    promptCue: 'Cutting-mat backdrop: dark teal field, 1cm white grid at 12%, 5cm grid at 24%, faint angle guides.',
    intake: 'export',
    license: 'Free',
    tags: ['grid', 'svg', 'backdrop'],
  },
  {
    id: 'space-type',
    name: 'Space Type Generator',
    url: 'https://spacetypegenerator.com',
    kind: 'generators',
    use: 'video',
    description: 'Type-in-space renders — ready-made title cards.',
    promptCue: 'Spatial title: letters distributed in depth, slow dolly-in, heavy tracking, monochrome.',
    intake: 'export',
    license: 'Free',
    tags: ['type', '3d', 'title'],
  },
  {
    id: 'book-of-shapes',
    name: 'Book of Shapes',
    url: 'https://bookofshapes.com',
    kind: 'generators',
    use: 'both',
    description: 'Generative shape library — SVG accents and transition masks.',
    promptCue: 'Generative shape mask: one organic blob, used as a clip-path that grows from 0 to cover over 0.6s.',
    intake: 'export',
    license: 'Free',
    tags: ['shape', 'svg', 'mask'],
  },
  {
    id: 'tabbied',
    name: 'Tabbied patterns',
    url: 'https://tabbied.com/patterns',
    kind: 'backgrounds',
    use: 'video',
    description: 'Doodle-pattern generator; tiles as a looping background.',
    promptCue: 'Pattern backdrop: repeating doodle tile at 8% opacity, slow 60s diagonal drift.',
    intake: 'export',
    license: 'Free',
    tags: ['pattern', 'tile'],
  },
  {
    id: 'dotforge',
    name: 'Dotforge',
    url: 'https://dotforge.vercel.app',
    kind: 'backgrounds',
    use: 'both',
    description: 'Dot-matrix background generator — matches the existing Dot Field effect.',
    promptCue: 'Dot matrix: 1px dots on a 24px grid at 8% white, radial mask fading to transparent at the edges.',
    intake: 'export',
    license: 'Free',
    tags: ['dots', 'matrix', 'background'],
  },
  {
    id: 'ditther',
    name: 'Ditther',
    url: 'https://ditther.com',
    kind: 'generators',
    use: 'video',
    description: 'Dithering tool — 1-bit treatments for retro beats and thumbnails.',
    promptCue: 'Dither pass: Atkinson dithering to 1-bit, then tint the white channel with the accent colour.',
    intake: 'export',
    license: 'Free',
    tags: ['dither', 'retro', '1-bit'],
  },
  {
    id: 'tokokino',
    name: 'Tokokino',
    url: 'https://tokokino.com',
    kind: 'inspiration',
    use: 'both',
    description: 'Motion-heavy showcase; reference for pacing and scene cuts.',
    promptCue: 'Pacing reference: cut on the beat every 1.2s, hold the final frame for 1.5s.',
    intake: 'reference',
    license: 'Reference only',
    tags: ['motion', 'pacing'],
  },
  {
    id: 'benday',
    name: 'benday',
    url: 'https://benday.kacemmathlouthi.dev',
    kind: 'generators',
    use: 'video',
    description: 'Ben-Day halftone generator — print-style texture over stills.',
    promptCue: 'Halftone pass: 6px dot grid at 15°, two-colour separation, slight registration offset.',
    intake: 'export',
    license: 'Free',
    tags: ['halftone', 'print', 'texture'],
  },
  {
    id: 'spherium',
    name: 'Spherium',
    url: 'https://tryspherium.com',
    kind: 'shaders',
    use: 'video',
    description: 'Sphere/orb visuals — a drop-in hero object for opening beats.',
    promptCue: 'Orb hero: single iridescent sphere centred, slow rotation, rim light, dark vignette field.',
    intake: 'reference',
    license: 'Free tier',
    tags: ['orb', 'sphere', 'hero'],
  },

  /* ——— Prompts, systems, inspiration ——— */
  {
    id: 'designmd',
    name: 'designmd.ai',
    url: 'https://designmd.ai',
    kind: 'prompts',
    use: 'ui',
    description: 'Design systems expressed as markdown an agent can read — the format Cupric briefs should follow.',
    promptCue: 'Give the agent the system as markdown: tokens, spacing scale, component rules, then the task.',
    intake: 'reference',
    license: 'Free tier',
    tags: ['design-system', 'markdown', 'agent'],
  },
  {
    id: 'vibeprompts',
    name: 'Vibeprompts',
    url: 'https://vibeprompts.dev',
    kind: 'prompts',
    use: 'both',
    description: 'Ready-made prompts for dashboards and landing pages — seeds for the Brief screen.',
    promptCue: 'Brief seed: audience, one promise, three proof beats, one call to action.',
    intake: 'copy',
    license: 'Free',
    tags: ['prompt', 'brief'],
  },
  {
    id: 'getlayers',
    name: 'getlayers.ai',
    url: 'https://getlayers.ai',
    kind: 'prompts',
    use: 'video',
    description: '200+ full build prompts for 3D and scroll-driven sites — complete briefs, not components.',
    promptCue: 'Full build brief: scene list, camera moves, scroll triggers, asset list, then the copy deck.',
    intake: 'copy',
    license: 'Free tier',
    tags: ['brief', '3d', 'scroll'],
  },
  {
    id: 'minimal-gallery',
    name: 'Minimal Gallery',
    url: 'https://minimal.gallery',
    kind: 'inspiration',
    use: 'both',
    description: 'High-end minimal sites — feed a URL to the agent as a style anchor.',
    promptCue: 'Style anchor: minimal, one typeface, one accent, whitespace doing the work.',
    intake: 'reference',
    license: 'Reference only',
    tags: ['minimal', 'anchor'],
  },
  {
    id: 'kage-design',
    name: 'Kage',
    url: 'https://kage.design',
    kind: 'prompts',
    use: 'ui',
    description: 'UI inspiration mapped straight to prompts.',
    promptCue: 'Inspiration → prompt: name the layout, the motion, the palette, and the one detail that sells it.',
    intake: 'reference',
    license: 'Free tier',
    tags: ['inspiration', 'prompt'],
  },
  {
    id: 'refero-styles',
    name: 'Refero Styles',
    url: 'https://styles.refero.design',
    kind: 'inspiration',
    use: 'ui',
    description: '2,000+ real product styles with typography specs — type scales worth stealing exactly.',
    promptCue: 'Type scale: name the family, the weights used, the scale ratio, and the tracking at display sizes.',
    intake: 'reference',
    license: 'Free tier',
    tags: ['typography', 'styles'],
  },
  {
    id: 'component-gallery',
    name: 'The Component Gallery',
    url: 'https://component.gallery',
    kind: 'inspiration',
    use: 'ui',
    description: '2,600+ ways top design systems solve the same element — the tiebreaker when a pattern is unclear.',
    promptCue: 'Pattern check: compare three systems solving this element, keep the simplest that stays accessible.',
    intake: 'reference',
    license: 'Free',
    tags: ['patterns', 'design-systems'],
  },
  {
    id: 'appshot-gallery',
    name: 'Appshot Gallery',
    url: 'https://appshot.gallery',
    kind: 'inspiration',
    use: 'video',
    description: 'App screenshot gallery — framing reference for product-shot beats.',
    promptCue: 'Product shot beat: device frame at 12° tilt, screen content readable, soft floor shadow.',
    intake: 'reference',
    license: 'Reference only',
    tags: ['screenshot', 'framing'],
  },
  {
    id: 'saved-design',
    name: 'Saved.design',
    url: 'https://saved.design',
    kind: 'inspiration',
    use: 'both',
    description: 'Curated saves of interface and motion work — a running moodboard for the app.',
    promptCue: 'Moodboard cue: one adjective for the motion, one for the surface, one for the type.',
    intake: 'reference',
    license: 'Reference only',
    tags: ['moodboard', 'curation'],
  },
]

/** Sources usable by the local HTML → MP4 generator. */
export const VIDEO_SOURCES = SOURCES.filter((s) => s.use === 'video' || s.use === 'both')

/** Sources that inform the app's own interface. */
export const UI_SOURCES = SOURCES.filter((s) => s.use === 'ui' || s.use === 'both')

export function sourcesByKind(kind: SourceKind): SourceEntry[] {
  return SOURCES.filter((s) => s.kind === kind)
}

export function getSource(id: string): SourceEntry | undefined {
  return SOURCES.find((s) => s.id === id)
}
