/* Frame-safe data visualization — every chart is a pure function of (data, t). */
import { clamp, getEase, hash1, mixColor, withAlpha } from "@/core/math";
import type { Theme } from "@/themes";
import { registerNodeRenderer, rr, text, linearGrad, p, type Ctx2D } from "@/render/core";

export type ChartProps = { data?: number[]; data2?: number[]; labels?: string[]; colors?: string[]; animation?: string; duration?: number; title?: string; value?: number; suffix?: string; prefix?: string; showLabels?: boolean };
export type ChartDef = { id: string; name: string; tags: string[]; description: string; draw: (ctx: Ctx2D, w: number, h: number, pr: number, t: number, d: Required<Pick<ChartProps, "data" | "colors">> & ChartProps, th: Theme) => void };
export const CHARTS: Record<string, ChartDef> = {};
const C = (id: string, name: string, tags: string[], description: string, draw: ChartDef["draw"]) => { CHARTS[id] = { id, name, tags, description, draw }; };
export const CHART_ANIMATIONS = ["grow", "draw", "stagger", "sweep", "fade"] as const;
const TAU = Math.PI * 2;
const col = (d: { colors: string[] }, i: number) => d.colors[i % d.colors.length];
function stag(pr: number, i: number, n: number, mode: string) { if (mode === "grow" || mode === "fade" || mode === "draw") return pr; const s = 0.6 / Math.max(1, n); return clamp((pr - i * s) / (1 - 0.6 + s)); }
function norm(data: number[]) { const mx = Math.max(...data, 1e-6), mn = Math.min(0, ...data); return (v: number) => (v - mn) / (mx - mn || 1); }
function axes(ctx: Ctx2D, w: number, h: number, th: Theme, rows = 4) { ctx.strokeStyle = withAlpha(th.colors.muted, 0.18); ctx.lineWidth = 1; for (let i = 0; i <= rows; i++) { const y = -h / 2 + (i / rows) * h; ctx.beginPath(); ctx.moveTo(-w / 2, y); ctx.lineTo(w / 2, y); ctx.stroke(); } }
function linePath(ctx: Ctx2D, data: number[], w: number, h: number, n: (v: number) => number, amp = 1, stepped = false) {
  data.forEach((v, i) => { const x = -w / 2 + (i / (data.length - 1)) * w, y = h / 2 - n(v) * h * amp; if (!i) ctx.moveTo(x, y); else if (stepped) { const px = -w / 2 + ((i - 1) / (data.length - 1)) * w; ctx.lineTo(x, h / 2 - n(data[i - 1]) * h * amp); void px; ctx.lineTo(x, y); } else { const px = -w / 2 + ((i - 1) / (data.length - 1)) * w, py = h / 2 - n(data[i - 1]) * h * amp; const cx = (px + x) / 2; ctx.bezierCurveTo(cx, py, cx, y, x, y); } });
}

C("line", "Line Chart", ["trend", "growth"], "Smooth line that draws left to right.", (ctx, w, h, pr, t, d, th) => { axes(ctx, w, h, th); const n = norm(d.data); ctx.save(); ctx.beginPath(); ctx.rect(-w / 2 - 10, -h, (w + 20) * pr, h * 2); ctx.clip(); ctx.beginPath(); linePath(ctx, d.data, w, h, n); ctx.strokeStyle = col(d, 0); ctx.lineWidth = 3.5; ctx.lineJoin = "round"; ctx.stroke(); ctx.restore(); const i = Math.min(d.data.length - 1, Math.floor(pr * (d.data.length - 1))); ctx.beginPath(); ctx.arc(-w / 2 + (i / (d.data.length - 1)) * w, h / 2 - n(d.data[i]) * h, 6, 0, TAU); ctx.fillStyle = col(d, 0); ctx.fill(); });
C("area", "Area Chart", ["trend", "saas", "revenue"], "Gradient area chart revealing with its line.", (ctx, w, h, pr, t, d, th) => { axes(ctx, w, h, th); const n = norm(d.data); ctx.save(); ctx.beginPath(); ctx.rect(-w / 2 - 10, -h, (w + 20) * pr, h * 2); ctx.clip(); ctx.beginPath(); linePath(ctx, d.data, w, h, n); ctx.lineTo(w / 2, h / 2); ctx.lineTo(-w / 2, h / 2); ctx.closePath(); ctx.fillStyle = linearGrad(ctx, [withAlpha(col(d, 0), 0.45), withAlpha(col(d, 1), 0)], 0, -h / 2, 0, h / 2); ctx.fill(); ctx.beginPath(); linePath(ctx, d.data, w, h, n); ctx.strokeStyle = col(d, 0); ctx.lineWidth = 3; ctx.stroke(); ctx.restore(); });
C("multiLine", "Multi-line", ["comparison", "trend"], "Two series drawing in sequence.", (ctx, w, h, pr, t, d, th) => { axes(ctx, w, h, th); const d2 = d.data2 ?? d.data.map((v, i) => v * 0.6 + Math.sin(i) * 4); const n = norm([...d.data, ...d2]); [d.data, d2].forEach((s, k) => { ctx.save(); ctx.beginPath(); ctx.rect(-w / 2 - 10, -h, (w + 20) * clamp(pr * 1.3 - k * 0.3), h * 2); ctx.clip(); ctx.beginPath(); linePath(ctx, s, w, h, n); ctx.strokeStyle = col(d, k); ctx.lineWidth = 3; ctx.stroke(); ctx.restore(); }); });
C("step", "Step Line", ["discrete", "status"], "Stepped line chart.", (ctx, w, h, pr, t, d, th) => { axes(ctx, w, h, th); const n = norm(d.data); ctx.save(); ctx.beginPath(); ctx.rect(-w / 2 - 10, -h, (w + 20) * pr, h * 2); ctx.clip(); ctx.beginPath(); linePath(ctx, d.data, w, h, n, 1, true); ctx.strokeStyle = col(d, 0); ctx.lineWidth = 3; ctx.stroke(); ctx.restore(); });
C("sparkline", "Sparkline", ["kpi", "mini"], "Compact inline trend line.", (ctx, w, h, pr, t, d) => { const n = norm(d.data); ctx.save(); ctx.beginPath(); ctx.rect(-w / 2 - 4, -h, (w + 8) * pr, h * 2); ctx.clip(); ctx.beginPath(); linePath(ctx, d.data, w, h, n); ctx.strokeStyle = col(d, 0); ctx.lineWidth = 2.5; ctx.stroke(); ctx.lineTo(w / 2, h / 2); ctx.lineTo(-w / 2, h / 2); ctx.fillStyle = withAlpha(col(d, 0), 0.15); ctx.fill(); ctx.restore(); });
C("bar", "Bar Chart", ["comparison", "data"], "Vertical bars growing with stagger.", (ctx, w, h, pr, t, d, th) => { axes(ctx, w, h, th); const n = norm(d.data); const bw = w / d.data.length; d.data.forEach((v, i) => { const k = getEase("overshoot")(stag(pr, i, d.data.length, d.animation ?? "stagger")); const bh = n(v) * h * k; rr(ctx, -w / 2 + i * bw + bw * 0.18, h / 2 - bh, bw * 0.64, bh, Math.min(8, bw * 0.2)); ctx.fillStyle = linearGrad(ctx, [col(d, 0), col(d, 1)], 0, h / 2 - bh, 0, h / 2); ctx.fill(); if (d.labels?.[i]) text(ctx, d.labels[i], -w / 2 + i * bw + bw / 2, h / 2 + 18, { size: 13, color: th.colors.muted, align: "center" }); }); });
C("hbar", "Horizontal Bars", ["ranking", "comparison"], "Horizontal bars with values.", (ctx, w, h, pr, t, d, th) => { const n = norm(d.data); const bh = h / d.data.length; d.data.forEach((v, i) => { const k = getEase("emphasized")(stag(pr, i, d.data.length, d.animation ?? "stagger")); const lw = w * 0.22; rr(ctx, -w / 2 + lw, -h / 2 + i * bh + bh * 0.2, (w - lw - 60) * n(v) * k, bh * 0.6, bh * 0.3); ctx.fillStyle = col(d, i); ctx.fill(); text(ctx, d.labels?.[i] ?? `Item ${i + 1}`, -w / 2, -h / 2 + i * bh + bh / 2, { size: 14, color: th.colors.text }); text(ctx, String(Math.round(v * k)), -w / 2 + lw + (w - lw - 60) * n(v) * k + 10, -h / 2 + i * bh + bh / 2, { size: 13, weight: 600, color: th.colors.muted }); }); });
C("stacked", "Stacked Bars", ["composition", "data"], "Stacked two-series bars.", (ctx, w, h, pr, t, d, th) => { axes(ctx, w, h, th); const d2 = d.data2 ?? d.data.map((v) => v * 0.5); const n = norm(d.data.map((v, i) => v + d2[i])); const bw = w / d.data.length; d.data.forEach((v, i) => { const k = getEase("emphasized")(stag(pr, i, d.data.length, "stagger")); const h1 = n(v) * h * k, h2 = n(d2[i]) * h * k; ctx.fillStyle = col(d, 0); ctx.fillRect(-w / 2 + i * bw + bw * 0.2, h / 2 - h1, bw * 0.6, h1); ctx.fillStyle = col(d, 1); ctx.fillRect(-w / 2 + i * bw + bw * 0.2, h / 2 - h1 - h2, bw * 0.6, h2); }); });
C("histogram", "Histogram", ["distribution", "statistics"], "Gap-less distribution bars.", (ctx, w, h, pr, t, d, th) => { const data = d.data.length > 12 ? d.data : Array.from({ length: 24 }, (_, i) => Math.exp(-((i - 12) ** 2) / 30) * 100 + hash1(i) * 10); const n = norm(data); const bw = w / data.length; data.forEach((v, i) => { const k = stag(pr, i, data.length, "stagger"); ctx.fillStyle = mixColor(col(d, 0), col(d, 1), i / data.length); ctx.fillRect(-w / 2 + i * bw, h / 2 - n(v) * h * k, bw - 1, n(v) * h * k); }); axes(ctx, w, h, th, 1); });
C("waterfall", "Waterfall", ["finance", "bridge"], "Cumulative waterfall bridge chart.", (ctx, w, h, pr, t, d, th) => { const deltas = d.data.map((v, i) => (i % 3 === 2 ? -v * 0.5 : v)); let acc = 0; const tops = deltas.map((v) => { const a = acc; acc += v; return [a, acc]; }); const mx = Math.max(...tops.flat(), 1); const bw = w / deltas.length; tops.forEach(([a, b], i) => { const k = stag(pr, i, deltas.length, "stagger"); const y0 = h / 2 - (a / mx) * h, y1 = h / 2 - ((a + (b - a) * k) / mx) * h; ctx.fillStyle = b >= a ? th.colors.success : th.colors.danger; ctx.fillRect(-w / 2 + i * bw + bw * 0.15, Math.min(y0, y1), bw * 0.7, Math.abs(y1 - y0)); }); });
C("candlestick", "Candlestick", ["finance", "trading", "crypto"], "OHLC candles appearing in sequence.", (ctx, w, h, pr, t, d, th) => { axes(ctx, w, h, th); const n = 20; let pv = 50; const bw = w / n; for (let i = 0; i < n; i++) { if (stag(pr, i, n, "stagger") <= 0) break; const o = pv, c = pv + (hash1(i * 3.3) - 0.45) * 14; const hi = Math.max(o, c) + hash1(i) * 6, lo = Math.min(o, c) - hash1(i * 2) * 6; pv = c; const y = (v: number) => h / 2 - ((v - 20) / 70) * h; const up = c >= o; ctx.strokeStyle = up ? th.colors.success : th.colors.danger; ctx.fillStyle = ctx.strokeStyle; const x = -w / 2 + i * bw + bw / 2; ctx.beginPath(); ctx.moveTo(x, y(hi)); ctx.lineTo(x, y(lo)); ctx.stroke(); ctx.fillRect(x - bw * 0.3, Math.min(y(o), y(c)), bw * 0.6, Math.max(2, Math.abs(y(o) - y(c)))); } });
C("pie", "Pie Chart", ["composition", "share"], "Pie slices sweeping in.", (ctx, w, h, pr, t, d) => { const R = Math.min(w, h) / 2; const tot = d.data.reduce((a, b) => a + b, 0) || 1; let a0 = -Math.PI / 2; const sweep = getEase("easeInOutCubic")(pr) * TAU; d.data.forEach((v, i) => { const a1 = a0 + (v / tot) * TAU; const end = Math.min(a1, -Math.PI / 2 + sweep); if (end > a0) { ctx.beginPath(); ctx.moveTo(0, 0); ctx.arc(0, 0, R, a0, end); ctx.closePath(); ctx.fillStyle = col(d, i); ctx.fill(); } a0 = a1; }); });
C("donut", "Donut", ["composition", "kpi"], "Donut with centre total.", (ctx, w, h, pr, t, d, th) => { const R = Math.min(w, h) / 2; const tot = d.data.reduce((a, b) => a + b, 0) || 1; let a0 = -Math.PI / 2; const sweep = getEase("easeInOutCubic")(pr) * TAU; ctx.lineWidth = R * 0.28; ctx.lineCap = "butt"; d.data.forEach((v, i) => { const a1 = a0 + (v / tot) * TAU; const end = Math.min(a1, -Math.PI / 2 + sweep); if (end > a0) { ctx.beginPath(); ctx.arc(0, 0, R * 0.84, a0 + 0.02, end - 0.02); ctx.strokeStyle = col(d, i); ctx.stroke(); } a0 = a1; }); text(ctx, `${Math.round(tot * pr)}`, 0, -6, { size: R * 0.32, weight: 700, color: th.colors.text, align: "center" }); text(ctx, d.title ?? "Total", 0, R * 0.2, { size: R * 0.11, color: th.colors.muted, align: "center" }); });
C("polar", "Polar Area", ["composition", "radial"], "Polar area wedges growing outward.", (ctx, w, h, pr, t, d) => { const R = Math.min(w, h) / 2; const n = norm(d.data); d.data.forEach((v, i) => { const k = getEase("overshoot")(stag(pr, i, d.data.length, "stagger")); const a0 = (i / d.data.length) * TAU - Math.PI / 2; ctx.beginPath(); ctx.moveTo(0, 0); ctx.arc(0, 0, R * n(v) * k, a0, a0 + TAU / d.data.length - 0.03); ctx.closePath(); ctx.fillStyle = withAlpha(col(d, i), 0.85); ctx.fill(); }); });
C("radar", "Radar", ["comparison", "skills"], "Radar polygon expanding from centre.", (ctx, w, h, pr, t, d, th) => { const R = Math.min(w, h) / 2, n = d.data.length, nn = norm(d.data); ctx.strokeStyle = withAlpha(th.colors.muted, 0.25); for (let r = 1; r <= 4; r++) { ctx.beginPath(); for (let i = 0; i <= n; i++) { const a = (i / n) * TAU - Math.PI / 2; ctx.lineTo(Math.cos(a) * R * r / 4, Math.sin(a) * R * r / 4); } ctx.stroke(); } const k = getEase("overshoot")(pr); ctx.beginPath(); d.data.forEach((v, i) => { const a = (i / n) * TAU - Math.PI / 2; ctx.lineTo(Math.cos(a) * R * nn(v) * k, Math.sin(a) * R * nn(v) * k); }); ctx.closePath(); ctx.fillStyle = withAlpha(col(d, 0), 0.3); ctx.fill(); ctx.strokeStyle = col(d, 0); ctx.lineWidth = 2.5; ctx.stroke(); });
C("scatter", "Scatter", ["correlation", "science"], "Points popping in by index.", (ctx, w, h, pr, t, d, th) => { axes(ctx, w, h, th); for (let i = 0; i < 60; i++) { const k = getEase("overshoot")(stag(pr, i, 60, "stagger")); const x = hash1(i * 1.7) * w - w / 2, y = h / 2 - (hash1(i * 1.7) * 0.7 + hash1(i * 5.1) * 0.3) * h; ctx.beginPath(); ctx.arc(x, y, 5 * k, 0, TAU); ctx.fillStyle = withAlpha(col(d, i), 0.85); ctx.fill(); } });
C("bubble", "Bubble", ["correlation", "market"], "Bubbles sized by value.", (ctx, w, h, pr, t, d, th) => { axes(ctx, w, h, th); d.data.forEach((v, i) => { const k = getEase("overshoot")(stag(pr, i, d.data.length, "stagger")); const x = -w / 2 + (i + 0.5) / d.data.length * w, y = (hash1(i * 3) - 0.5) * h * 0.7; ctx.beginPath(); ctx.arc(x, y, Math.sqrt(v) * 4 * k, 0, TAU); ctx.fillStyle = withAlpha(col(d, i), 0.6); ctx.fill(); }); });
C("heatmap", "Heatmap", ["density", "activity"], "Grid cells warming up diagonally.", (ctx, w, h, pr, t, d) => { const cols = 14, rows = 7, cw = w / cols, ch = h / rows; for (let y = 0; y < rows; y++) for (let x = 0; x < cols; x++) { const k = clamp(pr * 2 - (x + y) / (cols + rows)); const v = hash1(x * 7 + y * 13); rr(ctx, -w / 2 + x * cw + 2, -h / 2 + y * ch + 2, cw - 4, ch - 4, 4); ctx.fillStyle = withAlpha(mixColor(col(d, 1), col(d, 0), v), 0.15 + v * 0.85 * k); ctx.fill(); } });
C("calendarHeat", "Contribution Graph", ["activity", "developer"], "GitHub-style contribution grid.", (ctx, w, h, pr, t, d, th) => { const cols = 26, rows = 7, s = Math.min(w / cols, h / rows); for (let x = 0; x < cols; x++) for (let y = 0; y < rows; y++) { const v = hash1(x * 3.1 + y * 17.3); const on = pr * cols > x; rr(ctx, -w / 2 + x * s + 1.5, -h / 2 + y * s + 1.5, s - 3, s - 3, 3); ctx.fillStyle = on ? withAlpha(col(d, 0), v < 0.3 ? 0.12 : v) : th.colors.surface2; ctx.fill(); } });
C("funnel", "Funnel", ["conversion", "marketing"], "Conversion funnel stages.", (ctx, w, h, pr, t, d, th) => { const n = d.data.length, sh = h / n, mx = Math.max(...d.data); d.data.forEach((v, i) => { const k = getEase("emphasized")(stag(pr, i, n, "stagger")); const ww = (v / mx) * w * k, nw = ((d.data[i + 1] ?? v * 0.7) / mx) * w * k; ctx.beginPath(); ctx.moveTo(-ww / 2, -h / 2 + i * sh); ctx.lineTo(ww / 2, -h / 2 + i * sh); ctx.lineTo(nw / 2, -h / 2 + (i + 1) * sh - 4); ctx.lineTo(-nw / 2, -h / 2 + (i + 1) * sh - 4); ctx.closePath(); ctx.fillStyle = col(d, i); ctx.fill(); text(ctx, `${d.labels?.[i] ?? `Stage ${i + 1}`} · ${Math.round(v * k).toLocaleString("en-US")}`, 0, -h / 2 + i * sh + sh / 2, { size: 15, weight: 600, color: "#fff", align: "center" }); void th; }); });
C("counter", "Counter", ["kpi", "number"], "Large number counting up.", (ctx, w, h, pr, t, d, th) => { const v = (d.value ?? d.data[d.data.length - 1] ?? 100) * getEase("easeOutExpo")(pr); text(ctx, `${d.prefix ?? ""}${Math.round(v).toLocaleString("en-US")}${d.suffix ?? ""}`, 0, 0, { size: Math.min(h * 0.7, w / 5), weight: 750, color: th.colors.text, align: "center" }); if (d.title) text(ctx, d.title, 0, h * 0.42, { size: Math.min(h * 0.14, 22), color: th.colors.muted, align: "center" }); });
C("kpi", "KPI Tile", ["kpi", "dashboard"], "KPI tile with delta and sparkline.", (ctx, w, h, pr, t, d, th) => { rr(ctx, -w / 2, -h / 2, w, h, 18); ctx.fillStyle = th.colors.surface; ctx.fill(); ctx.strokeStyle = th.colors.border; ctx.stroke(); text(ctx, d.title ?? "Conversion rate", -w / 2 + 20, -h / 2 + 28, { size: 14, color: th.colors.muted }); const v = (d.value ?? 4.8) * getEase("easeOutExpo")(pr); text(ctx, `${v.toFixed(1)}${d.suffix ?? "%"}`, -w / 2 + 20, -h / 2 + 70, { size: 34, weight: 720, color: th.colors.text }); ctx.save(); ctx.translate(w * 0.2, h * 0.2); CHARTS.sparkline.draw(ctx, w * 0.45, h * 0.35, pr, t, d, th); ctx.restore(); });
C("progressRing", "Progress Ring", ["progress", "goal"], "Circular progress ring with percentage.", (ctx, w, h, pr, t, d, th) => { const R = Math.min(w, h) / 2 - 10; const v = (d.value ?? 76) / 100 * getEase("easeInOutCubic")(pr); ctx.lineWidth = R * 0.16; ctx.lineCap = "round"; ctx.strokeStyle = th.colors.surface2; ctx.beginPath(); ctx.arc(0, 0, R, 0, TAU); ctx.stroke(); ctx.strokeStyle = linearGrad(ctx, [col(d, 0), col(d, 1)], -R, -R, R, R); ctx.beginPath(); ctx.arc(0, 0, R, -Math.PI / 2, -Math.PI / 2 + v * TAU); ctx.stroke(); text(ctx, `${Math.round(v * 100)}%`, 0, 0, { size: R * 0.45, weight: 720, color: th.colors.text, align: "center" }); });
C("progressBars", "Progress Bars", ["progress", "goals"], "Multiple labelled progress bars.", (ctx, w, h, pr, t, d, th) => { const n = d.data.length, rh = h / n; d.data.forEach((v, i) => { const k = getEase("emphasized")(stag(pr, i, n, "stagger")); const y = -h / 2 + i * rh + rh / 2; text(ctx, d.labels?.[i] ?? `Goal ${i + 1}`, -w / 2, y - 12, { size: 14, color: th.colors.text }); text(ctx, `${Math.round(Math.min(100, v) * k)}%`, w / 2, y - 12, { size: 13, color: th.colors.muted, align: "right" }); rr(ctx, -w / 2, y + 4, w, 10, 5); ctx.fillStyle = th.colors.surface2; ctx.fill(); rr(ctx, -w / 2, y + 4, w * Math.min(100, v) / 100 * k, 10, 5); ctx.fillStyle = col(d, i); ctx.fill(); }); });
C("gauge", "Gauge", ["kpi", "performance"], "Speedometer gauge with needle settle.", (ctx, w, h, pr, t, d, th) => { const R = Math.min(w / 2, h) * 0.9; const v = (d.value ?? 72) / 100; ctx.lineWidth = R * 0.14; ctx.lineCap = "round"; ctx.strokeStyle = th.colors.surface2; ctx.beginPath(); ctx.arc(0, h * 0.3, R, Math.PI, TAU); ctx.stroke(); const k = getEase("easeOutElastic")(pr) * v; ctx.strokeStyle = linearGrad(ctx, [th.colors.success, th.colors.warning, th.colors.danger], -R, 0, R, 0); ctx.beginPath(); ctx.arc(0, h * 0.3, R, Math.PI, Math.PI + k * Math.PI); ctx.stroke(); const a = Math.PI + k * Math.PI; ctx.strokeStyle = th.colors.text; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(0, h * 0.3); ctx.lineTo(Math.cos(a) * R * 0.75, h * 0.3 + Math.sin(a) * R * 0.75); ctx.stroke(); text(ctx, `${Math.round(k * 100)}`, 0, h * 0.18, { size: R * 0.3, weight: 720, color: th.colors.text, align: "center" }); });
C("timeline", "Timeline", ["roadmap", "history"], "Milestones along a drawing line.", (ctx, w, h, pr, t, d, th) => { const labels = d.labels ?? ["Idea", "Seed", "Beta", "Launch", "Scale"]; const n = labels.length; ctx.strokeStyle = th.colors.border; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(-w / 2, 0); ctx.lineTo(w / 2, 0); ctx.stroke(); ctx.strokeStyle = col(d, 0); ctx.beginPath(); ctx.moveTo(-w / 2, 0); ctx.lineTo(-w / 2 + w * pr, 0); ctx.stroke(); labels.forEach((l, i) => { const x = -w / 2 + (i / (n - 1)) * w; const on = pr >= i / (n - 1) - 0.01; ctx.beginPath(); ctx.arc(x, 0, on ? 10 : 7, 0, TAU); ctx.fillStyle = on ? col(d, 0) : th.colors.surface2; ctx.fill(); text(ctx, l, x, (i % 2 ? 1 : -1) * 36, { size: 15, weight: 600, color: on ? th.colors.text : th.colors.muted, align: "center" }); }); });
C("network", "Network Graph", ["graph", "relationships", "ai"], "Force-style graph with edges drawing in.", (ctx, w, h, pr, t, d, th) => { const n = 18; const pts = Array.from({ length: n }, (_, i) => { const a = (i / n) * TAU + hash1(i) * 0.5, r = (i === 0 ? 0 : 0.35 + hash1(i * 3) * 0.6) * Math.min(w, h) / 2; return [Math.cos(a) * r + Math.sin(t + i) * 4, Math.sin(a) * r + Math.cos(t * 0.8 + i) * 4]; }); for (let i = 1; i < n; i++) { const j = i < 6 ? 0 : 1 + Math.floor(hash1(i * 7) * 5); const k = stag(pr, i, n, "stagger"); ctx.strokeStyle = withAlpha(col(d, i), 0.5); ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(pts[j][0], pts[j][1]); ctx.lineTo(pts[j][0] + (pts[i][0] - pts[j][0]) * k, pts[j][1] + (pts[i][1] - pts[j][1]) * k); ctx.stroke(); } pts.forEach(([x, y], i) => { const k = getEase("overshoot")(stag(pr, i, n, "stagger")); ctx.beginPath(); ctx.arc(x, y, (i === 0 ? 16 : 7) * k, 0, TAU); ctx.fillStyle = i === 0 ? th.colors.text : col(d, i); ctx.fill(); }); });
C("treemap", "Treemap", ["hierarchy", "composition"], "Squarified-ish treemap tiles.", (ctx, w, h, pr, t, d, th) => { const vals = [...d.data].sort((a, b) => b - a); const tot = vals.reduce((a, b) => a + b, 0) || 1; let x = -w / 2, y = -h / 2, rw = w, rh = h; vals.forEach((v, i) => { const f = v / tot * (w * h) / (rw * rh) * (tot / vals.slice(i).reduce((a, b) => a + b, 0)) * (vals.slice(i).reduce((a, b) => a + b, 0) / tot); const horiz = rw > rh; const s = horiz ? rw * Math.min(1, f) : rh * Math.min(1, f); const k = getEase("emphasized")(stag(pr, i, vals.length, "stagger")); const bx = x, by = y, bw = horiz ? s : rw, bh = horiz ? rh : s; ctx.save(); ctx.globalAlpha *= k; rr(ctx, bx + 2, by + 2, bw - 4, bh - 4, 8); ctx.fillStyle = col(d, i); ctx.fill(); if (bw > 60 && bh > 30) text(ctx, d.labels?.[i] ?? `${Math.round((v / tot) * 100)}%`, bx + 12, by + 20, { size: 14, weight: 600, color: "#fff" }); ctx.restore(); if (horiz) { x += s; rw -= s; } else { y += s; rh -= s; } void th; }); });
C("leaderboard", "Leaderboard", ["ranking", "gaming", "sales"], "Ranked rows with bars and positions.", (ctx, w, h, pr, t, d, th) => { const n = Math.min(6, d.data.length); const idx = d.data.map((v, i) => [v, i]).sort((a, b) => b[0] - a[0]).slice(0, n); const mx = idx[0][0]; const rh = h / n; idx.forEach(([v, i], r) => { const k = getEase("emphasized")(stag(pr, r, n, "stagger")); const y = -h / 2 + r * rh + rh / 2; text(ctx, `#${r + 1}`, -w / 2, y, { size: 16, weight: 700, color: r === 0 ? th.colors.warning : th.colors.muted }); text(ctx, d.labels?.[i] ?? `Team ${i + 1}`, -w / 2 + 50, y, { size: 15, color: th.colors.text }); rr(ctx, -w / 2 + w * 0.4, y - 8, w * 0.5 * (v / mx) * k, 16, 8); ctx.fillStyle = col(d, r); ctx.fill(); }); });
C("comparison", "Comparison Bars", ["versus", "comparison"], "Before/after comparison pair.", (ctx, w, h, pr, t, d, th) => { const a = d.data[0] ?? 30, b = d.data[1] ?? 90; const mx = Math.max(a, b); [a, b].forEach((v, i) => { const k = getEase("emphasized")(clamp(pr * 1.5 - i * 0.4)); const bh = (v / mx) * h * 0.75 * k; const x = (i - 0.5) * w * 0.4; rr(ctx, x - w * 0.12, h / 2 - bh, w * 0.24, bh, 12); ctx.fillStyle = i ? col(d, 0) : th.colors.surface2; ctx.fill(); text(ctx, `${Math.round(v * k)}${d.suffix ?? ""}`, x, h / 2 - bh - 24, { size: 28, weight: 720, color: th.colors.text, align: "center" }); text(ctx, d.labels?.[i] ?? (i ? "With us" : "Before"), x, h / 2 + 22, { size: 15, color: th.colors.muted, align: "center" }); }); });

export function drawChart(ctx: Ctx2D, kind: string, w: number, h: number, t: number, props: ChartProps, th: Theme) {
  const def = CHARTS[kind] ?? CHARTS.bar;
  const dur = props.duration ?? 1.6;
  const pr = props.animation === "none" ? 1 : clamp(t / dur);
  const data = props.data?.length ? props.data : [12, 19, 14, 25, 22, 31, 28, 38];
  const colors = props.colors?.length ? props.colors : [th.colors.primary, th.colors.secondary, th.colors.accent, th.colors.success, th.colors.warning];
  ctx.save();
  if (props.animation === "fade") ctx.globalAlpha *= pr;
  def.draw(ctx, w, h, props.animation === "fade" ? 1 : pr, t, { ...props, data, colors }, th);
  ctx.restore();
}

registerNodeRenderer("chart", (rc, node) => {
  const t = (rc.frame - node.timing.start) / rc.fps - p<number>(node, "animDelay", 0) / rc.fps;
  const w = p<number>(node, "w", 700), h = p<number>(node, "h", 400);
  if (p<boolean>(node, "card", false)) { rr(rc.ctx, -w / 2 - 28, -h / 2 - 48, w + 56, h + 80, 20); rc.ctx.fillStyle = rc.theme.colors.surface; rc.ctx.fill(); rc.ctx.strokeStyle = rc.theme.colors.border; rc.ctx.stroke(); if (node.props.title) text(rc.ctx, String(node.props.title), -w / 2, -h / 2 - 22, { size: 18, weight: 650, color: rc.theme.colors.text }); }
  drawChart(rc.ctx, p<string>(node, "kind", "bar"), w, h, Math.max(0, t), node.props as ChartProps, rc.theme);
}, (node) => ({ w: (node.props.w as number) ?? 700, h: (node.props.h as number) ?? 400 }));
