// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "animated-bar-chart".
import { AnimatedBarChart } from '../framecn/animated-bar-chart'
import { animatedBarChartConfig } from '../framecn/animated-bar-chart/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={AnimatedBarChart} config={animatedBarChartConfig} />
}
