// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "ai-generate-overlay".
import { AIGenerateOverlay } from '../framecn/ai-generate-overlay'
import { aiGenerateOverlayConfig } from '../framecn/ai-generate-overlay/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={AIGenerateOverlay} config={aiGenerateOverlayConfig} />
}
