// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "ai-generation-canvas".
import { AIGenerationCanvas } from '../framecn/ai-generation-canvas'
import { aiGenerationCanvasConfig } from '../framecn/ai-generation-canvas/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={AIGenerationCanvas} config={aiGenerationCanvasConfig} />
}
