// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "animated-line-chart".
import { AnimatedLineChart } from '../framecn/animated-line-chart'
import { animatedLineChartConfig } from '../framecn/animated-line-chart/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={AnimatedLineChart} config={animatedLineChartConfig} />
}
