// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "backdrop".
import { Backdrop } from '../framecn/backdrop'
import { backdropConfig } from '../framecn/backdrop/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={Backdrop} config={backdropConfig} />
}
