// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "blur-reveal".
import { BlurReveal } from '../framecn/blur-reveal'
import { blurRevealConfig } from '../framecn/blur-reveal/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={BlurReveal} config={blurRevealConfig} />
}
