// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "blur-out-up".
import { BlurOutUp } from '../framecn/blur-out-up'
import { blurOutUpConfig } from '../framecn/blur-out-up/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={BlurOutUp} config={blurOutUpConfig} />
}
