// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "bottom-up-letters".
import { BottomUpLetters } from '../framecn/bottom-up-letters'
import { bottomUpLettersConfig } from '../framecn/bottom-up-letters/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={BottomUpLetters} config={bottomUpLettersConfig} />
}
