// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "bounding-box-selector".
import { BoundingBoxSelector } from '../framecn/bounding-box-selector'
import { boundingBoxSelectorConfig } from '../framecn/bounding-box-selector/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={BoundingBoxSelector} config={boundingBoxSelectorConfig} />
}
