// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "browser-flow".
import { BrowserFlow } from '../framecn/browser-flow'
import { browserFlowConfig } from '../framecn/browser-flow/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={BrowserFlow} config={browserFlowConfig} />
}
