// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "code-diff-wipe".
import { CodeDiffWipe } from '../framecn/code-diff-wipe'
import { codeDiffWipeConfig } from '../framecn/code-diff-wipe/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CodeDiffWipe} config={codeDiffWipeConfig} />
}
