// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-texture".
import { CaptionTexture } from '../framecn/caption-texture'
import { captionTextureConfig } from '../framecn/caption-texture/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionTexture} config={captionTextureConfig} />
}
