// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "confetti".
import { Confetti } from '../framecn/confetti'
import { confettiConfig } from '../framecn/confetti/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={Confetti} config={confettiConfig} />
}
