// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-neon-accent".
import { CaptionNeonAccent } from '../framecn/caption-neon-accent'
import { captionNeonAccentConfig } from '../framecn/caption-neon-accent/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionNeonAccent} config={captionNeonAccentConfig} />
}
