// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-gradient-fill".
import { CaptionGradientFill } from '../framecn/caption-gradient-fill'
import { captionGradientFillConfig } from '../framecn/caption-gradient-fill/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionGradientFill} config={captionGradientFillConfig} />
}
