// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-glitch-rgb".
import { CaptionGlitchRgb } from '../framecn/caption-glitch-rgb'
import { captionGlitchRgbConfig } from '../framecn/caption-glitch-rgb/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionGlitchRgb} config={captionGlitchRgbConfig} />
}
