// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-editorial-emphasis".
import { CaptionEditorialEmphasis } from '../framecn/caption-editorial-emphasis'
import { captionEditorialEmphasisConfig } from '../framecn/caption-editorial-emphasis/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionEditorialEmphasis} config={captionEditorialEmphasisConfig} />
}
