// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-parallax-layers".
import { CaptionParallaxLayers } from '../framecn/caption-parallax-layers'
import { captionParallaxLayersConfig } from '../framecn/caption-parallax-layers/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionParallaxLayers} config={captionParallaxLayersConfig} />
}
