// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "code-accordion".
import { CodeAccordion } from '../framecn/code-accordion'
import { codeAccordionConfig } from '../framecn/code-accordion/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CodeAccordion} config={codeAccordionConfig} />
}
