// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-emoji-pop".
import { CaptionEmojiPop } from '../framecn/caption-emoji-pop'
import { captionEmojiPopConfig } from '../framecn/caption-emoji-pop/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionEmojiPop} config={captionEmojiPopConfig} />
}
