// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "chat-to-preview-layout".
import { ChatToPreviewLayout } from '../framecn/chat-to-preview-layout'
import { chatToPreviewLayoutConfig } from '../framecn/chat-to-preview-layout/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ChatToPreviewLayout} config={chatToPreviewLayoutConfig} />
}
