// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-highlight".
import { CaptionHighlight } from '../framecn/caption-highlight'
import { captionHighlightConfig } from '../framecn/caption-highlight/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionHighlight} config={captionHighlightConfig} />
}
