// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-kinetic-slam".
import { CaptionKineticSlam } from '../framecn/caption-kinetic-slam'
import { captionKineticSlamConfig } from '../framecn/caption-kinetic-slam/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionKineticSlam} config={captionKineticSlamConfig} />
}
