// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "cursor-flow".
import { CursorFlow } from '../framecn/cursor-flow'
import { cursorFlowConfig } from '../framecn/cursor-flow/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CursorFlow} config={cursorFlowConfig} />
}
