// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-particle-burst".
import { CaptionParticleBurst } from '../framecn/caption-particle-burst'
import { captionParticleBurstConfig } from '../framecn/caption-particle-burst/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionParticleBurst} config={captionParticleBurstConfig} />
}
