// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-weight-shift".
import { CaptionWeightShift } from '../framecn/caption-weight-shift'
import { captionWeightShiftConfig } from '../framecn/caption-weight-shift/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionWeightShift} config={captionWeightShiftConfig} />
}
