// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-matrix-decode".
import { CaptionMatrixDecode } from '../framecn/caption-matrix-decode'
import { captionMatrixDecodeConfig } from '../framecn/caption-matrix-decode/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionMatrixDecode} config={captionMatrixDecodeConfig} />
}
