// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-clip-wipe".
import { CaptionClipWipe } from '../framecn/caption-clip-wipe'
import { captionClipWipeConfig } from '../framecn/caption-clip-wipe/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionClipWipe} config={captionClipWipeConfig} />
}
