// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "chromatic-aberration-wipe".
import { ChromaticAberrationWipe } from '../framecn/chromatic-aberration-wipe'
import { chromaticAberrationWipeConfig } from '../framecn/chromatic-aberration-wipe/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ChromaticAberrationWipe} config={chromaticAberrationWipeConfig} />
}
