// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-pill-karaoke".
import { CaptionPillKaraoke } from '../framecn/caption-pill-karaoke'
import { captionPillKaraokeConfig } from '../framecn/caption-pill-karaoke/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionPillKaraoke} config={captionPillKaraokeConfig} />
}
