// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "caption-neon-glow".
import { CaptionNeonGlow } from '../framecn/caption-neon-glow'
import { captionNeonGlowConfig } from '../framecn/caption-neon-glow/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={CaptionNeonGlow} config={captionNeonGlowConfig} />
}
