// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "drag-and-drop-flow".
import { DragAndDropFlow } from '../framecn/drag-and-drop-flow'
import { dragAndDropFlowConfig } from '../framecn/drag-and-drop-flow/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={DragAndDropFlow} config={dragAndDropFlowConfig} />
}
