// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "device-mockup-zoom".
import { DeviceMockupZoom } from '../framecn/device-mockup-zoom'
import { deviceMockupZoomConfig } from '../framecn/device-mockup-zoom/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={DeviceMockupZoom} config={deviceMockupZoomConfig} />
}
