// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "directional-wipe".
import { DirectionalWipe } from '../framecn/directional-wipe'
import { directionalWipeConfig } from '../framecn/directional-wipe/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={DirectionalWipe} config={directionalWipeConfig} />
}
