// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "data-flow-pipes".
import { DataFlowPipes } from '../framecn/data-flow-pipes'
import { dataFlowPipesConfig } from '../framecn/data-flow-pipes/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={DataFlowPipes} config={dataFlowPipesConfig} />
}
