// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "dynamic-grid".
import { DynamicGrid } from '../framecn/dynamic-grid'
import { dynamicGridConfig } from '../framecn/dynamic-grid/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={DynamicGrid} config={dynamicGridConfig} />
}
