// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "dashboard-populate".
import { DashboardPopulate } from '../framecn/dashboard-populate'
import { dashboardPopulateConfig } from '../framecn/dashboard-populate/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={DashboardPopulate} config={dashboardPopulateConfig} />
}
