// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "ecosystem-constellation".
import { EcosystemConstellation } from '../framecn/ecosystem-constellation'
import { ecosystemConstellationConfig } from '../framecn/ecosystem-constellation/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={EcosystemConstellation} config={ecosystemConstellationConfig} />
}
