// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "focus-blur-resolve".
import { FocusBlurResolve } from '../framecn/focus-blur-resolve'
import { focusBlurResolveConfig } from '../framecn/focus-blur-resolve/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={FocusBlurResolve} config={focusBlurResolveConfig} />
}
