// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "frosted-glass-wipe".
import { FrostedGlassWipe } from '../framecn/frosted-glass-wipe'
import { frostedGlassWipeConfig } from '../framecn/frosted-glass-wipe/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={FrostedGlassWipe} config={frostedGlassWipeConfig} />
}
