// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "fade-through".
import { FadeThrough } from '../framecn/fade-through'
import { fadeThroughConfig } from '../framecn/fade-through/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={FadeThrough} config={fadeThroughConfig} />
}
