// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "grid-pixelate-wipe".
import { GridPixelateWipe } from '../framecn/grid-pixelate-wipe'
import { gridPixelateWipeConfig } from '../framecn/grid-pixelate-wipe/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={GridPixelateWipe} config={gridPixelateWipeConfig} />
}
