// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "glass-code-block".
import { GlassCodeBlock } from '../framecn/glass-code-block'
import { glassCodeBlockConfig } from '../framecn/glass-code-block/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={GlassCodeBlock} config={glassCodeBlockConfig} />
}
