// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "hero-device-assemble".
import { HeroDeviceAssemble } from '../framecn/hero-device-assemble'
import { heroDeviceAssembleConfig } from '../framecn/hero-device-assemble/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={HeroDeviceAssemble} config={heroDeviceAssembleConfig} />
}
