// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "infinite-marquee".
import { InfiniteMarquee } from '../framecn/infinite-marquee'
import { infiniteMarqueeConfig } from '../framecn/infinite-marquee/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={InfiniteMarquee} config={infiniteMarqueeConfig} />
}
