// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "inline-highlight".
import { InlineHighlight } from '../framecn/inline-highlight'
import { inlineHighlightConfig } from '../framecn/inline-highlight/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={InlineHighlight} config={inlineHighlightConfig} />
}
