// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "infinite-bento-pan".
import { InfiniteBentoPan } from '../framecn/infinite-bento-pan'
import { infiniteBentoPanConfig } from '../framecn/infinite-bento-pan/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={InfiniteBentoPan} config={infiniteBentoPanConfig} />
}
