// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "image-expand-to-fullscreen".
import { ImageExpandToFullscreen } from '../framecn/image-expand-to-fullscreen'
import { imageExpandToFullscreenConfig } from '../framecn/image-expand-to-fullscreen/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ImageExpandToFullscreen} config={imageExpandToFullscreenConfig} />
}
