// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "kinetic-type-mask".
import { KineticTypeMask } from '../framecn/kinetic-type-mask'
import { kineticTypeMaskConfig } from '../framecn/kinetic-type-mask/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={KineticTypeMask} config={kineticTypeMaskConfig} />
}
