// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "logo-enter".
import { LogoEnter } from '../framecn/logo-enter'
import { logoEnterConfig } from '../framecn/logo-enter/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={LogoEnter} config={logoEnterConfig} />
}
