// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "line-by-line-slide".
import { LineByLineSlide } from '../framecn/line-by-line-slide'
import { lineByLineSlideConfig } from '../framecn/line-by-line-slide/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={LineByLineSlide} config={lineByLineSlideConfig} />
}
