// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "live-code-compilation".
import { LiveCodeCompilation } from '../framecn/live-code-compilation'
import { liveCodeCompilationConfig } from '../framecn/live-code-compilation/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={LiveCodeCompilation} config={liveCodeCompilationConfig} />
}
