// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "landing-code-showcase".
import { LandingCodeShowcase } from '../framecn/landing-code-showcase'
import { landingCodeShowcaseConfig } from '../framecn/landing-code-showcase/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={LandingCodeShowcase} config={landingCodeShowcaseConfig} />
}
