// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "matrix-decode".
import { MatrixDecode } from '../framecn/matrix-decode'
import { matrixDecodeConfig } from '../framecn/matrix-decode/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={MatrixDecode} config={matrixDecodeConfig} />
}
