// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "marker-highlight".
import { MarkerHighlight } from '../framecn/marker-highlight'
import { markerHighlightConfig } from '../framecn/marker-highlight/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={MarkerHighlight} config={markerHighlightConfig} />
}
