// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "micro-scale-fade".
import { MicroScaleFade } from '../framecn/micro-scale-fade'
import { microScaleFadeConfig } from '../framecn/micro-scale-fade/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={MicroScaleFade} config={microScaleFadeConfig} />
}
