// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "morphing-modal".
import { MorphingModal } from '../framecn/morphing-modal'
import { morphingModalConfig } from '../framecn/morphing-modal/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={MorphingModal} config={morphingModalConfig} />
}
