// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "mesh-gradient-bg".
import { MeshGradientBg } from '../framecn/mesh-gradient-bg'
import { meshGradientBgConfig } from '../framecn/mesh-gradient-bg/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={MeshGradientBg} config={meshGradientBgConfig} />
}
