// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "masked-slide-reveal".
import { MaskedSlideReveal } from '../framecn/masked-slide-reveal'
import { maskedSlideRevealConfig } from '../framecn/masked-slide-reveal/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={MaskedSlideReveal} config={maskedSlideRevealConfig} />
}
