// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "mask-reveal-up".
import { MaskRevealUp } from '../framecn/mask-reveal-up'
import { maskRevealUpConfig } from '../framecn/mask-reveal-up/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={MaskRevealUp} config={maskRevealUpConfig} />
}
