// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "pricing-tier-focus".
import { PricingTierFocus } from '../framecn/pricing-tier-focus'
import { pricingTierFocusConfig } from '../framecn/pricing-tier-focus/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={PricingTierFocus} config={pricingTierFocusConfig} />
}
