// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "product-launch-trailer".
import { ProductLaunchTrailer } from '../framecn/product-launch-trailer'
import { productLaunchTrailerConfig } from '../framecn/product-launch-trailer/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ProductLaunchTrailer} config={productLaunchTrailerConfig} />
}
