// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "pipeline-journey".
import { PipelineJourney } from '../framecn/pipeline-journey'
import { pipelineJourneyConfig } from '../framecn/pipeline-journey/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={PipelineJourney} config={pipelineJourneyConfig} />
}
