// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "per-character-rise".
import { PerCharacterRise } from '../framecn/per-character-rise'
import { perCharacterRiseConfig } from '../framecn/per-character-rise/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={PerCharacterRise} config={perCharacterRiseConfig} />
}
