// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "perspective-marquee".
import { PerspectiveMarquee } from '../framecn/perspective-marquee'
import { perspectiveMarqueeConfig } from '../framecn/perspective-marquee/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={PerspectiveMarquee} config={perspectiveMarqueeConfig} />
}
