// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "pulsing-indicator".
import { PulsingIndicator } from '../framecn/pulsing-indicator'
import { pulsingIndicatorConfig } from '../framecn/pulsing-indicator/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={PulsingIndicator} config={pulsingIndicatorConfig} />
}
