// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "per-word-crossfade".
import { PerWordCrossfade } from '../framecn/per-word-crossfade'
import { perWordCrossfadeConfig } from '../framecn/per-word-crossfade/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={PerWordCrossfade} config={perWordCrossfadeConfig} />
}
