// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "progress-steps".
import { ProgressSteps } from '../framecn/progress-steps'
import { progressStepsConfig } from '../framecn/progress-steps/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ProgressSteps} config={progressStepsConfig} />
}
