// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "rgb-glitch-text".
import { RGBGlitchText } from '../framecn/rgb-glitch-text'
import { rgbGlitchTextConfig } from '../framecn/rgb-glitch-text/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={RGBGlitchText} config={rgbGlitchTextConfig} />
}
