// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "simulated-cursor".
import { SimulatedCursor } from '../framecn/simulated-cursor'
import { simulatedCursorConfig } from '../framecn/simulated-cursor/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SimulatedCursor} config={simulatedCursorConfig} />
}
