// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-mesh-gradient".
import { ShaderMeshGradient } from '../framecn/shader-mesh-gradient'
import { shaderMeshGradientConfig } from '../framecn/shader-mesh-gradient/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderMeshGradient} config={shaderMeshGradientConfig} />
}
