// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "slot-machine-roll".
import { SlotMachineRoll } from '../framecn/slot-machine-roll'
import { slotMachineRollConfig } from '../framecn/slot-machine-roll/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SlotMachineRoll} config={slotMachineRollConfig} />
}
