// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "scale-down-fade".
import { ScaleDownFade } from '../framecn/scale-down-fade'
import { scaleDownFadeConfig } from '../framecn/scale-down-fade/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ScaleDownFade} config={scaleDownFadeConfig} />
}
