// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-smoke-ring".
import { ShaderSmokeRing } from '../framecn/shader-smoke-ring'
import { shaderSmokeRingConfig } from '../framecn/shader-smoke-ring/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderSmokeRing} config={shaderSmokeRingConfig} />
}
