// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-metaballs".
import { ShaderMetaballs } from '../framecn/shader-metaballs'
import { shaderMetaballsConfig } from '../framecn/shader-metaballs/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderMetaballs} config={shaderMetaballsConfig} />
}
