// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-spiral".
import { ShaderSpiral } from '../framecn/shader-spiral'
import { shaderSpiralConfig } from '../framecn/shader-spiral/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderSpiral} config={shaderSpiralConfig} />
}
