// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-voronoi".
import { ShaderVoronoi } from '../framecn/shader-voronoi'
import { shaderVoronoiConfig } from '../framecn/shader-voronoi/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderVoronoi} config={shaderVoronoiConfig} />
}
