// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-perlin-noise".
import { ShaderPerlinNoise } from '../framecn/shader-perlin-noise'
import { shaderPerlinNoiseConfig } from '../framecn/shader-perlin-noise/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderPerlinNoise} config={shaderPerlinNoiseConfig} />
}
