// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-grain-gradient".
import { ShaderGrainGradient } from '../framecn/shader-grain-gradient'
import { shaderGrainGradientConfig } from '../framecn/shader-grain-gradient/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderGrainGradient} config={shaderGrainGradientConfig} />
}
