// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shared-axis-y".
import { SharedAxisY } from '../framecn/shared-axis-y'
import { sharedAxisYConfig } from '../framecn/shared-axis-y/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SharedAxisY} config={sharedAxisYConfig} />
}
