// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "short-slide-right".
import { ShortSlideRight } from '../framecn/short-slide-right'
import { shortSlideRightConfig } from '../framecn/short-slide-right/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShortSlideRight} config={shortSlideRightConfig} />
}
