// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "spring-pop-in".
import { SpringPopIn } from '../framecn/spring-pop-in'
import { springPopInConfig } from '../framecn/spring-pop-in/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SpringPopIn} config={springPopInConfig} />
}
