// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-warp".
import { ShaderWarp } from '../framecn/shader-warp'
import { shaderWarpConfig } from '../framecn/shader-warp/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderWarp} config={shaderWarpConfig} />
}
