// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "staggered-fade-up".
import { StaggeredFadeUp } from '../framecn/staggered-fade-up'
import { staggeredFadeUpConfig } from '../framecn/staggered-fade-up/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={StaggeredFadeUp} config={staggeredFadeUpConfig} />
}
