// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "success-confetti".
import { SuccessConfetti } from '../framecn/success-confetti'
import { successConfettiConfig } from '../framecn/success-confetti/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SuccessConfetti} config={successConfettiConfig} />
}
