// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shared-axis-z".
import { SharedAxisZ } from '../framecn/shared-axis-z'
import { sharedAxisZConfig } from '../framecn/shared-axis-z/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SharedAxisZ} config={sharedAxisZConfig} />
}
