// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "strikethrough-replace".
import { StrikethroughReplace } from '../framecn/strikethrough-replace'
import { strikethroughReplaceConfig } from '../framecn/strikethrough-replace/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={StrikethroughReplace} config={strikethroughReplaceConfig} />
}
