// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-dot-orbit".
import { ShaderDotOrbit } from '../framecn/shader-dot-orbit'
import { shaderDotOrbitConfig } from '../framecn/shader-dot-orbit/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderDotOrbit} config={shaderDotOrbitConfig} />
}
