// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-god-rays".
import { ShaderGodRays } from '../framecn/shader-god-rays'
import { shaderGodRaysConfig } from '../framecn/shader-god-rays/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderGodRays} config={shaderGodRaysConfig} />
}
