// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-color-panels".
import { ShaderColorPanels } from '../framecn/shader-color-panels'
import { shaderColorPanelsConfig } from '../framecn/shader-color-panels/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderColorPanels} config={shaderColorPanelsConfig} />
}
