// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-swirl".
import { ShaderSwirl } from '../framecn/shader-swirl'
import { shaderSwirlConfig } from '../framecn/shader-swirl/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderSwirl} config={shaderSwirlConfig} />
}
