// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-neuro-noise".
import { ShaderNeuroNoise } from '../framecn/shader-neuro-noise'
import { shaderNeuroNoiseConfig } from '../framecn/shader-neuro-noise/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderNeuroNoise} config={shaderNeuroNoiseConfig} />
}
