// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-liquid-metal".
import { ShaderLiquidMetal } from '../framecn/shader-liquid-metal'
import { shaderLiquidMetalConfig } from '../framecn/shader-liquid-metal/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderLiquidMetal} config={shaderLiquidMetalConfig} />
}
