// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "soft-blur-in".
import { SoftBlurIn } from '../framecn/soft-blur-in'
import { softBlurInConfig } from '../framecn/soft-blur-in/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SoftBlurIn} config={softBlurInConfig} />
}
