// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-simplex-noise".
import { ShaderSimplexNoise } from '../framecn/shader-simplex-noise'
import { shaderSimplexNoiseConfig } from '../framecn/shader-simplex-noise/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderSimplexNoise} config={shaderSimplexNoiseConfig} />
}
