// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "staggered-bento-grid".
import { StaggeredBentoGrid } from '../framecn/staggered-bento-grid'
import { staggeredBentoGridConfig } from '../framecn/staggered-bento-grid/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={StaggeredBentoGrid} config={staggeredBentoGridConfig} />
}
