// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "spring-scale-in".
import { SpringScaleIn } from '../framecn/spring-scale-in'
import { springScaleInConfig } from '../framecn/spring-scale-in/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SpringScaleIn} config={springScaleInConfig} />
}
