// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shimmer-sweep".
import { ShimmerSweep } from '../framecn/shimmer-sweep'
import { shimmerSweepConfig } from '../framecn/shimmer-sweep/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShimmerSweep} config={shimmerSweepConfig} />
}
