// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-pulsing-border".
import { ShaderPulsingBorder } from '../framecn/shader-pulsing-border'
import { shaderPulsingBorderConfig } from '../framecn/shader-pulsing-border/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderPulsingBorder} config={shaderPulsingBorderConfig} />
}
