// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-dithering".
import { ShaderDithering } from '../framecn/shader-dithering'
import { shaderDitheringConfig } from '../framecn/shader-dithering/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderDithering} config={shaderDitheringConfig} />
}
