// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "shader-water".
import { ShaderWater } from '../framecn/shader-water'
import { shaderWaterConfig } from '../framecn/shader-water/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ShaderWater} config={shaderWaterConfig} />
}
