// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "spatial-push".
import { SpatialPush } from '../framecn/spatial-push'
import { spatialPushConfig } from '../framecn/spatial-push/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SpatialPush} config={spatialPushConfig} />
}
