// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "swipe-transition-wipe".
import { SwipeTransitionWipe } from '../framecn/swipe-transition-wipe'
import { swipeTransitionWipeConfig } from '../framecn/swipe-transition-wipe/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SwipeTransitionWipe} config={swipeTransitionWipeConfig} />
}
