// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "spotlight-card".
import { SpotlightCard } from '../framecn/spotlight-card'
import { spotlightCardConfig } from '../framecn/spotlight-card/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={SpotlightCard} config={spotlightCardConfig} />
}
