// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "text-fade-replace".
import { TextFadeReplace } from '../framecn/text-fade-replace'
import { textFadeReplaceConfig } from '../framecn/text-fade-replace/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={TextFadeReplace} config={textFadeReplaceConfig} />
}
