// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "terminal-simulator".
import { TerminalSimulator } from '../framecn/terminal-simulator'
import { terminalSimulatorConfig } from '../framecn/terminal-simulator/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={TerminalSimulator} config={terminalSimulatorConfig} />
}
