// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "top-down-letters".
import { TopDownLetters } from '../framecn/top-down-letters'
import { topDownLettersConfig } from '../framecn/top-down-letters/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={TopDownLetters} config={topDownLettersConfig} />
}
