// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "tracking-in".
import { TrackingIn } from '../framecn/tracking-in'
import { trackingInConfig } from '../framecn/tracking-in/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={TrackingIn} config={trackingInConfig} />
}
