// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "terminal-to-browser-deploy".
import { TerminalToBrowserDeploy } from '../framecn/terminal-to-browser-deploy'
import { terminalToBrowserDeployConfig } from '../framecn/terminal-to-browser-deploy/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={TerminalToBrowserDeploy} config={terminalToBrowserDeployConfig} />
}
