// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "toast-notification".
import { ToastNotification } from '../framecn/toast-notification'
import { toastNotificationConfig } from '../framecn/toast-notification/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ToastNotification} config={toastNotificationConfig} />
}
