// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "typewriter".
import { Typewriter } from '../framecn/typewriter'
import { typewriterConfig } from '../framecn/typewriter/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={Typewriter} config={typewriterConfig} />
}
