// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "zoom-through-transition".
import { ZoomThroughTransition } from '../framecn/zoom-through-transition'
import { zoomThroughTransitionConfig } from '../framecn/zoom-through-transition/config'
import { FramecnStage } from '../framecn/stage'

export default function Demo() {
  return <FramecnStage component={ZoomThroughTransition} config={zoomThroughTransitionConfig} />
}
