/* Background engine — deterministic procedural backgrounds on Canvas2D. Every background exposes the same
 * parameter contract: colors, speed, density, scale, noise, intensity, opacity, direction, blur, seed. */
import { fbm3, hash1, mixColor, mulberry32, noise3, parseColor, withAlpha, clamp } from "@/core/math";
import type { Theme } from "@/themes";
import { getCanvas, ctxOf, glowSprite, linearGrad, type Ctx2D } from "@/render/core";

export type BgParams = { colors: string[]; speed: number; density: number; scale: number; noise: number; intensity: number; opacity: number; direction: number; blur: number; seed: number; base: string };
export type BgDef = { id: string; name: string; group: "gradient" | "procedural" | "grid" | "abstract"; tags: string[]; description: string; draw: (ctx: Ctx2D, w: number, h: number, t: number, P: BgParams, theme: Theme, q: number) => void };
export const BACKGROUNDS: Record<string, BgDef> = {};
const B = (id: string, name: string, group: BgDef["group"], tags: string[], description: string, draw: BgDef["draw"]) => { BACKGROUNDS[id] = { id, name, group, tags, description, draw }; };
const c = (P: BgParams, i: number) => P.colors[((i % P.colors.length) + P.colors.length) % P.colors.length] ?? "#7c8cff";
const TAU = Math.PI * 2;

/** Low-resolution scalar field → upscaled smooth image (cheap GPU-free procedural texture). */
function field(ctx: Ctx2D, w: number, h: number, res: number, key: string, fn: (u: number, v: number) => [number, number, number, number]) {
  const rw = Math.max(8, Math.round(res * (w / h))), rh = Math.max(8, Math.round(res));
  const cv = getCanvas(`field_${key}`, rw, rh);
  const g = ctxOf(cv);
  const img = g.createImageData(rw, rh);
  const d = img.data;
  for (let y = 0; y < rh; y++) for (let x = 0; x < rw; x++) {
    const [r, gg, b, a] = fn(x / rw, y / rh);
    const i = (y * rw + x) * 4;
    d[i] = r; d[i + 1] = gg; d[i + 2] = b; d[i + 3] = a;
  }
  g.putImageData(img, 0, 0);
  ctx.save(); ctx.imageSmoothingEnabled = true; ctx.imageSmoothingQuality = "high"; ctx.drawImage(cv, 0, 0, w, h); ctx.restore();
}
function ramp(P: BgParams, v: number): [number, number, number] {
  const cs = P.colors.map(parseColor);
  const x = clamp(v) * (cs.length - 1);
  const i = Math.min(cs.length - 2, Math.floor(x)), f = x - i;
  const a = cs[Math.max(0, i)], b = cs[Math.min(cs.length - 1, i + 1)];
  return [a.r + (b.r - a.r) * f, a.g + (b.g - a.g) * f, a.b + (b.b - a.b) * f];
}
function blob(ctx: Ctx2D, x: number, y: number, r: number, color: string, alpha = 1) {
  const g = ctx.createRadialGradient(x, y, 0, x, y, r);
  g.addColorStop(0, withAlpha(color, alpha)); g.addColorStop(1, withAlpha(color, 0));
  ctx.fillStyle = g; ctx.fillRect(x - r, y - r, r * 2, r * 2);
}

/* ============ GRADIENTS ============ */
B("linear", "Linear Gradient", "gradient", ["gradient", "clean"], "Directional multi-stop gradient.", (ctx, w, h, t, P) => { const a = ((P.direction + t * P.speed * 10) * Math.PI) / 180, r = Math.hypot(w, h) / 2; ctx.fillStyle = linearGrad(ctx, P.colors, w / 2 - Math.cos(a) * r, h / 2 - Math.sin(a) * r, w / 2 + Math.cos(a) * r, h / 2 + Math.sin(a) * r); ctx.fillRect(0, 0, w, h); });
B("radial", "Radial Glow", "gradient", ["glow", "spotlight"], "Centered radial glow over the base.", (ctx, w, h, t, P) => { const r = Math.max(w, h) * 0.7 * P.scale * (1 + Math.sin(t * P.speed) * 0.05); const g = ctx.createRadialGradient(w / 2, h * 0.45, 0, w / 2, h * 0.45, r); P.colors.forEach((col, i) => g.addColorStop(i / Math.max(1, P.colors.length - 1), withAlpha(col, i === P.colors.length - 1 ? 0 : P.intensity))); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); });
B("conic", "Conic Sweep", "gradient", ["holographic", "vibrant"], "Rotating conic gradient.", (ctx, w, h, t, P) => { const g = ctx.createConicGradient(t * P.speed * 0.5 + (P.direction * Math.PI) / 180, w / 2, h / 2); [...P.colors, P.colors[0]].forEach((col, i, arr) => g.addColorStop(i / (arr.length - 1), col)); ctx.fillStyle = g; ctx.globalAlpha *= P.intensity; ctx.fillRect(0, 0, w, h); });
B("mesh", "Mesh Gradient", "gradient", ["saas", "premium", "soft"], "Organic mesh gradient of drifting colour points.", (ctx, w, h, t, P) => { const n = Math.max(3, Math.round(4 * P.density)); for (let i = 0; i < n; i++) { const x = w * (0.5 + 0.42 * Math.sin(t * P.speed * 0.3 + i * 2.1 + P.seed)); const y = h * (0.5 + 0.42 * Math.cos(t * P.speed * 0.25 + i * 1.7 + P.seed)); blob(ctx, x, y, Math.max(w, h) * 0.55 * P.scale, c(P, i), 0.75 * P.intensity); } });
B("aurora", "Aurora", "gradient", ["ai", "premium", "northern-lights"], "Layered aurora curtains.", (ctx, w, h, t, P) => { ctx.save(); ctx.globalCompositeOperation = "lighter"; ctx.filter = `blur(${Math.round(40 * P.scale + P.blur)}px)`; for (let k = 0; k < 4; k++) { ctx.beginPath(); const yb = h * (0.25 + k * 0.12); ctx.moveTo(0, h); for (let x = 0; x <= w; x += w / 24) { const y = yb + Math.sin(x / w * 3 + t * P.speed * 0.6 + k * 1.3) * h * 0.08 * P.intensity + noise3(x / w * 2, k, t * 0.2 * P.speed, P.seed) * h * 0.12 * P.noise * 3; ctx.lineTo(x, y); } ctx.lineTo(w, h); ctx.closePath(); const g = ctx.createLinearGradient(0, yb - h * 0.2, 0, h); g.addColorStop(0, withAlpha(c(P, k), 0)); g.addColorStop(0.2, withAlpha(c(P, k), 0.55)); g.addColorStop(1, withAlpha(c(P, k), 0)); ctx.fillStyle = g; ctx.fill(); } ctx.restore(); });
B("animatedGradient", "Animated Gradient", "gradient", ["animated", "saas"], "Gradient that pans across its colours.", (ctx, w, h, t, P) => { const off = (t * P.speed * 0.1) % 1; const g = ctx.createLinearGradient(-w * off, 0, w * (2 - off), h * 0.3); [...P.colors, ...P.colors].forEach((col, i, arr) => g.addColorStop(i / (arr.length - 1), col)); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); });
B("liquid", "Liquid Blobs", "gradient", ["liquid", "fluid", "blob"], "Gooey liquid colour blobs.", (ctx, w, h, t, P) => { ctx.save(); ctx.filter = `blur(${Math.round(60 * P.scale + P.blur)}px)`; for (let i = 0; i < 6; i++) { const x = w * (0.5 + 0.35 * Math.sin(t * P.speed * 0.5 + i * 1.9)); const y = h * (0.5 + 0.35 * Math.sin(t * P.speed * 0.37 + i * 2.7)); ctx.fillStyle = withAlpha(c(P, i), 0.8 * P.intensity); ctx.beginPath(); ctx.arc(x, y, Math.min(w, h) * (0.18 + 0.06 * Math.sin(t + i)) * P.scale, 0, TAU); ctx.fill(); } ctx.restore(); });
B("holographicBg", "Holographic Foil", "gradient", ["holographic", "iridescent", "futuristic"], "Hue-shifting holographic foil.", (ctx, w, h, t, P, _th, q) => field(ctx, w, h, 40 * q, "holo", (u, v) => { const n = fbm3(u * 3 * P.scale, v * 3 * P.scale, t * 0.2 * P.speed, 3, P.seed); const hue = (u + v + n + t * 0.05 * P.speed) % 1; const [r, g, b] = ramp({ ...P, colors: [...P.colors, P.colors[0]] }, (hue + 1) % 1); return [r, g, b, 255 * P.intensity]; }));
B("iridescent", "Iridescent Film", "gradient", ["iridescent", "luxury"], "Thin-film interference bands.", (ctx, w, h, t, P, _th, q) => field(ctx, w, h, 50 * q, "irid", (u, v) => { const d = Math.sin((u * 6 + v * 4) * P.scale + fbm3(u * 2, v * 2, t * 0.15 * P.speed, 3, P.seed) * 4); const [r, g, b] = ramp(P, d * 0.5 + 0.5); return [r, g, b, 200 * P.intensity]; }));
B("spotlight", "Spotlight", "gradient", ["cinematic", "stage"], "Moving stage spotlight cone.", (ctx, w, h, t, P) => { const x = w * (0.5 + Math.sin(t * P.speed * 0.4) * 0.25); ctx.save(); ctx.globalCompositeOperation = "lighter"; const g = ctx.createRadialGradient(x, -h * 0.1, 0, x, -h * 0.1, h * 1.3 * P.scale); g.addColorStop(0, withAlpha(c(P, 0), 0.6 * P.intensity)); g.addColorStop(1, withAlpha(c(P, 0), 0)); ctx.fillStyle = g; ctx.beginPath(); ctx.moveTo(x - 40, -10); ctx.lineTo(x + 40, -10); ctx.lineTo(x + w * 0.4, h); ctx.lineTo(x - w * 0.4, h); ctx.closePath(); ctx.fill(); ctx.restore(); });
B("horizon", "Horizon Glow", "gradient", ["cinematic", "sunset"], "Glowing horizon line with atmospheric falloff.", (ctx, w, h, t, P) => { const y = h * 0.62; const g = ctx.createLinearGradient(0, 0, 0, h); g.addColorStop(0, P.base); g.addColorStop(0.55, withAlpha(c(P, 0), 0.5 * P.intensity)); g.addColorStop(0.62, withAlpha(c(P, 1), 0.9 * P.intensity)); g.addColorStop(0.64, P.base); g.addColorStop(1, P.base); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); blob(ctx, w / 2, y, w * 0.45 * (1 + Math.sin(t * P.speed) * 0.03), c(P, 1), 0.5 * P.intensity); });
B("duotone", "Duotone Split", "gradient", ["editorial", "bold"], "Two-tone diagonal split with soft seam.", (ctx, w, h, t, P) => { const a = ((P.direction + Math.sin(t * P.speed * 0.3) * 8) * Math.PI) / 180; const g = ctx.createLinearGradient(w / 2 - Math.cos(a) * w, h / 2 - Math.sin(a) * w, w / 2 + Math.cos(a) * w, h / 2 + Math.sin(a) * w); g.addColorStop(0.48, c(P, 0)); g.addColorStop(0.52, c(P, 1)); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); });
/* ============ PROCEDURAL ============ */
B("noise", "Value Noise", "procedural", ["noise", "texture"], "Smooth animated value noise.", (ctx, w, h, t, P, _th, q) => field(ctx, w, h, 36 * q, "noise", (u, v) => { const n = noise3(u * 4 * P.scale, v * 4 * P.scale, t * 0.3 * P.speed, P.seed) * 0.5 + 0.5; const [r, g, b] = ramp(P, n); return [r, g, b, 255 * P.intensity]; }));
B("fractalNoise", "Fractal Noise", "procedural", ["noise", "clouds"], "Multi-octave fractal clouds.", (ctx, w, h, t, P, _th, q) => field(ctx, w, h, 60 * q, "fbm", (u, v) => { const n = fbm3(u * 3 * P.scale, v * 3 * P.scale, t * 0.15 * P.speed, 5, P.seed) * 0.8 + 0.5; const [r, g, b] = ramp(P, n); return [r, g, b, 255 * P.intensity]; }));
B("flowingNoise", "Flowing Noise", "procedural", ["fluid", "organic"], "Domain-warped flowing noise.", (ctx, w, h, t, P, _th, q) => field(ctx, w, h, 48 * q, "warp", (u, v) => { const s = 2.5 * P.scale, z = t * 0.2 * P.speed; const qx = fbm3(u * s, v * s, z, 3, P.seed), qy = fbm3(u * s + 5.2, v * s + 1.3, z, 3, P.seed); const n = fbm3(u * s + qx * 2 * (1 + P.noise), v * s + qy * 2, z, 3, P.seed + 1) * 0.8 + 0.5; const [r, g, b] = ramp(P, n); return [r, g, b, 255 * P.intensity]; }));
B("plasma", "Plasma", "procedural", ["retro", "psychedelic"], "Classic sine plasma.", (ctx, w, h, t, P, _th, q) => field(ctx, w, h, 40 * q, "plasma", (u, v) => { const x = u * 8 * P.scale, y = v * 8 * P.scale, tt = t * P.speed; const n = (Math.sin(x + tt) + Math.sin((y + tt) * 0.8) + Math.sin((x + y + tt) * 0.7) + Math.sin(Math.hypot(x - 4, y - 4) + tt)) / 8 + 0.5; const [r, g, b] = ramp(P, n); return [r, g, b, 255 * P.intensity]; }));
B("metaballs", "Metaballs", "procedural", ["liquid", "blob"], "Iso-surface metaballs.", (ctx, w, h, t, P, _th, q) => { const balls = Array.from({ length: 6 }, (_, i) => [0.5 + 0.35 * Math.sin(t * P.speed * 0.6 + i * 1.7), 0.5 + 0.35 * Math.cos(t * P.speed * 0.5 + i * 2.3), 0.07 + 0.03 * Math.sin(i)]); field(ctx, w, h, 70 * q, "meta", (u, v) => { let s = 0; const ar = w / h; for (const [x, y, r] of balls) s += (r * r) / (((u - x) * ar) ** 2 + (v - y) ** 2 + 1e-4); const k = clamp((s - 0.8) * 2); const [r, g, b] = ramp(P, clamp(s / 3)); return [r, g, b, 255 * k * P.intensity]; }); });
B("voronoi", "Voronoi Cells", "procedural", ["cells", "organic", "tech"], "Animated Voronoi cellular pattern.", (ctx, w, h, t, P, _th, q) => { const rng = mulberry32(P.seed); const pts = Array.from({ length: Math.round(18 * P.density) }, () => [rng(), rng(), rng() * TAU]); field(ctx, w, h, 70 * q, "voro", (u, v) => { let d1 = 9, d2 = 9; const ar = w / h; for (const [x, y, ph] of pts) { const px = x + Math.sin(t * P.speed * 0.4 + ph) * 0.05, py = y + Math.cos(t * P.speed * 0.4 + ph) * 0.05; const d = Math.hypot((u - px) * ar, v - py); if (d < d1) { d2 = d1; d1 = d; } else if (d < d2) d2 = d; } const e = clamp((d2 - d1) * 12); const [r, g, b] = ramp(P, d1 * 3); return [r * e, g * e, b * e, 255 * P.intensity]; }); });
B("topographic", "Topographic", "procedural", ["map", "contour", "minimal"], "Contour lines of a noise terrain.", (ctx, w, h, t, P, _th, q) => field(ctx, w, h, 110 * q, "topo", (u, v) => { const n = fbm3(u * 2.5 * P.scale, v * 2.5 * P.scale, t * 0.05 * P.speed, 3, P.seed) * 10 * P.density; const f = Math.abs((n % 1 + 1) % 1 - 0.5); const k = f < 0.06 ? 1 : 0; const col = parseColor(c(P, 0)); return [col.r, col.g, col.b, 255 * k * P.intensity]; }));
B("waves", "Waves", "procedural", ["waves", "calm"], "Stacked sine wave bands.", (ctx, w, h, t, P) => { const n = Math.round(6 * P.density); for (let k = 0; k < n; k++) { ctx.beginPath(); const yb = h * (0.35 + (k / n) * 0.65); ctx.moveTo(0, h); for (let x = 0; x <= w; x += 16) ctx.lineTo(x, yb + Math.sin(x / (w * 0.18 * P.scale) + t * P.speed * (1 + k * 0.2) + k) * h * 0.04 * P.intensity); ctx.lineTo(w, h); ctx.closePath(); ctx.fillStyle = withAlpha(c(P, k), 0.25 + (k / n) * 0.35); ctx.fill(); } });
B("waveLines", "Wave Lines", "procedural", ["lines", "minimal", "tech"], "Fine animated wave line field.", (ctx, w, h, t, P) => { const n = Math.round(40 * P.density); ctx.lineWidth = 1.2; for (let k = 0; k < n; k++) { ctx.beginPath(); const yb = (k / n) * h * 1.2 - h * 0.1; for (let x = 0; x <= w; x += 12) { const y = yb + Math.sin(x / (w * 0.25 * P.scale) + t * P.speed + k * 0.15) * h * 0.05 * P.intensity + noise3(x / w * 3, k * 0.1, t * 0.2, P.seed) * 30 * P.noise * 4; x ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } ctx.strokeStyle = withAlpha(mixColor(c(P, 0), c(P, 1), k / n), 0.5); ctx.stroke(); } });
B("blobs", "Floating Blobs", "procedural", ["soft", "friendly"], "Soft noise-deformed blobs.", (ctx, w, h, t, P) => { for (let i = 0; i < Math.round(5 * P.density); i++) { const cx = w * hash1(i + P.seed), cy = h * hash1(i * 3 + P.seed); const R = Math.min(w, h) * (0.15 + hash1(i * 7) * 0.15) * P.scale; ctx.beginPath(); for (let k = 0; k <= 48; k++) { const a = (k / 48) * TAU; const r = R * (1 + noise3(Math.cos(a), Math.sin(a), t * P.speed * 0.4 + i, P.seed) * 0.3); const x = cx + Math.cos(a) * r + Math.sin(t * 0.3 + i) * 40, y = cy + Math.sin(a) * r; k ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } ctx.fillStyle = withAlpha(c(P, i), 0.35 * P.intensity); ctx.fill(); } });
B("vectorField", "Vector Field", "procedural", ["tech", "data", "science"], "Noise-driven vector field arrows.", (ctx, w, h, t, P) => { const step = Math.max(18, 44 / P.density); ctx.lineWidth = 1.5; ctx.lineCap = "round"; for (let y = step / 2; y < h; y += step) for (let x = step / 2; x < w; x += step) { const a = noise3(x / w * 3 * P.scale, y / h * 3 * P.scale, t * 0.2 * P.speed, P.seed) * TAU; const len = step * 0.4; ctx.strokeStyle = withAlpha(mixColor(c(P, 0), c(P, 1), (Math.sin(a) + 1) / 2), 0.6 * P.intensity); ctx.beginPath(); ctx.moveTo(x - Math.cos(a) * len, y - Math.sin(a) * len); ctx.lineTo(x + Math.cos(a) * len, y + Math.sin(a) * len); ctx.stroke(); } });
B("fluidField", "Fluid Streamlines", "procedural", ["fluid", "flow", "premium"], "Streamlines traced through a flow field.", (ctx, w, h, t, P) => { const rng = mulberry32(P.seed); const n = Math.round(160 * P.density); ctx.lineWidth = 1.4; for (let i = 0; i < n; i++) { let x = rng() * w, y = rng() * h; ctx.beginPath(); ctx.moveTo(x, y); for (let s = 0; s < 22; s++) { const a = fbm3(x / w * 2 * P.scale, y / h * 2 * P.scale, t * 0.08 * P.speed, 2, P.seed) * TAU * 1.5; x += Math.cos(a) * 9; y += Math.sin(a) * 9; ctx.lineTo(x, y); } ctx.strokeStyle = withAlpha(c(P, i), 0.35 * P.intensity); ctx.stroke(); } });
/* ============ GRIDS ============ */
const gridColor = (P: BgParams, a = 0.18) => withAlpha(c(P, 0), a * P.intensity);
B("perspectiveGrid", "Perspective Grid", "grid", ["synthwave", "retro", "cyber"], "Infinite perspective floor grid.", (ctx, w, h, t, P) => { const hy = h * 0.5; ctx.strokeStyle = gridColor(P, 0.5); ctx.lineWidth = 1.5; const n = Math.round(24 * P.density); for (let i = -n; i <= n; i++) { ctx.beginPath(); ctx.moveTo(w / 2 + i * 8, hy); ctx.lineTo(w / 2 + i * w * 0.12 * P.scale, h); ctx.stroke(); } const off = (t * P.speed * 0.5) % 1; for (let k = 0; k < 16; k++) { const z = (k + 1 - off) / 16; const y = hy + (h - hy) * z * z; ctx.globalAlpha = z; ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); } ctx.globalAlpha = 1; blob(ctx, w / 2, hy, w * 0.5, c(P, 1), 0.35 * P.intensity); });
B("infiniteGrid", "Infinite Grid", "grid", ["saas", "minimal", "tech"], "Scrolling square grid with radial fade.", (ctx, w, h, t, P) => { const s = 64 * P.scale; const a = (P.direction * Math.PI) / 180; const ox = (Math.cos(a) * t * P.speed * 30) % s, oy = (Math.sin(a) * t * P.speed * 30) % s; ctx.strokeStyle = gridColor(P); ctx.lineWidth = 1; ctx.beginPath(); for (let x = ox - s; x < w + s; x += s) { ctx.moveTo(x, 0); ctx.lineTo(x, h); } for (let y = oy - s; y < h + s; y += s) { ctx.moveTo(0, y); ctx.lineTo(w, y); } ctx.stroke(); const g = ctx.createRadialGradient(w / 2, h / 2, 0, w / 2, h / 2, Math.max(w, h) * 0.6); g.addColorStop(0, "rgba(0,0,0,0)"); g.addColorStop(1, P.base); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); });
B("dotGrid", "Dot Grid", "grid", ["minimal", "saas"], "Dot matrix with a travelling pulse.", (ctx, w, h, t, P) => { const s = 32 * P.scale; for (let y = s / 2; y < h; y += s) for (let x = s / 2; x < w; x += s) { const d = Math.hypot(x - w / 2, y - h / 2) / Math.max(w, h); const pulse = Math.max(0, Math.sin(d * 20 - t * P.speed * 3)) ** 8; ctx.fillStyle = withAlpha(mixColor(c(P, 0), c(P, 1), pulse), (0.18 + pulse * 0.8) * P.intensity); ctx.fillRect(x - 1.5, y - 1.5, 3 + pulse * 2, 3 + pulse * 2); } });
B("lineGrid", "Line Grid", "grid", ["blueprint"], "Major/minor blueprint grid.", (ctx, w, h, _t, P) => { const s = 24 * P.scale; ctx.lineWidth = 1; for (let i = 0, x = 0; x < w; x += s, i++) { ctx.strokeStyle = gridColor(P, i % 5 ? 0.08 : 0.25); ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke(); } for (let i = 0, y = 0; y < h; y += s, i++) { ctx.strokeStyle = gridColor(P, i % 5 ? 0.08 : 0.25); ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); } });
B("isometric", "Isometric Grid", "grid", ["3d", "tech"], "Isometric lattice with elevated tiles.", (ctx, w, h, t, P) => { const s = 48 * P.scale; ctx.strokeStyle = gridColor(P, 0.22); ctx.lineWidth = 1; ctx.beginPath(); for (let k = -h; k < w + h; k += s) { ctx.moveTo(k, 0); ctx.lineTo(k + h / Math.tan(Math.PI / 6), h); ctx.moveTo(k, 0); ctx.lineTo(k - h / Math.tan(Math.PI / 6), h); } ctx.stroke(); for (let i = 0; i < 12 * P.density; i++) { const x = hash1(i + P.seed) * w, y = hash1(i * 2 + P.seed) * h; const lift = Math.max(0, Math.sin(t * P.speed + i)) * 20; ctx.fillStyle = withAlpha(c(P, i), 0.25 * P.intensity); ctx.beginPath(); ctx.moveTo(x, y - s / 2 - lift); ctx.lineTo(x + s * 0.866, y - lift); ctx.lineTo(x, y + s / 2 - lift); ctx.lineTo(x - s * 0.866, y - lift); ctx.closePath(); ctx.fill(); } });
B("cyberGrid", "Cyber Grid", "grid", ["cyber", "neon", "hud"], "Neon grid with scanning beam.", (ctx, w, h, t, P) => { const s = 56 * P.scale; ctx.save(); ctx.shadowColor = c(P, 0); ctx.shadowBlur = 8; ctx.strokeStyle = gridColor(P, 0.35); ctx.beginPath(); for (let x = 0; x < w; x += s) { ctx.moveTo(x, 0); ctx.lineTo(x, h); } for (let y = 0; y < h; y += s) { ctx.moveTo(0, y); ctx.lineTo(w, y); } ctx.stroke(); ctx.restore(); const sy = ((t * P.speed * 0.25) % 1) * h; const g = ctx.createLinearGradient(0, sy - 80, 0, sy); g.addColorStop(0, withAlpha(c(P, 1), 0)); g.addColorStop(1, withAlpha(c(P, 1), 0.5 * P.intensity)); ctx.fillStyle = g; ctx.fillRect(0, sy - 80, w, 80); });
B("holoGrid", "Holographic Grid", "grid", ["holographic", "futuristic"], "Shimmering holographic lattice.", (ctx, w, h, t, P) => { const s = 40 * P.scale; for (let x = 0; x < w; x += s) { ctx.strokeStyle = withAlpha(mixColor(c(P, 0), c(P, 1), (Math.sin(x / w * 6 + t * P.speed) + 1) / 2), 0.3 * P.intensity); ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke(); } for (let y = 0; y < h; y += s) { ctx.strokeStyle = withAlpha(mixColor(c(P, 1), c(P, 2), (Math.cos(y / h * 6 + t * P.speed) + 1) / 2), 0.3 * P.intensity); ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(w, y); ctx.stroke(); } });
B("radialGrid", "Radial Grid", "grid", ["radar", "hud"], "Polar grid with radar sweep.", (ctx, w, h, t, P) => { const cx = w / 2, cy = h / 2, R = Math.hypot(w, h) / 2; ctx.strokeStyle = gridColor(P, 0.2); for (let r = 60 * P.scale; r < R; r += 80 * P.scale) { ctx.beginPath(); ctx.arc(cx, cy, r, 0, TAU); ctx.stroke(); } for (let k = 0; k < 24; k++) { const a = (k / 24) * TAU; ctx.beginPath(); ctx.moveTo(cx, cy); ctx.lineTo(cx + Math.cos(a) * R, cy + Math.sin(a) * R); ctx.stroke(); } const a0 = t * P.speed; const g = ctx.createConicGradient(a0, cx, cy); g.addColorStop(0, withAlpha(c(P, 1), 0.45 * P.intensity)); g.addColorStop(0.1, withAlpha(c(P, 1), 0)); g.addColorStop(1, withAlpha(c(P, 1), 0)); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); });
B("dataGrid", "Data Grid", "grid", ["data", "tech", "ai"], "Cells lighting up like live data.", (ctx, w, h, t, P) => { const s = 28 * P.scale; const f = Math.floor(t * 8 * P.speed); for (let y = 0, j = 0; y < h; y += s, j++) for (let x = 0, i = 0; x < w; x += s, i++) { const v = hash1(i * 31.7 + j * 7.3 + Math.floor((f + i * 3 + j) / 6) * 1.37 + P.seed); if (v > 1 - 0.12 * P.density) { ctx.fillStyle = withAlpha(c(P, i + j), (v - 0.85) * 5 * P.intensity); ctx.fillRect(x + 2, y + 2, s - 4, s - 4); } } });
B("hexGrid", "Hex Grid", "grid", ["tech", "honeycomb"], "Honeycomb grid with waves of light.", (ctx, w, h, t, P) => { const r = 28 * P.scale, hh = r * Math.sqrt(3); for (let row = 0, y = 0; y < h + hh; y += hh / 2, row++) for (let x = (row % 2) * r * 1.5; x < w + r * 3; x += r * 3) { const lit = Math.max(0, Math.sin(x / w * 5 + y / h * 3 - t * P.speed * 2)) ** 6; ctx.beginPath(); for (let k = 0; k < 6; k++) { const a = (k / 6) * TAU; ctx.lineTo(x + Math.cos(a) * r * 0.92, y + Math.sin(a) * r * 0.92); } ctx.closePath(); ctx.strokeStyle = gridColor(P, 0.18); ctx.stroke(); if (lit > 0.05) { ctx.fillStyle = withAlpha(c(P, 1), lit * 0.5 * P.intensity); ctx.fill(); } } });
/* ============ ABSTRACT ============ */
B("ribbons", "Silk Ribbons", "abstract", ["premium", "luxury", "flowing"], "Flowing translucent silk ribbons.", (ctx, w, h, t, P) => { ctx.save(); ctx.globalCompositeOperation = "lighter"; for (let k = 0; k < Math.round(5 * P.density); k++) { ctx.beginPath(); for (let i = 0; i <= 60; i++) { const x = (i / 60) * w; const y = h * 0.5 + Math.sin(i / 60 * TAU * P.scale + t * P.speed * 0.7 + k * 0.6) * h * 0.18 * P.intensity + Math.sin(i / 60 * 9 + t * 0.4 + k) * h * 0.03; i ? ctx.lineTo(x, y) : ctx.moveTo(x, y); } ctx.lineWidth = 60 + k * 10; ctx.strokeStyle = withAlpha(c(P, k), 0.08); ctx.stroke(); ctx.lineWidth = 1.5; ctx.strokeStyle = withAlpha(c(P, k), 0.5); ctx.stroke(); } ctx.restore(); });
B("orbs", "Bokeh Orbs", "abstract", ["bokeh", "soft", "cinematic"], "Out-of-focus floating light orbs.", (ctx, w, h, t, P) => { ctx.save(); ctx.globalCompositeOperation = "lighter"; for (let i = 0; i < Math.round(22 * P.density); i++) { const x = (hash1(i + P.seed) * w + t * P.speed * 10 * (hash1(i * 3) + 0.2)) % (w + 200) - 100, y = hash1(i * 5 + P.seed) * h + Math.sin(t * 0.5 + i) * 20; const r = (20 + hash1(i * 7) * 90) * P.scale; ctx.drawImage(glowSprite(c(P, i), 128), x - r, y - r, r * 2, r * 2); } ctx.restore(); });
B("rings", "Pulse Rings", "abstract", ["radar", "ai", "sonar"], "Expanding concentric rings.", (ctx, w, h, t, P) => { const n = Math.round(8 * P.density); const R = Math.hypot(w, h) / 2; for (let k = 0; k < n; k++) { const ph = ((t * P.speed * 0.2 + k / n) % 1); ctx.strokeStyle = withAlpha(c(P, k), (1 - ph) * 0.6 * P.intensity); ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(w / 2, h / 2, ph * R * P.scale, 0, TAU); ctx.stroke(); } });
B("lightRays", "Light Rays", "abstract", ["volumetric", "cinematic", "god-rays"], "Volumetric god rays from above.", (ctx, w, h, t, P) => { ctx.save(); ctx.globalCompositeOperation = "lighter"; const ox = w * 0.5, oy = -h * 0.2; for (let i = 0; i < Math.round(14 * P.density); i++) { const a = Math.PI / 2 + (hash1(i + P.seed) - 0.5) * 1.3 + Math.sin(t * P.speed * 0.2 + i) * 0.05; const spread = 0.02 + hash1(i * 3) * 0.04; const g = ctx.createLinearGradient(ox, oy, ox + Math.cos(a) * h * 1.5, oy + Math.sin(a) * h * 1.5); g.addColorStop(0, withAlpha(c(P, i), 0.35 * P.intensity * (0.5 + 0.5 * Math.sin(t + i)))); g.addColorStop(1, withAlpha(c(P, i), 0)); ctx.fillStyle = g; ctx.beginPath(); ctx.moveTo(ox, oy); ctx.lineTo(ox + Math.cos(a - spread) * h * 2, oy + Math.sin(a - spread) * h * 2); ctx.lineTo(ox + Math.cos(a + spread) * h * 2, oy + Math.sin(a + spread) * h * 2); ctx.closePath(); ctx.fill(); } ctx.restore(); });
B("beams", "Falling Beams", "abstract", ["saas", "tech", "meteor"], "Vertical light beams falling along columns.", (ctx, w, h, t, P) => { const cols = Math.round(14 * P.density); ctx.strokeStyle = gridColor(P, 0.08); for (let i = 0; i < cols; i++) { const x = ((i + 0.5) / cols) * w; ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, h); ctx.stroke(); const sp = 0.3 + hash1(i + P.seed) * 0.5; const y = ((t * P.speed * sp + hash1(i * 9)) % 1.4) * h * 1.2 - h * 0.2; const g = ctx.createLinearGradient(0, y - 180, 0, y); g.addColorStop(0, withAlpha(c(P, i), 0)); g.addColorStop(1, withAlpha(c(P, i), 0.9 * P.intensity)); ctx.fillStyle = g; ctx.fillRect(x - 1, y - 180, 2, 180); } });
B("geometric", "Geometric Drift", "abstract", ["geometric", "minimal", "bauhaus"], "Slowly rotating outlined polygons.", (ctx, w, h, t, P) => { ctx.lineWidth = 1.5; for (let i = 0; i < Math.round(10 * P.density); i++) { const x = hash1(i + P.seed) * w, y = hash1(i * 2 + P.seed) * h, r = (30 + hash1(i * 3) * 120) * P.scale, sides = 3 + (i % 4); ctx.strokeStyle = withAlpha(c(P, i), 0.4 * P.intensity); ctx.beginPath(); for (let k = 0; k <= sides; k++) { const a = (k / sides) * TAU + t * P.speed * 0.2 * (i % 2 ? 1 : -1); ctx.lineTo(x + Math.cos(a) * r, y + Math.sin(a) * r); } ctx.stroke(); } });
B("starfield", "Starfield", "abstract", ["space", "stars", "cosmic"], "Parallax twinkling starfield.", (ctx, w, h, t, P) => { for (let i = 0; i < Math.round(300 * P.density); i++) { const z = hash1(i * 1.3 + P.seed); const x = ((hash1(i + P.seed) * w - t * P.speed * 20 * z) % w + w) % w, y = hash1(i * 7 + P.seed) * h; const tw = 0.5 + 0.5 * Math.sin(t * 3 + i); ctx.fillStyle = withAlpha(i % 7 ? "#ffffff" : c(P, i), (0.3 + z * 0.7) * tw * P.intensity); const s = 0.6 + z * 1.8; ctx.fillRect(x, y, s, s); } });
B("warpSpeed", "Warp Speed", "abstract", ["space", "hyperspace", "energetic"], "Hyperspace star streaks.", (ctx, w, h, t, P) => { ctx.lineCap = "round"; for (let i = 0; i < Math.round(200 * P.density); i++) { const a = hash1(i + P.seed) * TAU; const z = ((hash1(i * 3) + t * P.speed * 0.4) % 1); const r0 = z * z * Math.hypot(w, h) * 0.7, r1 = r0 * (1 + 0.15 * z); ctx.strokeStyle = withAlpha(c(P, i), z * P.intensity); ctx.lineWidth = z * 2.5; ctx.beginPath(); ctx.moveTo(w / 2 + Math.cos(a) * r0, h / 2 + Math.sin(a) * r0); ctx.lineTo(w / 2 + Math.cos(a) * r1, h / 2 + Math.sin(a) * r1); ctx.stroke(); } });
B("matrixRain", "Code Rain", "abstract", ["hacker", "code", "cyber"], "Falling glyph columns.", (ctx, w, h, t, P) => { const s = 18 * P.scale; ctx.font = `${s}px ui-monospace, monospace`; ctx.textAlign = "center"; const cols = Math.floor(w / s); for (let i = 0; i < cols; i++) { const sp = 0.5 + hash1(i + P.seed); const head = ((t * P.speed * sp * 8 + hash1(i * 5) * 40) % (h / s + 20)); for (let k = 0; k < 18; k++) { const row = Math.floor(head) - k; if (row < 0) continue; const ch = String.fromCharCode(0x30a0 + Math.floor(hash1(i * 13 + row * 7 + Math.floor(t * 4)) * 96)); ctx.fillStyle = withAlpha(k === 0 ? "#ffffff" : c(P, 0), (1 - k / 18) * P.intensity); ctx.fillText(ch, i * s + s / 2, row * s); } } });
B("stripes", "Motion Stripes", "abstract", ["bold", "sport"], "Diagonal animated stripes.", (ctx, w, h, t, P) => { const s = 60 * P.scale; ctx.save(); ctx.translate(w / 2, h / 2); ctx.rotate((P.direction * Math.PI) / 180 + Math.PI / 4); const off = (t * P.speed * 40) % (s * 2); for (let x = -w * 1.5 + off; x < w * 1.5; x += s * 2) { ctx.fillStyle = withAlpha(c(P, Math.floor(x / s)), 0.15 * P.intensity); ctx.fillRect(x, -h * 1.5, s, h * 3); } ctx.restore(); });
B("sunburst", "Sunburst", "abstract", ["retro", "celebration"], "Rotating radial sunburst rays.", (ctx, w, h, t, P) => { const n = Math.round(24 * P.density); const R = Math.hypot(w, h); for (let k = 0; k < n; k++) { const a0 = (k / n) * TAU + t * P.speed * 0.1; ctx.fillStyle = withAlpha(c(P, k), k % 2 ? 0.12 * P.intensity : 0.04); ctx.beginPath(); ctx.moveTo(w / 2, h / 2); ctx.arc(w / 2, h / 2, R, a0, a0 + TAU / n); ctx.closePath(); ctx.fill(); } });
B("halftone", "Halftone", "abstract", ["print", "editorial", "pop-art"], "Animated halftone dot gradient.", (ctx, w, h, t, P) => { const s = 18 * P.scale; for (let y = 0; y < h; y += s) for (let x = 0; x < w; x += s) { const v = (Math.sin(x / w * 4 + t * P.speed) + Math.cos(y / h * 3 - t * P.speed * 0.7)) / 4 + 0.5; ctx.fillStyle = withAlpha(mixColor(c(P, 0), c(P, 1), y / h), 0.8 * P.intensity); ctx.beginPath(); ctx.arc(x + s / 2, y + s / 2, v * s * 0.5, 0, TAU); ctx.fill(); } });
B("circuit", "Circuit Traces", "abstract", ["tech", "hardware", "ai"], "PCB traces with travelling pulses.", (ctx, w, h, t, P) => { const rng = mulberry32(P.seed); const n = Math.round(26 * P.density); ctx.lineWidth = 1.5; for (let i = 0; i < n; i++) { let x = Math.round(rng() * w / 40) * 40, y = Math.round(rng() * h / 40) * 40; const pts: [number, number][] = [[x, y]]; for (let k = 0; k < 5; k++) { if (rng() > 0.5) x += (rng() > 0.5 ? 1 : -1) * 80; else y += (rng() > 0.5 ? 1 : -1) * 80; pts.push([x, y]); } ctx.strokeStyle = gridColor(P, 0.25); ctx.beginPath(); pts.forEach(([a, b], j) => (j ? ctx.lineTo(a, b) : ctx.moveTo(a, b))); ctx.stroke(); const ph = (t * P.speed * 0.3 + rng()) % 1; const seg = Math.floor(ph * (pts.length - 1)), f = ph * (pts.length - 1) - seg; const px = pts[seg][0] + (pts[seg + 1][0] - pts[seg][0]) * f, py = pts[seg][1] + (pts[seg + 1][1] - pts[seg][1]) * f; ctx.drawImage(glowSprite(c(P, i), 48), px - 12, py - 12, 24, 24); ctx.fillStyle = c(P, 0); ctx.fillRect(pts[0][0] - 3, pts[0][1] - 3, 6, 6); } });
B("constellation", "Constellation", "abstract", ["network", "ai", "space"], "Drifting nodes connected by proximity.", (ctx, w, h, t, P) => { const n = Math.round(70 * P.density); const pts = Array.from({ length: n }, (_, i) => [((hash1(i + P.seed) * w + Math.sin(t * P.speed * 0.3 + i) * 40) + w) % w, ((hash1(i * 3 + P.seed) * h + Math.cos(t * P.speed * 0.25 + i) * 40) + h) % h]); const md = 160 * P.scale; ctx.lineWidth = 1; for (let i = 0; i < n; i++) for (let j = i + 1; j < n; j++) { const d = Math.hypot(pts[i][0] - pts[j][0], pts[i][1] - pts[j][1]); if (d < md) { ctx.strokeStyle = withAlpha(c(P, i), (1 - d / md) * 0.4 * P.intensity); ctx.beginPath(); ctx.moveTo(pts[i][0], pts[i][1]); ctx.lineTo(pts[j][0], pts[j][1]); ctx.stroke(); } } pts.forEach(([x, y], i) => { ctx.fillStyle = withAlpha(c(P, i), 0.9); ctx.beginPath(); ctx.arc(x, y, 2, 0, TAU); ctx.fill(); }); });
B("meteors", "Meteor Shower", "abstract", ["space", "dramatic"], "Diagonal meteors with tails.", (ctx, w, h, t, P) => { ctx.lineCap = "round"; for (let i = 0; i < Math.round(14 * P.density); i++) { const ph = (t * P.speed * (0.25 + hash1(i) * 0.3) + hash1(i * 7 + P.seed)) % 1; const x = hash1(i * 3 + P.seed) * w * 1.4 - ph * w * 0.6, y = ph * h * 1.3 - h * 0.15; const g = ctx.createLinearGradient(x, y, x + 140, y - 140 * 0.6); g.addColorStop(0, withAlpha("#ffffff", P.intensity)); g.addColorStop(1, withAlpha(c(P, i), 0)); ctx.strokeStyle = g; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x + 140, y - 84); ctx.stroke(); } });
B("gradientGrain", "Grainy Gradient", "abstract", ["editorial", "trendy", "film"], "Soft gradient with film-grain texture.", (ctx, w, h, t, P, _th, q) => { BACKGROUNDS.mesh.draw(ctx, w, h, t, P, _th, q); const fr = Math.floor(t * 24); field(ctx, w, h, 180 * q, "grain", (u, v) => { const n = hash1(u * 1013.1 + v * 7919.7 + fr * 1.37 + P.seed) * 255; return [n, n, n, 28 * P.intensity]; }); });
B("checkerWarp", "Warped Checker", "abstract", ["psychedelic", "op-art"], "Op-art warped checkerboard.", (ctx, w, h, t, P, _th, q) => field(ctx, w, h, 90 * q, "check", (u, v) => { const x = u * 10 * P.scale + Math.sin(v * 6 + t * P.speed) * 0.8, y = v * 10 * P.scale + Math.cos(u * 6 + t * P.speed) * 0.8; const k = (Math.floor(x) + Math.floor(y)) % 2 === 0; const col = parseColor(k ? c(P, 0) : c(P, 1)); return [col.r, col.g, col.b, 180 * P.intensity]; }));
B("lightLeakBg", "Light Leaks", "abstract", ["film", "warm", "cinematic"], "Warm drifting film light leaks.", (ctx, w, h, t, P) => { ctx.save(); ctx.globalCompositeOperation = "lighter"; for (let i = 0; i < 3; i++) blob(ctx, w * (0.2 + 0.6 * ((Math.sin(t * P.speed * 0.2 + i * 2) + 1) / 2)), h * (0.3 + i * 0.2), w * 0.45 * P.scale, c(P, i), 0.35 * P.intensity); ctx.restore(); });
B("concentric", "Concentric Squares", "abstract", ["hypnotic", "minimal"], "Rotating nested squares.", (ctx, w, h, t, P) => { ctx.save(); ctx.translate(w / 2, h / 2); ctx.lineWidth = 1.5; for (let k = 1; k < 18 * P.density; k++) { ctx.rotate(Math.sin(t * P.speed * 0.3) * 0.04); const s = k * 50 * P.scale; ctx.strokeStyle = withAlpha(c(P, k), 0.3 * P.intensity); ctx.strokeRect(-s / 2, -s / 2, s, s); } ctx.restore(); });

export function drawBackground(id: string, ctx: Ctx2D, w: number, h: number, t: number, P: BgParams, theme: Theme, q = 1) {
  const def = BACKGROUNDS[id] ?? BACKGROUNDS.mesh;
  ctx.save();
  ctx.globalAlpha *= P.opacity;
  def.draw(ctx, w, h, t, P, theme, q);
  ctx.restore();
}
export const BG_IDS = () => Object.keys(BACKGROUNDS);
