// Vendor framecn (MIT, github.com/shadcn-labs/framecn) video components into
// src/lab/framecn. Usage: node scripts/vendor-framecn.mjs /path/to/framecn-clone
// - Sources are copied verbatim except import paths.
// - "@editframe/react" (proprietary runtime) is NOT vendored: its two used
//   names (Timegroup, useTimingInfo) are provided by our own editframe-shim.tsx.
// - Each component gets a lab demo wrapper (src/lab/components/fc-*.tsx) so the
//   Components tab, Studio and the single component recorder all use it.
import { readFile, writeFile, mkdir, readdir, rm } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import path from 'node:path'

const src = process.argv[2]
if (!src || !existsSync(path.join(src, 'registry.json'))) { console.error('usage: vendor-framecn.mjs <framecn clone>'); process.exit(1) }
const root = process.cwd()
const compDir = path.join(src, 'registry/bases/editframe/components')
const outDir = path.join(root, 'src/lab/framecn')
const labDir = path.join(root, 'src/lab/components')
const registry = JSON.parse(await readFile(path.join(src, 'registry.json'), 'utf8'))
const byName = new Map(registry.items.map((i) => [i.name, i]))

// docs path → framecn category
const docCat = new Map()
async function walk(dir, cat) {
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) await walk(p, e.name)
    else if (e.name.endsWith('.mdx')) {
      const body = await readFile(p, 'utf8')
      const m = body.match(/<ComponentPreview[^>]*name="([^"]+)"/)
      if (m) docCat.set(m[1], cat)
    }
  }
}
await walk(path.join(src, 'content/docs'), 'docs')
const CAT = { captions: 'captions', typography: 'text', transitions: 'transitions', compositions: 'scenes', 'ui-blocks': 'scenes', environment: 'shaders', shaders: 'shaders', components: 'shaders', primitives: 'motion' }

const rewrite = (code) => code
  .replace(/from "@editframe\/react"/g, 'from "../editframe-shim"')
  .replace(/from "@\/lib\/customizer-config"/g, 'from "../customizer-config"')

for (const f of await readdir(labDir)) if (f.startsWith('fc-')) await rm(path.join(labDir, f))
const entries = []
const dirs = (await readdir(compDir, { withFileTypes: true })).filter((d) => d.isDirectory()).map((d) => d.name).sort()
for (const dir of dirs) {
  const idx = await readFile(path.join(compDir, dir, 'index.tsx'), 'utf8')
  const cfg = await readFile(path.join(compDir, dir, 'config.ts'), 'utf8')
  if (/^import[^\n]*from "(remotion|@\/components[^"]*)"/m.test(idx)) { console.warn(`skip ${dir}: unsupported import`); continue }
  await mkdir(path.join(outDir, dir), { recursive: true })
  const header = `// Vendored from framecn (MIT) — https://github.com/shadcn-labs/framecn/tree/main/registry/bases/editframe/components/${dir}\n// Only import paths changed. See src/lab/framecn/LICENSE.\n`
  await writeFile(path.join(outDir, dir, 'index.tsx'), header + rewrite(idx.replace(/^"use client";\n/, '')))
  await writeFile(path.join(outDir, dir, 'config.ts'), header + rewrite(cfg))
  const comp = cfg.match(/componentName:\s*"([A-Za-z0-9]+)"/)?.[1]
  const cfgName = cfg.match(/export const (\w+Config)\b/)?.[1]
  if (!comp || !cfgName || !new RegExp(`export (const|function) ${comp}\\b`).test(idx)) { console.warn(`skip ${dir}: no component export`); continue }
  const slug = `fc-${dir}`
  await writeFile(path.join(labDir, `${slug}.tsx`), `// Generated by scripts/vendor-framecn.mjs — framecn (MIT) "${dir}".\nimport { ${comp} } from '../framecn/${dir}'\nimport { ${cfgName} } from '../framecn/${dir}/config'\nimport { FramecnStage } from '../framecn/stage'\n\nexport default function Demo() {\n  return <FramecnStage component={${comp}} config={${cfgName}} />\n}\n`)
  const reg = byName.get(dir) ?? {}
  const shortName = dir.replace(/^(caption|shader)-/, '')
  const cat = CAT[docCat.get(dir) ?? docCat.get(shortName) ?? ''] ?? (dir.startsWith('shader-') ? 'shaders' : dir.startsWith('caption-') ? 'captions' : 'motion')
  entries.push({ slug, dir, name: reg.title ?? dir, category: cat, description: reg.description ?? '', configName: cfgName })
}
await writeFile(path.join(outDir, 'entries.json'), JSON.stringify({ source: 'https://www.framecn.dev/docs/components', repo: 'https://github.com/shadcn-labs/framecn', license: 'MIT', vendoredAt: new Date().toISOString().slice(0, 10), count: entries.length, entries }, null, 1) + '\n')
await writeFile(path.join(outDir, 'configs.ts'), `// Generated by scripts/vendor-framecn.mjs — slug → framecn customizer config (defaults + controls).\nimport type { ComponentConfig } from './customizer-config'\n${entries.map((e, i) => `import { ${e.configName} as c${i} } from './${e.dir}/config'`).join('\n')}\n\nexport const FRAMECN_CONFIGS: Record<string, ComponentConfig> = {\n${entries.map((e, i) => `  '${e.slug}': c${i},`).join('\n')}\n}\n`)
await writeFile(path.join(outDir, 'LICENSE'), await readFile(path.join(src, 'LICENSE'), 'utf8'))
// customizer-config (MIT) verbatim
await writeFile(path.join(outDir, 'customizer-config.ts'), '// Vendored from framecn (MIT) lib/customizer-config.ts\n' + await readFile(path.join(src, 'lib/customizer-config.ts'), 'utf8'))
console.log(`vendored ${entries.length} framecn components`)
