/* Template system + Video Story Engine. Templates are pure generators (input → editable VideoDoc).
 * Scene builders are responsive: they compute alternate layouts per aspect ratio (row vs stack), not crops. */
import { createDoc, createNode, createScene, uid } from "@/core/scene-graph";
import { ASPECT_SIZES, type Aspect, type AnimationConfig, type EffectConfig, type Scene, type SceneNode, type StoryType, type VideoDoc } from "@/core/types";
import { getTheme, registerTheme, generateTheme, type Theme } from "@/themes";

export type TemplateInput = {
  aspect?: Aspect; width?: number; height?: number; fps?: number; duration?: number; // seconds
  brand?: { name?: string; primary?: string; logoMark?: string; logoSrc?: string; url?: string };
  headline?: string; subtitle?: string; problem?: string; features?: string[]; stats?: string[]; cta?: string; quote?: string; author?: string; prompt?: string;
  theme?: string; background?: string; transition?: string; typography?: string; music?: number | null; screenshot?: string;
};
export type Layout = { w: number; h: number; cx: number; cy: number; s: number; portrait: boolean; square: boolean; margin: number };
export const layoutFor = (w: number, h: number): Layout => ({ w, h, cx: w / 2, cy: h / 2, s: Math.min(w, h) / 1080, portrait: h / w > 1.1, square: Math.abs(h / w - 1) <= 0.25 && h / w <= 1.1 && h / w >= 0.8, margin: Math.min(w, h) * 0.07 });

export type Style = { theme: string; bg: string; bgKind: "background" | "shader"; transition: string; text: string; sub: string; enter: string; particles?: string; effects: EffectConfig[]; logo: string; material: string; lighting: string; camera: string };
export type BuildCtx = { L: Layout; I: Required<Pick<TemplateInput, "headline" | "subtitle" | "cta">> & TemplateInput; style: Style; theme: Theme; brand: string; dur: number };
type SceneBuilder = (c: BuildCtx) => SceneNode[];

const e = (preset: string, delay = 0, extra: Partial<AnimationConfig> = {}): AnimationConfig => ({ preset, delay, ...extra });
function T(c: BuildCtx, text: string, x: number, y: number, size: number, o: { anim?: string; delay?: number; role?: "display" | "body" | "mono"; color?: string; maxWidth?: number; fill?: string; align?: string; name?: string; start?: number; highlight?: string; weight?: number } = {}) {
  const start = o.start ?? 0;
  return createNode("text", { text, size: size * c.L.s, animation: o.anim ?? (o.role === "body" ? "lineFadeUp" : c.style.text), role: o.role ?? "display", maxWidth: (o.maxWidth ?? (c.L.portrait ? 0.86 : 0.8)) * c.L.w, align: o.align ?? "center", ...(o.color ? { color: o.color } : {}), ...(o.fill ? { fill: o.fill } : {}), ...(o.highlight ? { highlightWords: o.highlight } : {}), ...(o.weight ? { weight: o.weight } : {}) },
    { x, y, name: o.name ?? "headline", timing: { start: start + (o.delay ?? 0), duration: c.dur - start - (o.delay ?? 0) }, exit: { preset: "fade", duration: 8 } });
}
function BG(c: BuildCtx, variant?: string, extra: Record<string, unknown> = {}): SceneNode {
  const v = variant ?? c.style.bg;
  const isShader = c.style.bgKind === "shader" && !variant;
  return createNode(isShader ? "shader" : "background", isShader ? { shader: v, colors: [c.theme.colors.bg, c.theme.colors.primary, c.theme.colors.secondary], speed: 0.6, intensity: 0.9, ...extra } : { variant: v, colors: c.theme.gradient, speed: 0.6, intensity: 0.8, ...extra }, { x: c.L.cx, y: c.L.cy, name: "background", timing: { start: 0, duration: c.dur } });
}
function FX(c: BuildCtx, preset?: string): SceneNode[] {
  const pr = preset ?? c.style.particles;
  return pr ? [createNode("particles", { preset: pr, intensity: 0.7 }, { x: c.L.cx, y: c.L.cy, name: "particles", timing: { start: 0, duration: c.dur } })] : [];
}
const fit = (c: BuildCtx, w: number, h: number, maxW: number, maxH: number) => Math.min(maxW / w, maxH / h);

/* ---------------- Story scene builders ---------------- */
export const SCENE_BUILDERS: Record<string, { type: StoryType; name: string; description: string; frames: number; build: SceneBuilder }> = {
  logo: { type: "logo", name: "Logo Reveal", description: "Brand logo animation.", frames: 75, build: (c) => [BG(c), ...FX(c), createNode("logo", { text: c.brand, style: c.style.logo, size: 150 * c.L.s * (c.L.portrait ? 0.8 : 1), mark: c.I.brand?.logoMark ?? "spark", ...(c.I.brand?.logoSrc ? { mark: "image", src: c.I.brand.logoSrc } : {}) }, { x: c.L.cx, y: c.L.cy, name: "logo", timing: { start: 4, duration: c.dur - 4 }, exit: { preset: "blurIn", duration: 10 } })] },
  hook: { type: "hook", name: "Hook", description: "Big attention-grabbing statement.", frames: 75, build: (c) => [BG(c), ...FX(c), T(c, c.I.headline, c.L.cx, c.L.cy, c.L.portrait ? 120 : 132, { anim: c.style.text, name: "headline" })] },
  title: { type: "title", name: "Title", description: "Headline with supporting subtitle.", frames: 90, build: (c) => [BG(c), ...FX(c), T(c, c.I.headline, c.L.cx, c.L.cy - 70 * c.L.s, c.L.portrait ? 104 : 112, { name: "headline" }), T(c, c.I.subtitle, c.L.cx, c.L.cy + (c.L.portrait ? 130 : 90) * c.L.s, 38, { role: "body", delay: 14, name: "subtitle", maxWidth: 0.62 })] },
  problem: { type: "problem", name: "Problem", description: "Pain point with strike-through emphasis.", frames: 90, build: (c) => [BG(c, "noise", { colors: [c.theme.colors.bg, c.theme.colors.surface2, c.theme.colors.surface], intensity: 0.8 }), T(c, c.I.problem ?? "Your team loses 12 hours a week to busywork.", c.L.cx, c.L.cy - 30 * c.L.s, c.L.portrait ? 88 : 96, { anim: "wordBlurUp", highlight: "12,hours,busywork" }), T(c, "It doesn't have to be this way.", c.L.cx, c.L.cy + 150 * c.L.s, 36, { role: "body", delay: 30, anim: "strike", name: "kicker" })] },
  statement: { type: "statement", name: "Statement", description: "Editorial statement with masked lines.", frames: 80, build: (c) => [BG(c), T(c, c.I.subtitle, c.L.cx, c.L.cy, c.L.portrait ? 84 : 92, { anim: "lineMaskUp", maxWidth: 0.72, name: "statement" })] },
  aiPrompt: { type: "demo", name: "AI Prompt", description: "Prompt being typed into an AI interface.", frames: 110, build: (c) => { const k = fit(c, 720, 520, c.L.w * 0.86, c.L.h * (c.L.portrait ? 0.5 : 0.72)); return [BG(c), ...FX(c, "neural"), createNode("ui", { kind: "aiChat", prompt: c.I.prompt ?? `Create a launch plan for ${c.brand}`, response: c.I.subtitle }, { x: c.L.cx, y: c.L.portrait ? c.L.h * 0.58 : c.L.cy + 30 * c.L.s, transform: { x: c.L.cx, y: c.L.portrait ? c.L.h * 0.58 : c.L.cy + 30 * c.L.s, scale: k }, name: "ai-chat", timing: { start: 0, duration: c.dur }, enter: e("blurScale") }), T(c, "Just ask.", c.L.cx, c.L.portrait ? c.L.h * 0.2 : c.L.h * 0.1, 64, { name: "label" })]; } },
  aiProcessing: { type: "process", name: "AI Processing", description: "Neural visualization while AI thinks.", frames: 80, build: (c) => [BG(c, "radialGrid", { colors: [c.theme.colors.primary, c.theme.colors.secondary] }), createNode("particles", { preset: "energy" }, { x: c.L.cx, y: c.L.cy, name: "energy", timing: { start: 0, duration: c.dur } }), createNode("three", { object: "icosahedron", material: "holographic", lighting: "HOLOGRAPHIC", camera: "PRODUCT", animation: "tumble", w: 700 * c.L.s, h: 700 * c.L.s }, { x: c.L.cx, y: c.L.cy, name: "ai-core", timing: { start: 0, duration: c.dur }, enter: e("zoomIn") }), T(c, "Thinking in real time", c.L.cx, c.L.h * (c.L.portrait ? 0.82 : 0.86), 44, { anim: "scramble", name: "label" })] },
  product: { type: "product", name: "Product", description: "Product in a device/browser with copy (responsive row/stack).", frames: 120, build: (c) => { const land = !c.L.portrait; const dev = createNode("device", { device: land ? "laptop" : "iphone", screen: land ? "dashboard" : "chat", reflection: true, screenGlow: true, ...(c.I.screenshot ? { screen: "image", screenSrc: c.I.screenshot } : {}) }, { name: "device", timing: { start: 0, duration: c.dur }, enter: e("perspectiveIn", 6), loop: { preset: "hover", intensity: 0.6 } }); const k = land ? fit(c, 1200, 760, c.L.w * 0.55, c.L.h * 0.7) : fit(c, 400, 820, c.L.w * 0.6, c.L.h * 0.5); dev.transform = land ? { x: c.L.w * 0.66, y: c.L.cy, scale: k } : { x: c.L.cx, y: c.L.h * 0.64, scale: k }; return [BG(c), ...FX(c), dev, T(c, c.I.headline, land ? c.L.w * 0.25 : c.L.cx, land ? c.L.cy - 50 * c.L.s : c.L.h * 0.16, land ? 76 : 70, { align: land ? "left" : "center", maxWidth: land ? 0.36 : 0.86, name: "headline" }), T(c, c.I.subtitle, land ? c.L.w * 0.25 : c.L.cx, land ? c.L.cy + 80 * c.L.s : c.L.h * 0.27, 30, { role: "body", align: land ? "left" : "center", maxWidth: land ? 0.36 : 0.8, delay: 14, name: "subtitle" })]; } },
  dashboard: { type: "demo", name: "Dashboard Demo", description: "Full animated SaaS dashboard in a browser.", frames: 120, build: (c) => { const k = fit(c, 1280, 800, c.L.w * 0.9, c.L.h * (c.L.portrait ? 0.45 : 0.78)); return [BG(c), createNode("ui", { kind: "browser", brand: c.brand, url: c.I.brand?.url ?? `app.${c.brand.toLowerCase().replace(/\s+/g, "")}.com` }, { transform: { x: c.L.cx, y: c.L.portrait ? c.L.h * 0.6 : c.L.cy + 30 * c.L.s, scale: k, rotateX: 0 }, name: "dashboard", timing: { start: 0, duration: c.dur }, enter: e("flipUp3D", 0, { duration: 34 }) }), ...(c.L.portrait ? [T(c, "Everything in one place", c.L.cx, c.L.h * 0.2, 72, { name: "label" })] : [])]; } },
  features: { type: "feature", name: "Features", description: "Feature cards with staggered entrance (grid adapts).", frames: 120, build: (c) => { const f = (c.I.features?.length ? c.I.features : ["Real-time automation", "AI insights", "Enterprise security"]).slice(0, c.L.portrait ? 3 : 3); const icons = ["⚡", "✦", "◆", "●"]; const nodes: SceneNode[] = [BG(c), T(c, "Built for speed", c.L.cx, c.L.portrait ? c.L.h * 0.14 : c.L.h * 0.16, c.L.portrait ? 72 : 80, { name: "headline" })]; const k = fit(c, 400, 260, c.L.portrait ? c.L.w * 0.8 : c.L.w * 0.28, c.L.portrait ? c.L.h * 0.2 : c.L.h * 0.45); f.forEach((ft, i) => { const x = c.L.portrait ? c.L.cx : c.L.w * (0.2 + i * 0.3); const y = c.L.portrait ? c.L.h * (0.36 + i * 0.22) : c.L.cy + 60 * c.L.s; nodes.push(createNode("ui", { kind: "featureCard", title: ft, body: ["Trigger workflows from any event.", "Answers from your data, instantly.", "SOC 2, SSO and audit logs built in."][i] ?? "", icon: icons[i] }, { transform: { x, y, scale: k }, name: `feature-${i + 1}`, timing: { start: 10 + i * 8, duration: c.dur - 10 - i * 8 }, enter: e(c.style.enter), exit: { preset: "fade", duration: 8 } })); }); return nodes; } },
  metrics: { type: "statistic", name: "Metrics", description: "KPI counters and a growth chart.", frames: 110, build: (c) => { const stats = (c.I.stats?.length ? c.I.stats : ["10x|faster workflows", "98%|customer retention", "2.4M|tasks automated"]).slice(0, 3); const nodes: SceneNode[] = [BG(c)]; stats.forEach((s, i) => { const [v, l] = s.split("|"); const x = c.L.portrait ? c.L.cx : c.L.w * (0.2 + i * 0.3); const y = c.L.portrait ? c.L.h * (0.22 + i * 0.2) : c.L.h * 0.38; nodes.push(T(c, v, x, y, c.L.portrait ? 120 : 130, { anim: "counter", fill: "gradient", name: `stat-${i + 1}`, start: i * 8, maxWidth: 0.3 })); nodes.push(T(c, l ?? "", x, y + 100 * c.L.s, 30, { role: "body", start: 10 + i * 8, maxWidth: c.L.portrait ? 0.8 : 0.26, name: `stat-label-${i + 1}` })); }); const k = fit(c, 700, 300, c.L.w * (c.L.portrait ? 0.85 : 0.7), c.L.h * 0.28); nodes.push(createNode("chart", { kind: "area", data: [12, 18, 16, 26, 24, 38, 36, 52, 60, 74], w: 700, h: 300, animDelay: 20 }, { transform: { x: c.L.cx, y: c.L.portrait ? c.L.h * 0.84 : c.L.h * 0.76, scale: k }, name: "chart", timing: { start: 16, duration: c.dur - 16 }, enter: e("fadeUp") })); return nodes; } },
  statistic: { type: "statistic", name: "Big Statistic", description: "One huge counting number.", frames: 80, build: (c) => { const [v, l] = (c.I.stats?.[0] ?? "10x|faster than before").split("|"); return [BG(c), T(c, v, c.L.cx, c.L.cy - 40 * c.L.s, 280, { anim: "counter", fill: "gradient", name: "number" }), T(c, l ?? "", c.L.cx, c.L.cy + 150 * c.L.s, 44, { role: "body", delay: 20, name: "label" })]; } },
  comparison: { type: "comparison", name: "Comparison", description: "Before/after comparison bars.", frames: 100, build: (c) => { const k = fit(c, 700, 420, c.L.w * 0.8, c.L.h * 0.5); return [BG(c), T(c, `Before vs. ${c.brand}`, c.L.cx, c.L.h * 0.16, 76, { name: "headline" }), createNode("chart", { kind: "comparison", data: [18, 94], labels: ["Before", `With ${c.brand}`], suffix: "%", w: 700, h: 420, animDelay: 12 }, { transform: { x: c.L.cx, y: c.L.h * 0.58, scale: k }, name: "chart", timing: { start: 8, duration: c.dur - 8 }, enter: e("fadeUp") })]; } },
  testimonial: { type: "testimonial", name: "Testimonial", description: "Customer quote with stars.", frames: 110, build: (c) => { const k = fit(c, 560, 280, c.L.w * 0.86, c.L.h * 0.4); return [BG(c), createNode("ui", { kind: "testimonialCard", quote: c.I.quote ?? `“${c.brand} changed how our team works. We shipped in days, not months.”`, author: c.I.author ?? "Maya Chen · Head of Growth, Northwind" }, { transform: { x: c.L.cx, y: c.L.cy, scale: k }, name: "testimonial", timing: { start: 0, duration: c.dur }, enter: e("blurScale") }), createNode("ui", { kind: "avatar", label: "+2.4k teams" }, { transform: { x: c.L.cx, y: c.L.cy + (280 * k) / 2 + 80 * c.L.s, scale: c.L.s * 1.2 }, name: "avatars", timing: { start: 20, duration: c.dur - 20 } })]; } },
  process: { type: "process", name: "Process", description: "Workflow graph of steps.", frames: 110, build: (c) => { const k = fit(c, 900, 360, c.L.w * 0.92, c.L.h * 0.5); return [BG(c), T(c, "How it works", c.L.cx, c.L.h * 0.18, 76, { name: "headline" }), createNode("ui", { kind: "workflow", steps: (c.I.features?.length ? c.I.features : ["Connect data", "AI analyzes", "Automate", "Ship"]).slice(0, c.L.portrait ? 3 : 4) }, { transform: { x: c.L.cx, y: c.L.cy + 40 * c.L.s, scale: k }, name: "workflow", timing: { start: 6, duration: c.dur - 6 } })]; } },
  automation: { type: "demo", name: "Automation", description: "Agent run checklist completing.", frames: 110, build: (c) => { const land = !c.L.portrait; const k = fit(c, 520, 420, c.L.w * (land ? 0.4 : 0.85), c.L.h * (land ? 0.7 : 0.45)); return [BG(c), createNode("ui", { kind: "automation", title: `${c.brand} agent · weekly report` }, { transform: { x: land ? c.L.w * 0.68 : c.L.cx, y: land ? c.L.cy : c.L.h * 0.62, scale: k }, name: "automation", timing: { start: 0, duration: c.dur }, enter: e("springUp") }), T(c, "Automations that run themselves", land ? c.L.w * 0.27 : c.L.cx, land ? c.L.cy : c.L.h * 0.2, 72, { align: land ? "left" : "center", maxWidth: land ? 0.38 : 0.86, name: "headline" })]; } },
  phone: { type: "product", name: "App Showcase", description: "Phone mockup with floating notification.", frames: 110, build: (c) => { const k = fit(c, 400, 820, c.L.w * 0.5, c.L.h * (c.L.portrait ? 0.62 : 0.8)); const land = !c.L.portrait; return [BG(c), ...FX(c), createNode("device", { device: "iphone", screen: "chat", reflection: true }, { transform: { x: land ? c.L.w * 0.65 : c.L.cx, y: land ? c.L.cy : c.L.h * 0.6, scale: k }, name: "phone", timing: { start: 0, duration: c.dur }, enter: e("slideUp"), loop: { preset: "levitate" } }), createNode("ui", { kind: "notification", title: `${c.brand}`, body: c.I.subtitle }, { transform: { x: land ? c.L.w * 0.65 : c.L.cx, y: land ? c.L.h * 0.2 : c.L.h * 0.3, scale: c.L.s * 1.1 }, name: "notification", timing: { start: 30, duration: c.dur - 30 }, enter: e("springUp") }), T(c, c.I.headline, land ? c.L.w * 0.27 : c.L.cx, land ? c.L.cy : c.L.h * 0.12, 72, { align: land ? "left" : "center", maxWidth: land ? 0.38 : 0.86, name: "headline" })]; } },
  product3d: { type: "product", name: "3D Product", description: "Glass 3D hero object with copy.", frames: 110, build: (c) => { const land = !c.L.portrait; const size = Math.min(c.L.w * (land ? 0.5 : 0.9), c.L.h * (land ? 0.9 : 0.55)); return [BG(c), ...FX(c, "dust"), createNode("three", { object: "torusKnot", material: c.style.material, lighting: c.style.lighting, camera: c.style.camera, animation: "heroFloat", color: c.theme.colors.primary, w: size, h: size }, { x: land ? c.L.w * 0.66 : c.L.cx, y: land ? c.L.cy : c.L.h * 0.6, name: "product-3d", timing: { start: 0, duration: c.dur }, enter: e("blurScale") }), T(c, c.I.headline, land ? c.L.w * 0.27 : c.L.cx, land ? c.L.cy - 40 * c.L.s : c.L.h * 0.16, land ? 80 : 72, { align: land ? "left" : "center", maxWidth: land ? 0.4 : 0.86, name: "headline" }), T(c, c.I.subtitle, land ? c.L.w * 0.27 : c.L.cx, land ? c.L.cy + 90 * c.L.s : c.L.h * 0.26, 30, { role: "body", align: land ? "left" : "center", maxWidth: land ? 0.38 : 0.8, delay: 12, name: "subtitle" })]; } },
  result: { type: "result", name: "Result", description: "Outcome with progress ring.", frames: 90, build: (c) => { const k = fit(c, 360, 360, c.L.w * 0.5, c.L.h * 0.4); return [BG(c), createNode("chart", { kind: "progressRing", value: 94, w: 360, h: 360 }, { transform: { x: c.L.cx, y: c.L.cy - 40 * c.L.s, scale: k }, name: "ring", timing: { start: 0, duration: c.dur }, enter: e("pop") }), T(c, "Goals hit, every sprint.", c.L.cx, c.L.cy + (360 * k) / 2 + 40 * c.L.s, 56, { name: "headline", delay: 16 })]; } },
  cta: { type: "cta", name: "Call to Action", description: "Brand + CTA button + URL.", frames: 90, build: (c) => [BG(c), ...FX(c), T(c, c.I.cta, c.L.cx, c.L.cy - 90 * c.L.s, c.L.portrait ? 96 : 104, { name: "headline" }), createNode("ui", { kind: "button", label: `${c.I.cta.split(" ").slice(0, 3).join(" ")} →` }, { transform: { x: c.L.cx, y: c.L.cy + 60 * c.L.s, scale: c.L.s * 1.4 }, name: "button", timing: { start: 16, duration: c.dur - 16 }, enter: e("pop") }), T(c, c.I.brand?.url ?? `${c.brand.toLowerCase().replace(/\s+/g, "")}.com`, c.L.cx, c.L.cy + 170 * c.L.s, 32, { role: "body", delay: 26, name: "url" })] },
  outro: { type: "outro", name: "Outro", description: "Logo end card with tagline.", frames: 70, build: (c) => [BG(c), createNode("logo", { text: c.brand, style: "fade", size: 120 * c.L.s, tagline: c.I.subtitle.split(".")[0], mark: c.I.brand?.logoMark ?? "spark" }, { x: c.L.cx, y: c.L.cy, name: "logo", timing: { start: 0, duration: c.dur } })] },
  kinetic: { type: "statement", name: "Kinetic Words", description: "Rapid kinetic typography sequence.", frames: 90, build: (c) => { const words = c.I.headline.split(" "); const per = Math.max(8, Math.floor(c.dur / Math.max(1, words.length))); return [BG(c), ...words.map((wd, i) => createNode("text", { text: wd, size: (c.L.portrait ? 180 : 220) * c.L.s, animation: i % 2 ? "charPop" : "wordStomp", fill: i === words.length - 1 ? "gradient" : "solid" }, { x: c.L.cx, y: c.L.cy, name: `word-${i + 1}`, timing: { start: i * per, duration: i === words.length - 1 ? c.dur - i * per : per } }))]; } },
  pricing: { type: "cta", name: "Pricing", description: "Pricing card spotlight.", frames: 100, build: (c) => { const k = fit(c, 380, 520, c.L.w * 0.7, c.L.h * 0.62); return [BG(c), createNode("ui", { kind: "pricingCard", tier: "Pro", price: 49, cta: c.I.cta }, { transform: { x: c.L.cx, y: c.L.cy + 30 * c.L.s, scale: k }, name: "pricing", timing: { start: 0, duration: c.dur }, enter: e("springUp") }), T(c, "Simple pricing", c.L.cx, c.L.h * 0.1, 60, { name: "headline" })]; } },
  code: { type: "demo", name: "Developer Code", description: "Code editor typing an API call.", frames: 120, build: (c) => { const k = fit(c, 760, 460, c.L.w * 0.9, c.L.h * 0.6); return [BG(c, "dotGrid", { colors: [c.theme.colors.primary, c.theme.colors.secondary] }), createNode("ui", { kind: "codeEditor" }, { transform: { x: c.L.cx, y: c.L.cy + 40 * c.L.s, scale: k }, name: "code", timing: { start: 0, duration: c.dur }, enter: e("blurUp") }), T(c, "Ship it in 10 lines", c.L.cx, c.L.h * 0.12, 60, { name: "headline" })]; } },
  youtubeIntro: { type: "hook", name: "YouTube Intro", description: "Fast channel intro with flash and burst logo.", frames: 70, build: (c) => [BG(c, "warpSpeed", { speed: 1.5 }), createNode("logo", { text: c.brand, style: "burst", size: 150 * c.L.s }, { x: c.L.cx, y: c.L.cy, name: "logo", timing: { start: 0, duration: c.dur } }), T(c, c.I.subtitle.split(".")[0], c.L.cx, c.L.cy + 170 * c.L.s, 40, { role: "body", delay: 24, anim: "wordPop", name: "tagline" })] },
};

/* ---------------- Styles ---------------- */
export const STYLES: Record<string, Style> = {
  futuristic: { theme: "aurora", bg: "auroraShader", bgKind: "shader", transition: "lightSweep", text: "wordBlurUp", sub: "lineFadeUp", enter: "blurUp", particles: "dust", effects: [{ type: "bloom", params: { intensity: 0.35 } }, { type: "grain", params: { amount: 0.04 } }, { type: "vignette", params: { amount: 0.4 } }], logo: "particle", material: "glass", lighting: "FUTURISTIC", camera: "HERO" },
  saas: { theme: "midnight", bg: "mesh", bgKind: "background", transition: "slideUp", text: "wordBlurUp", sub: "lineFadeUp", enter: "saas", effects: [{ type: "vignette", params: { amount: 0.35 } }, { type: "grain", params: { amount: 0.03 } }], logo: "minimal", material: "glass", lighting: "STUDIO", camera: "PRODUCT" },
  cinematic: { theme: "cinema", bg: "lightRays", bgKind: "background", transition: "lensFlareCut", text: "wordCinematic", sub: "lineBlur", enter: "cinematic", particles: "embers", effects: [{ type: "letterbox", params: { ratio: 2.39 } }, { type: "tealOrange", params: { amount: 0.2 } }, { type: "grain", params: { amount: 0.08 } }, { type: "vignette", params: { amount: 0.6 } }], logo: "blurFocus", material: "chrome", lighting: "CINEMATIC", camera: "CINEMATIC" },
  luxury: { theme: "luxury", bg: "silk", bgKind: "shader", transition: "lumaFade", text: "goldLuxury", sub: "lineBlur", enter: "luxury", particles: "sparkleBurst", effects: [{ type: "grain", params: { amount: 0.05 } }, { type: "vignette", params: { amount: 0.55 } }], logo: "luxury", material: "gold", lighting: "DARK_LUXURY", camera: "LUXURY" },
  minimal: { theme: "light", bg: "infiniteGrid", bgKind: "background", transition: "crossfade", text: "wordFadeUp", sub: "lineFadeUp", enter: "minimal", effects: [], logo: "fade", material: "ceramic", lighting: "SOFTBOX", camera: "PRODUCT" },
  editorial: { theme: "editorial", bg: "gradientGrain", bgKind: "background", transition: "wipeUp", text: "lineEditorial", sub: "lineMaskUp", enter: "editorial", effects: [{ type: "grain", params: { amount: 0.05 } }], logo: "split", material: "matte", lighting: "SOFTBOX", camera: "PRODUCT" },
  cyber: { theme: "cyber", bg: "cyberGrid", bgKind: "background", transition: "glitch", text: "charGlitch", sub: "scramble", enter: "glitchIn", particles: "data", effects: [{ type: "scanlines", params: { amount: 0.12 } }, { type: "chromatic", params: { amount: 2 } }, { type: "bloom", params: { intensity: 0.4 } }], logo: "glitch", material: "holographic", lighting: "NEON", camera: "TECH" },
  corporate: { theme: "corporate", bg: "waves", bgKind: "background", transition: "pushLeft", text: "wordFadeUp", sub: "lineFadeUp", enter: "corporate", effects: [], logo: "minimal", material: "plastic", lighting: "PRODUCT", camera: "SAAS" },
  social: { theme: "pastel", bg: "liquid", bgKind: "background", transition: "whip", text: "wordStomp", sub: "wordPop", enter: "social", particles: "confetti", effects: [], logo: "stamp", material: "glossy", lighting: "STUDIO", camera: "PRODUCT" },
  neon: { theme: "neon", bg: "perspectiveGrid", bgKind: "background", transition: "flash", text: "neonGlow", sub: "wordPop", enter: "flicker", particles: "sparks", effects: [{ type: "bloom", params: { intensity: 0.6 } }, { type: "vignette" }], logo: "neon", material: "emissive", lighting: "NEON", camera: "ORBIT" },
  finance: { theme: "finance", bg: "dataGrid", bgKind: "background", transition: "softWipe", text: "wordFadeUp", sub: "lineFadeUp", enter: "fadeUp", effects: [{ type: "vignette", params: { amount: 0.4 } }], logo: "minimal", material: "metal", lighting: "PRODUCT", camera: "SAAS" },
  gaming: { theme: "cyber", bg: "tunnel", bgKind: "shader", transition: "zoomIn", text: "charZoom", sub: "wordPop", enter: "zoomBlur", particles: "explosion", effects: [{ type: "chromatic", params: { amount: 3 } }, { type: "cameraShake", params: { amount: 3 } }], logo: "zoomThrough", material: "chrome", lighting: "HOLOGRAPHIC", camera: "DRAMATIC" },
};

/* ---------------- Templates ---------------- */
export type TemplateDef = { id: string; name: string; category: string; tags: string[]; description: string; style: string; scenes: string[]; aspect: Aspect; duration: number; defaults: Partial<TemplateInput>; music?: number };
export const TEMPLATES: Record<string, TemplateDef> = {};
const TP = (d: TemplateDef) => { TEMPLATES[d.id] = d; };
const SAAS_D = { headline: "Work that runs itself.", subtitle: "Automate busywork with AI agents your whole team can trust.", cta: "Start your free trial", features: ["Real-time automation", "AI insights", "Enterprise security"] };
TP({ id: "productLaunch", name: "Product Launch", category: "SaaS", tags: ["saas", "launch", "product"], description: "Logo → Hook → Product → Features → UI → Metrics → CTA.", style: "saas", scenes: ["logo", "hook", "product", "features", "dashboard", "metrics", "cta"], aspect: "16:9", duration: 30, defaults: SAAS_D, music: 112 });
TP({ id: "aiLaunch", name: "AI Launch", category: "AI", tags: ["ai", "launch", "futuristic"], description: "Prompt → AI processing → result → dashboard → automation → CTA.", style: "futuristic", scenes: ["aiPrompt", "aiProcessing", "product", "dashboard", "automation", "cta"], aspect: "16:9", duration: 28, defaults: { ...SAAS_D, headline: "Meet your AI teammate.", prompt: "Summarize this week's revenue and flag risks" }, music: 118 });
TP({ id: "startupStory", name: "Startup Story", category: "Startup", tags: ["startup", "pitch", "story"], description: "Problem → insight → solution → product → differentiation → CTA.", style: "editorial", scenes: ["problem", "statement", "title", "product", "comparison", "cta"], aspect: "16:9", duration: 28, defaults: { ...SAAS_D, subtitle: "We rebuilt the workflow from first principles." } });
TP({ id: "appPromo", name: "App Promo", category: "App", tags: ["app", "mobile", "social"], description: "Phone → UI → features → social proof → CTA.", style: "social", scenes: ["phone", "features", "testimonial", "cta"], aspect: "9:16", duration: 20, defaults: { ...SAAS_D, headline: "Your money, finally organised.", cta: "Download free" }, music: 124 });
TP({ id: "futuristicAd", name: "Futuristic AI SaaS Ad", category: "AI", tags: ["ai", "saas", "premium", "futuristic"], description: "7-scene premium AI advertisement: hook, problem, AI viz, product UI, features, metrics, CTA.", style: "futuristic", scenes: ["hook", "problem", "aiProcessing", "dashboard", "features", "metrics", "cta"], aspect: "16:9", duration: 25, defaults: { ...SAAS_D, headline: "Intelligence, on autopilot." }, music: 120 });
TP({ id: "logoRevealCinematic", name: "Cinematic Logo Reveal", category: "Cinematic", tags: ["logo", "cinematic", "intro"], description: "Cinematic logo reveal with light rays and letterbox.", style: "cinematic", scenes: ["logo"], aspect: "16:9", duration: 5, defaults: {} });
TP({ id: "youtubeIntro", name: "YouTube Intro", category: "YouTube", tags: ["youtube", "intro", "fast"], description: "Punchy 4-second channel intro.", style: "gaming", scenes: ["youtubeIntro"], aspect: "16:9", duration: 4, defaults: { subtitle: "New videos every Tuesday." }, music: 128 });
TP({ id: "shortsHook", name: "Shorts Hook", category: "Shorts", tags: ["shorts", "vertical", "social", "kinetic"], description: "Vertical kinetic hook → stat → CTA for Shorts/Reels/TikTok.", style: "social", scenes: ["kinetic", "statistic", "cta"], aspect: "9:16", duration: 12, defaults: { headline: "Stop doing this manually", stats: ["12h|saved every week"], cta: "Follow for more" }, music: 128 });
TP({ id: "reelsProduct", name: "Reels Product", category: "Reels", tags: ["reels", "vertical", "product"], description: "Vertical product reveal with 3D hero.", style: "neon", scenes: ["hook", "product3d", "features", "cta"], aspect: "9:16", duration: 16, defaults: SAAS_D, music: 122 });
TP({ id: "tiktokExplainer", name: "TikTok Explainer", category: "TikTok", tags: ["tiktok", "vertical", "explainer"], description: "Problem → process → result, vertical.", style: "social", scenes: ["problem", "process", "result", "cta"], aspect: "9:16", duration: 18, defaults: SAAS_D });
TP({ id: "explainer", name: "Explainer", category: "Explainer", tags: ["explainer", "education", "process"], description: "Title → problem → process → result → CTA.", style: "corporate", scenes: ["title", "problem", "process", "result", "cta"], aspect: "16:9", duration: 26, defaults: SAAS_D });
TP({ id: "education", name: "Course Trailer", category: "Education", tags: ["education", "course", "learning"], description: "Hook → what you'll learn → stats → testimonial → CTA.", style: "minimal", scenes: ["hook", "features", "statistic", "testimonial", "cta"], aspect: "16:9", duration: 24, defaults: { headline: "Learn motion design in 30 days.", features: ["Kinetic typography", "3D product shots", "Cinematic edits"], cta: "Enroll today", stats: ["40k|students"] } });
TP({ id: "financeReport", name: "Finance Report", category: "Finance", tags: ["finance", "data", "report"], description: "Metrics, comparison and results for investor updates.", style: "finance", scenes: ["title", "metrics", "comparison", "result", "outro"], aspect: "16:9", duration: 24, defaults: { headline: "Q3 Investor Update", subtitle: "Record growth across every segment.", stats: ["$4.2M|ARR", "212%|net revenue retention", "18mo|runway"] } });
TP({ id: "techKeynote", name: "Tech Keynote", category: "Technology", tags: ["tech", "keynote", "3d"], description: "Keynote-style 3D product reveal.", style: "cinematic", scenes: ["hook", "product3d", "features", "statistic", "outro"], aspect: "16:9", duration: 24, defaults: { ...SAAS_D, headline: "Introducing Nova." } });
TP({ id: "cyberSecurity", name: "Cyber Security", category: "Cyber", tags: ["cyber", "security", "hacker"], description: "Threat → detection → dashboard → CTA with glitch language.", style: "cyber", scenes: ["problem", "aiProcessing", "dashboard", "cta"], aspect: "16:9", duration: 20, defaults: { ...SAAS_D, problem: "1 in 3 breaches start with a single click.", headline: "Threats neutralised in milliseconds." } });
TP({ id: "luxuryBrand", name: "Luxury Brand Film", category: "Luxury", tags: ["luxury", "gold", "premium"], description: "Slow gold typography, 3D gold object and logo.", style: "luxury", scenes: ["statement", "product3d", "logo"], aspect: "16:9", duration: 18, defaults: { headline: "Crafted without compromise.", subtitle: "Time, reimagined." } });
TP({ id: "minimalLaunch", name: "Minimal Launch", category: "Minimal", tags: ["minimal", "clean", "launch"], description: "Understated launch with clean grid and typography.", style: "minimal", scenes: ["title", "product", "features", "cta"], aspect: "16:9", duration: 20, defaults: SAAS_D });
TP({ id: "editorialStory", name: "Editorial Story", category: "Editorial", tags: ["editorial", "magazine", "story"], description: "Magazine-style statements with masked lines.", style: "editorial", scenes: ["statement", "problem", "title", "testimonial", "outro"], aspect: "4:5", duration: 22, defaults: { ...SAAS_D, subtitle: "Good design is honest." } });
TP({ id: "gamingTrailer", name: "Gaming Trailer", category: "Gaming", tags: ["gaming", "energetic", "trailer"], description: "High-energy tunnel, zoom cuts and burst logo.", style: "gaming", scenes: ["kinetic", "product3d", "statistic", "youtubeIntro"], aspect: "16:9", duration: 16, defaults: { headline: "Enter the arena", stats: ["1M|players online"], subtitle: "Season 4 out now." }, music: 140 });
TP({ id: "dataStory", name: "Data Story", category: "Data", tags: ["data", "charts", "analytics"], description: "Data-driven narrative with charts and counters.", style: "finance", scenes: ["title", "metrics", "comparison", "statistic", "cta"], aspect: "16:9", duration: 24, defaults: { headline: "The state of remote work", stats: ["68%|work hybrid", "3.1x|productivity", "42%|less churn"] } });
TP({ id: "cinematicTrailer", name: "Cinematic Trailer", category: "Cinematic", tags: ["cinematic", "trailer", "film"], description: "Letterboxed trailer: hook, statement, product, logo.", style: "cinematic", scenes: ["hook", "statement", "product3d", "logo"], aspect: "16:9", duration: 22, defaults: { headline: "Some ideas change everything.", subtitle: "This is one of them." } });
TP({ id: "corporatePresentation", name: "Corporate Presentation", category: "Corporate", tags: ["corporate", "presentation", "business"], description: "Title, process, metrics, testimonial, outro.", style: "corporate", scenes: ["title", "process", "metrics", "testimonial", "outro"], aspect: "16:9", duration: 28, defaults: { headline: "Building the future of logistics", subtitle: "Annual company overview 2026", features: ["Plan", "Optimise", "Deliver", "Measure"] } });
TP({ id: "saasSquare", name: "SaaS Feed Ad (1:1)", category: "SaaS", tags: ["saas", "social", "square", "ad"], description: "Square feed ad for LinkedIn/Instagram.", style: "saas", scenes: ["hook", "dashboard", "metrics", "cta"], aspect: "1:1", duration: 15, defaults: SAAS_D });
TP({ id: "saasVertical", name: "SaaS Story Ad (9:16)", category: "SaaS", tags: ["saas", "vertical", "stories", "ad"], description: "Vertical story ad for SaaS.", style: "futuristic", scenes: ["hook", "product", "features", "cta"], aspect: "9:16", duration: 15, defaults: SAAS_D });
TP({ id: "featureSpotlight", name: "Feature Spotlight", category: "SaaS", tags: ["saas", "feature", "release"], description: "Single-feature release announcement.", style: "saas", scenes: ["title", "automation", "result", "cta"], aspect: "16:9", duration: 18, defaults: { ...SAAS_D, headline: "New: Autopilot workflows" } });
TP({ id: "devTool", name: "Developer Tool", category: "Technology", tags: ["developer", "api", "code"], description: "Code editor, terminal feel, metrics.", style: "neon", scenes: ["hook", "code", "metrics", "cta"], aspect: "16:9", duration: 20, defaults: { ...SAAS_D, headline: "The API for motion.", cta: "Read the docs", stats: ["12ms|p95 latency", "99.99%|uptime", "40k|developers"] } });
TP({ id: "pricingPromo", name: "Pricing Promo", category: "SaaS", tags: ["pricing", "offer", "conversion"], description: "Hook → features → pricing → CTA.", style: "saas", scenes: ["hook", "features", "pricing", "cta"], aspect: "16:9", duration: 18, defaults: { ...SAAS_D, headline: "Everything you need. One price." } });
TP({ id: "testimonialAd", name: "Customer Story", category: "Corporate", tags: ["testimonial", "social-proof", "case-study"], description: "Customer quote, results and CTA.", style: "minimal", scenes: ["statement", "testimonial", "metrics", "cta"], aspect: "16:9", duration: 20, defaults: { ...SAAS_D, subtitle: "How Northwind cut onboarding time by 70%." } });
TP({ id: "fintechApp", name: "Fintech App", category: "Finance", tags: ["fintech", "app", "mobile"], description: "Mobile banking app promo.", style: "finance", scenes: ["phone", "metrics", "testimonial", "cta"], aspect: "9:16", duration: 18, defaults: { headline: "Banking at the speed of thought.", cta: "Open an account", stats: ["0%|fees", "2min|signup", "4.9★|rating"] } });
TP({ id: "productHunt", name: "Product Hunt Launch", category: "Startup", tags: ["launch", "startup", "product-hunt"], description: "Launch-day teaser: logo, hook, dashboard, CTA.", style: "saas", scenes: ["logo", "kinetic", "dashboard", "cta"], aspect: "16:9", duration: 16, defaults: { ...SAAS_D, headline: "We launch today", cta: "Support us on Product Hunt" } });
TP({ id: "neonEvent", name: "Neon Event Promo", category: "Gaming", tags: ["event", "neon", "music"], description: "Neon event/music promo with beat-synced visuals.", style: "neon", scenes: ["kinetic", "statistic", "cta"], aspect: "1:1", duration: 12, defaults: { headline: "Friday night live", stats: ["10|artists on stage"], cta: "Get tickets" }, music: 126 });
TP({ id: "ai3dReveal", name: "AI 3D Reveal", category: "AI", tags: ["ai", "3d", "reveal"], description: "Holographic 3D core, AI prompt, CTA.", style: "futuristic", scenes: ["aiProcessing", "product3d", "aiPrompt", "cta"], aspect: "16:9", duration: 20, defaults: { ...SAAS_D, headline: "Thinking, visualised." } });

/** Build a complete editable VideoDoc from a template id + input. */
export function buildTemplate(id: string, input: TemplateInput = {}): VideoDoc {
  const def = TEMPLATES[id] ?? TEMPLATES.productLaunch;
  const style: Style = { ...(STYLES[def.style] ?? STYLES.saas) };
  let themeId = input.theme ?? style.theme;
  if (input.brand?.primary) { const base = getTheme(themeId); const t = generateTheme({ primary: input.brand.primary, mode: base.dark ? (style.theme === "luxury" ? "luxury" : "dark") : "light", font: base.font.id as never }); registerTheme(t); themeId = t.id; }
  if (input.background) { style.bg = input.background; style.bgKind = input.background in (SHADER_IDS_CACHE ?? {}) ? "shader" : "background"; }
  if (input.transition) style.transition = input.transition;
  if (input.typography) style.text = input.typography;
  const theme = getTheme(themeId);
  const aspect = input.aspect ?? def.aspect;
  const [w, h] = aspect === "custom" ? [input.width ?? 1920, input.height ?? 1080] : ASPECT_SIZES[aspect];
  const fps = input.fps ?? 30;
  const L = layoutFor(w, h);
  const I = { ...def.defaults, ...input, headline: input.headline ?? def.defaults.headline ?? "Built for what's next.", subtitle: input.subtitle ?? def.defaults.subtitle ?? "", cta: input.cta ?? def.defaults.cta ?? "Get started" };
  const brand = input.brand?.name ?? "NewBrand";
  const baseFrames = def.scenes.reduce((a, s) => a + (SCENE_BUILDERS[s]?.frames ?? 90), 0);
  const targetFrames = Math.round((input.duration ?? def.duration) * fps);
  const k = targetFrames / baseFrames;
  const scenes: Scene[] = def.scenes.map((sid, i) => {
    const b = SCENE_BUILDERS[sid] ?? SCENE_BUILDERS.title;
    const dur = Math.max(20, Math.round(b.frames * k * (fps / 30)));
    const trDur = i === 0 ? 0 : Math.min(18, Math.round(dur * 0.2));
    const nodes = b.build({ L, I, style, theme, brand, dur: dur + trDur });
    return createScene(b.name, dur + trDur, nodes, { type: b.type, ...(i > 0 ? { transition: { type: style.transition, duration: trDur } } : {}) });
  });
  const music = input.music === null ? undefined : input.music ?? def.music;
  const doc = createDoc({ name: `${brand} — ${def.name}`, width: w, height: h, fps, theme: themeId, scenes, effects: style.effects.map((fx) => ({ ...fx, id: uid("fx") })), audio: music ? [{ id: uid("au"), name: `Beat ${music} BPM`, kind: "music", generator: { type: "beat", bpm: music }, start: 0, volume: 0.8, fadeIn: 15, fadeOut: 30 }] : [], meta: { templateId: def.id, input: { ...input, aspect } } });
  return doc;
}
let SHADER_IDS_CACHE: Record<string, unknown> | null = null;
export function setShaderIds(ids: Record<string, unknown>) { SHADER_IDS_CACHE = ids; }

/** Compose an arbitrary video from story scene ids (Story Engine). */
export function composeStory(sceneIds: string[], input: TemplateInput & { style?: string } = {}): VideoDoc {
  const id = `__story_${sceneIds.join("_")}`;
  TEMPLATES[id] = { id, name: "Custom Story", category: "Custom", tags: [], description: "Composed story", style: input.style ?? "saas", scenes: sceneIds.filter((s) => SCENE_BUILDERS[s]), aspect: input.aspect ?? "16:9", duration: input.duration ?? sceneIds.length * 3.5, defaults: {} };
  const doc = buildTemplate(id, input);
  delete TEMPLATES[id];
  doc.meta = { ...doc.meta, templateId: undefined, story: sceneIds, style: input.style ?? "saas" };
  return doc;
}
