/* Post-processing pipeline: Scene → Bloom → DoF → Chromatic → Grain → Vignette → Grade → Output.
 * Each effect is deterministic in (t, params, seed) and works on a Canvas2D surface. */
import { hash1, mulberry32, withAlpha, clamp } from "@/core/math";
import { getCanvas, ctxOf, glowSprite, type Ctx2D } from "@/render/core";

export type EffectParams = Record<string, unknown>;
export type EffectDef = { id: string; name: string; group: "light" | "lens" | "color" | "texture" | "digital" | "cinematic"; tags: string[]; description: string; order: number; defaults: Record<string, number | string>; heavy?: boolean; apply: (ctx: Ctx2D, w: number, h: number, t: number, P: Record<string, number | string>, seed: number) => void };
export const EFFECTS: Record<string, EffectDef> = {};
const E = (d: EffectDef) => { EFFECTS[d.id] = d; };
const n = (P: Record<string, number | string>, k: string) => Number(P[k]);
function snapshot(ctx: Ctx2D, w: number, h: number, key = "fx_snap") { const c = getCanvas(key, w, h); const g = ctxOf(c); g.clearRect(0, 0, w, h); g.drawImage(ctx.canvas, 0, 0, w, h); return c; }

/** RGB split: draws the source with per-channel offsets. */
export function rgbSplit(ctx: Ctx2D, src: HTMLCanvasElement, w: number, h: number, amount: number, angle = 0) {
  const dx = Math.cos(angle) * amount, dy = Math.sin(angle) * amount;
  const chans: [string, number, number][] = [["#ff0000", -dx, -dy], ["#00ff00", 0, 0], ["#0000ff", dx, dy]];
  ctx.save(); ctx.clearRect(0, 0, w, h); ctx.fillStyle = "#000"; ctx.fillRect(0, 0, w, h);
  chans.forEach(([c, ox, oy], i) => {
    const tmp = getCanvas(`rgb_${i}`, w, h); const g = ctxOf(tmp);
    g.globalCompositeOperation = "source-over"; g.clearRect(0, 0, w, h); g.drawImage(src, ox, oy);
    g.globalCompositeOperation = "multiply"; g.fillStyle = c; g.fillRect(0, 0, w, h);
    ctx.globalCompositeOperation = i === 0 ? "source-over" : "lighter"; ctx.drawImage(tmp, 0, 0);
  });
  ctx.restore();
}

E({ id: "bloom", name: "Bloom", group: "light", order: 10, heavy: true, tags: ["glow", "cinematic"], description: "Bright areas bleed soft light.", defaults: { intensity: 0.6, radius: 24, threshold: 0.6 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w / 2, h / 2, "bloom_small"); const g = ctxOf(s); g.globalCompositeOperation = "source-over"; g.filter = `brightness(${1 - n(P, "threshold") * 0.5}) contrast(${1 + n(P, "threshold") * 2}) blur(${n(P, "radius") / 2}px)`; g.drawImage(s, 0, 0); g.filter = "none"; ctx.save(); ctx.globalCompositeOperation = "screen"; ctx.globalAlpha = n(P, "intensity"); ctx.drawImage(s, 0, 0, w, h); ctx.restore(); } });
E({ id: "glow", name: "Soft Glow", group: "light", order: 11, heavy: true, tags: ["dreamy", "soft"], description: "Diffuse dreamy glow over the whole frame.", defaults: { intensity: 0.35, radius: 40 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.globalCompositeOperation = "lighter"; ctx.globalAlpha = n(P, "intensity"); ctx.filter = `blur(${n(P, "radius")}px)`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "blur", name: "Gaussian Blur", group: "lens", order: 20, tags: ["blur", "focus"], description: "Uniform gaussian blur.", defaults: { amount: 6 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = `blur(${n(P, "amount")}px)`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "depthOfField", name: "Depth of Field", group: "lens", order: 21, heavy: true, tags: ["cinematic", "bokeh", "focus"], description: "Tilt-shift style focus band with blurred foreground/background.", defaults: { focus: 0.5, range: 0.25, amount: 10 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); const b = getCanvas("dof_b", w, h); const g = ctxOf(b); g.clearRect(0, 0, w, h); g.filter = `blur(${n(P, "amount")}px)`; g.drawImage(s, 0, 0); g.filter = "none"; g.globalCompositeOperation = "destination-out"; const f = n(P, "focus") * h, r = n(P, "range") * h; const gr = g.createLinearGradient(0, f - r, 0, f + r); gr.addColorStop(0, "rgba(0,0,0,0)"); gr.addColorStop(0.35, "rgba(0,0,0,1)"); gr.addColorStop(0.65, "rgba(0,0,0,1)"); gr.addColorStop(1, "rgba(0,0,0,0)"); g.fillStyle = gr; g.fillRect(0, f - r, w, r * 2); g.globalCompositeOperation = "source-over"; ctx.drawImage(b, 0, 0); } });
E({ id: "rackFocus", name: "Rack Focus", group: "lens", order: 22, tags: ["cinematic", "camera"], description: "Animated focus pull from blurred to sharp.", defaults: { amount: 14, duration: 1.5 }, apply: (ctx, w, h, t, P) => { const a = n(P, "amount") * (1 - clamp(t / n(P, "duration"))); if (a < 0.3) return; const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = `blur(${a}px)`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "chromatic", name: "Chromatic Aberration", group: "lens", order: 30, heavy: true, tags: ["lens", "cinematic", "tech"], description: "Red/blue fringing towards the edges.", defaults: { amount: 3 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); rgbSplit(ctx, s, w, h, n(P, "amount")); } });
E({ id: "rgbSplit", name: "RGB Split", group: "digital", order: 31, heavy: true, tags: ["glitch", "music"], description: "Animated RGB channel separation.", defaults: { amount: 8, speed: 1 }, apply: (ctx, w, h, t, P) => { const s = snapshot(ctx, w, h); rgbSplit(ctx, s, w, h, n(P, "amount") * (0.6 + 0.4 * Math.sin(t * 3 * n(P, "speed"))), t * n(P, "speed")); } });
E({ id: "lensDistortion", name: "Lens Distortion", group: "lens", order: 32, tags: ["lens", "fisheye"], description: "Barrel distortion approximated with concentric scaling.", defaults: { amount: 0.06 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); const k = n(P, "amount"); ctx.save(); for (let i = 10; i >= 1; i--) { const r = i / 10; const sc = 1 + k * (1 - r * r); ctx.save(); ctx.beginPath(); ctx.ellipse(w / 2, h / 2, (w / 2) * r * 1.42, (h / 2) * r * 1.42, 0, 0, Math.PI * 2); ctx.clip(); ctx.translate(w / 2, h / 2); ctx.scale(sc, sc); ctx.drawImage(s, -w / 2, -h / 2); ctx.restore(); } ctx.restore(); } });
E({ id: "grain", name: "Film Grain", group: "texture", order: 40, tags: ["film", "cinematic", "texture"], description: "Animated seeded film grain.", defaults: { amount: 0.08, size: 1.5 }, apply: (ctx, w, h, t, P, seed) => { const gw = Math.ceil(w / n(P, "size") / 2), gh = Math.ceil(h / n(P, "size") / 2); const c = getCanvas("grain_tex", gw, gh); const g = ctxOf(c); const img = g.createImageData(gw, gh); const rnd = mulberry32(Math.floor(t * 24) * 7919 + seed); for (let i = 0; i < img.data.length; i += 4) { const v = rnd() * 255; img.data[i] = img.data[i + 1] = img.data[i + 2] = v; img.data[i + 3] = 255; } g.putImageData(img, 0, 0); ctx.save(); ctx.globalCompositeOperation = "overlay"; ctx.globalAlpha = n(P, "amount") * 3; ctx.imageSmoothingEnabled = false; ctx.drawImage(c, 0, 0, w, h); ctx.restore(); } });
E({ id: "noise", name: "Digital Noise", group: "texture", order: 41, tags: ["noise", "tv"], description: "Coloured digital sensor noise.", defaults: { amount: 0.06 }, apply: (ctx, w, h, t, P, seed) => { const gw = Math.ceil(w / 3), gh = Math.ceil(h / 3); const c = getCanvas("noise_tex", gw, gh); const g = ctxOf(c); const img = g.createImageData(gw, gh); const rnd = mulberry32(Math.floor(t * 30) + seed); for (let i = 0; i < img.data.length; i += 4) { img.data[i] = rnd() * 255; img.data[i + 1] = rnd() * 255; img.data[i + 2] = rnd() * 255; img.data[i + 3] = 255; } g.putImageData(img, 0, 0); ctx.save(); ctx.globalCompositeOperation = "screen"; ctx.globalAlpha = n(P, "amount"); ctx.drawImage(c, 0, 0, w, h); ctx.restore(); } });
E({ id: "vignette", name: "Vignette", group: "lens", order: 50, tags: ["cinematic", "focus"], description: "Darkened frame edges.", defaults: { amount: 0.55, size: 0.65, color: "#000000" }, apply: (ctx, w, h, _t, P) => { const g = ctx.createRadialGradient(w / 2, h / 2, Math.min(w, h) * n(P, "size") * 0.4, w / 2, h / 2, Math.hypot(w, h) / 2); g.addColorStop(0, "rgba(0,0,0,0)"); g.addColorStop(1, withAlpha(String(P.color), n(P, "amount"))); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); } });
E({ id: "colorGrade", name: "Color Grade", group: "color", order: 60, tags: ["grade", "color"], description: "Exposure, contrast, saturation and hue in one pass.", defaults: { exposure: 1, contrast: 1.05, saturation: 1.1, hue: 0 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = `brightness(${n(P, "exposure")}) contrast(${n(P, "contrast")}) saturate(${n(P, "saturation")}) hue-rotate(${n(P, "hue")}deg)`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "exposure", name: "Exposure", group: "color", order: 61, tags: ["color"], description: "Brightness adjustment.", defaults: { amount: 1.15 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = `brightness(${n(P, "amount")})`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "saturation", name: "Saturation", group: "color", order: 62, tags: ["color"], description: "Saturation adjustment.", defaults: { amount: 1.4 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = `saturate(${n(P, "amount")})`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "contrast", name: "Contrast", group: "color", order: 63, tags: ["color"], description: "Contrast adjustment.", defaults: { amount: 1.25 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = `contrast(${n(P, "amount")})`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "hueShift", name: "Hue Shift", group: "color", order: 64, tags: ["color", "psychedelic"], description: "Animated hue rotation.", defaults: { speed: 30 }, apply: (ctx, w, h, t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = `hue-rotate(${t * n(P, "speed")}deg)`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "monochrome", name: "Monochrome", group: "color", order: 65, tags: ["bw", "editorial"], description: "Black and white conversion.", defaults: { amount: 1 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = `grayscale(${n(P, "amount")}) contrast(1.1)`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "sepia", name: "Vintage", group: "color", order: 66, tags: ["retro", "warm"], description: "Warm vintage sepia tone.", defaults: { amount: 0.6 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = `sepia(${n(P, "amount")}) contrast(1.05)`; ctx.drawImage(s, 0, 0); ctx.restore(); } });
E({ id: "duotone", name: "Duotone", group: "color", order: 67, tags: ["editorial", "bold"], description: "Map luminance to two colours.", defaults: { dark: "#1e1b4b", light: "#f0abfc" }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); ctx.save(); ctx.clearRect(0, 0, w, h); ctx.filter = "grayscale(1) contrast(1.2)"; ctx.drawImage(s, 0, 0); ctx.filter = "none"; ctx.globalCompositeOperation = "multiply"; ctx.fillStyle = String(P.light); ctx.fillRect(0, 0, w, h); ctx.globalCompositeOperation = "lighten"; ctx.fillStyle = String(P.dark); ctx.fillRect(0, 0, w, h); ctx.restore(); } });
E({ id: "tealOrange", name: "Teal & Orange", group: "color", order: 68, tags: ["cinematic", "blockbuster"], description: "Blockbuster teal shadows and orange highlights.", defaults: { amount: 0.25 }, apply: (ctx, w, h, _t, P) => { ctx.save(); ctx.globalCompositeOperation = "soft-light"; ctx.globalAlpha = n(P, "amount") * 2; const g = ctx.createLinearGradient(0, 0, w, h); g.addColorStop(0, "#008b8b"); g.addColorStop(1, "#ff8c42"); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); ctx.restore(); } });
E({ id: "scanlines", name: "Scanlines", group: "digital", order: 70, tags: ["retro", "crt", "tech"], description: "CRT scanlines with rolling bar.", defaults: { amount: 0.18, spacing: 3 }, apply: (ctx, w, h, t, P) => { ctx.save(); ctx.fillStyle = `rgba(0,0,0,${n(P, "amount")})`; const s = n(P, "spacing"); for (let y = 0; y < h; y += s) ctx.fillRect(0, y, w, s / 2); const ry = ((t * 0.2) % 1) * h; const g = ctx.createLinearGradient(0, ry - 60, 0, ry); g.addColorStop(0, "rgba(255,255,255,0)"); g.addColorStop(1, "rgba(255,255,255,0.05)"); ctx.fillStyle = g; ctx.fillRect(0, ry - 60, w, 60); ctx.restore(); } });
E({ id: "glitch", name: "Glitch", group: "digital", order: 71, tags: ["glitch", "cyber"], description: "Seeded slice displacement bursts.", defaults: { amount: 0.6, frequency: 0.35 }, apply: (ctx, w, h, t, P, seed) => { const f = Math.floor(t * 12); if (hash1(f * 1.3 + seed) > n(P, "frequency")) return; const s = snapshot(ctx, w, h); const rnd = mulberry32(f + seed); for (let i = 0; i < 8; i++) { const y = rnd() * h, hh = rnd() * h * 0.08 + 2, dx = (rnd() - 0.5) * w * 0.1 * n(P, "amount"); ctx.drawImage(s, 0, y, w, hh, dx, y, w, hh); } } });
E({ id: "pixelate", name: "Pixelate", group: "digital", order: 72, tags: ["retro", "8bit"], description: "Mosaic pixelation.", defaults: { size: 12 }, apply: (ctx, w, h, _t, P) => { const sz = Math.max(2, n(P, "size")); const c = getCanvas("pix", Math.ceil(w / sz), Math.ceil(h / sz)); const g = ctxOf(c); g.drawImage(ctx.canvas, 0, 0, c.width, c.height); ctx.save(); ctx.imageSmoothingEnabled = false; ctx.clearRect(0, 0, w, h); ctx.drawImage(c, 0, 0, w, h); ctx.restore(); } });
E({ id: "vhs", name: "VHS", group: "digital", order: 73, tags: ["retro", "tape"], description: "Tape wobble, colour bleed and tracking noise.", defaults: { amount: 0.5 }, apply: (ctx, w, h, t, P, seed) => { const s = snapshot(ctx, w, h); const a = n(P, "amount"); for (let y = 0; y < h; y += 8) { const dx = Math.sin(y * 0.05 + t * 8) * 2 * a + (hash1(Math.floor(t * 10) + y + seed) > 0.985 ? 20 * a : 0); ctx.drawImage(s, 0, y, w, 8, dx, y, w, 8); } ctx.save(); ctx.globalCompositeOperation = "screen"; ctx.globalAlpha = 0.15 * a; ctx.drawImage(s, 4 * a, 0); ctx.restore(); const ty = ((t * 0.3) % 1) * h; ctx.fillStyle = `rgba(255,255,255,${0.06 * a})`; ctx.fillRect(0, ty, w, 6); } });
E({ id: "sharpen", name: "Clarity", group: "lens", order: 23, tags: ["crisp"], description: "Local contrast boost (unsharp-mask style).", defaults: { amount: 0.4 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); const b = getCanvas("sharp_b", w, h); const g = ctxOf(b); g.clearRect(0, 0, w, h); g.filter = "blur(3px) invert(1)"; g.drawImage(s, 0, 0); g.filter = "none"; ctx.save(); ctx.globalCompositeOperation = "overlay"; ctx.globalAlpha = n(P, "amount"); ctx.drawImage(b, 0, 0); ctx.restore(); } });
E({ id: "fog", name: "Fog", group: "cinematic", order: 80, tags: ["atmosphere", "moody"], description: "Drifting low fog layers.", defaults: { amount: 0.35, color: "#c7d2fe" }, apply: (ctx, w, h, t, P) => { ctx.save(); ctx.globalCompositeOperation = "screen"; for (let i = 0; i < 5; i++) { const x = ((t * 20 * (i + 1)) % (w * 1.5)) - w * 0.25; const g = ctx.createRadialGradient(x, h * (0.7 + i * 0.06), 0, x, h * (0.7 + i * 0.06), w * 0.5); g.addColorStop(0, withAlpha(String(P.color), n(P, "amount") * 0.5)); g.addColorStop(1, withAlpha(String(P.color), 0)); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); } ctx.restore(); } });
E({ id: "lightLeak", name: "Light Leak", group: "cinematic", order: 81, tags: ["film", "warm"], description: "Warm film light leaks drifting across frame.", defaults: { amount: 0.45, color: "#ff8a3d" }, apply: (ctx, w, h, t, P) => { ctx.save(); ctx.globalCompositeOperation = "screen"; const x = w * (0.5 + Math.sin(t * 0.4) * 0.6); const g = ctx.createRadialGradient(x, h * 0.2, 0, x, h * 0.2, w * 0.7); g.addColorStop(0, withAlpha(String(P.color), n(P, "amount"))); g.addColorStop(1, withAlpha(String(P.color), 0)); ctx.fillStyle = g; ctx.fillRect(0, 0, w, h); ctx.restore(); } });
E({ id: "lensFlare", name: "Lens Flare", group: "cinematic", order: 82, tags: ["cinematic", "anamorphic", "sci-fi"], description: "Anamorphic streak with ghost orbs.", defaults: { amount: 0.6, x: 0.7, y: 0.3, color: "#9ecbff" }, apply: (ctx, w, h, t, P) => { const x = n(P, "x") * w + Math.sin(t * 0.5) * 40, y = n(P, "y") * h; const c = String(P.color); ctx.save(); ctx.globalCompositeOperation = "lighter"; ctx.globalAlpha = n(P, "amount"); const g = ctx.createLinearGradient(0, y, w, y); g.addColorStop(0, withAlpha(c, 0)); g.addColorStop(x / w, withAlpha(c, 0.8)); g.addColorStop(1, withAlpha(c, 0)); ctx.fillStyle = g; ctx.fillRect(0, y - 2, w, 4); ctx.drawImage(glowSprite(c, 128), x - 90, y - 90, 180, 180); for (let i = 1; i <= 4; i++) { const k = i * 0.35; const gx = x + (w / 2 - x) * k * 2, gy = y + (h / 2 - y) * k * 2; ctx.drawImage(glowSprite(i % 2 ? "#ff9ecf" : c, 64), gx - 20 * i, gy - 20 * i, 40 * i, 40 * i); } ctx.restore(); } });
E({ id: "lightSweep", name: "Light Sweep", group: "cinematic", order: 83, tags: ["premium", "logo", "shine"], description: "Diagonal specular sweep across frame.", defaults: { amount: 0.35, period: 3 }, apply: (ctx, w, h, t, P) => { const k = (t % n(P, "period")) / n(P, "period"); const x = -w * 0.3 + k * w * 1.6; ctx.save(); ctx.globalCompositeOperation = "overlay"; ctx.globalAlpha = n(P, "amount") * 2; ctx.translate(x, 0); ctx.transform(1, 0, -0.4, 1, 0, 0); const g = ctx.createLinearGradient(-120, 0, 120, 0); g.addColorStop(0, "rgba(255,255,255,0)"); g.addColorStop(0.5, "rgba(255,255,255,1)"); g.addColorStop(1, "rgba(255,255,255,0)"); ctx.fillStyle = g; ctx.fillRect(-120, 0, 240, h * 1.5); ctx.restore(); } });
E({ id: "volumetric", name: "Volumetric Light", group: "cinematic", order: 84, tags: ["god-rays", "atmosphere"], description: "God rays from a light source.", defaults: { amount: 0.3, x: 0.5, y: -0.1, color: "#fff4d6" }, apply: (ctx, w, h, t, P) => { const ox = n(P, "x") * w, oy = n(P, "y") * h; ctx.save(); ctx.globalCompositeOperation = "screen"; for (let i = 0; i < 12; i++) { const a = Math.PI / 2 + (hash1(i) - 0.5) * 1.4 + Math.sin(t * 0.3 + i) * 0.03; const sp = 0.03 + hash1(i * 2) * 0.03; const g = ctx.createLinearGradient(ox, oy, ox + Math.cos(a) * h, oy + Math.sin(a) * h); g.addColorStop(0, withAlpha(String(P.color), n(P, "amount"))); g.addColorStop(1, withAlpha(String(P.color), 0)); ctx.fillStyle = g; ctx.beginPath(); ctx.moveTo(ox, oy); ctx.lineTo(ox + Math.cos(a - sp) * h * 2, oy + Math.sin(a - sp) * h * 2); ctx.lineTo(ox + Math.cos(a + sp) * h * 2, oy + Math.sin(a + sp) * h * 2); ctx.fill(); } ctx.restore(); } });
E({ id: "bokehOverlay", name: "Bokeh Overlay", group: "cinematic", order: 85, tags: ["bokeh", "dreamy"], description: "Foreground out-of-focus light discs.", defaults: { amount: 0.4, color: "#ffd6a5" }, apply: (ctx, w, h, t, P) => { ctx.save(); ctx.globalCompositeOperation = "screen"; ctx.globalAlpha = n(P, "amount"); for (let i = 0; i < 14; i++) { const x = (hash1(i) * w + t * 12 * (i % 3 + 1)) % w, y = hash1(i * 3) * h; const r = 30 + hash1(i * 5) * 70; ctx.drawImage(glowSprite(String(P.color), 128), x - r, y - r, r * 2, r * 2); } ctx.restore(); } });
E({ id: "dust", name: "Dust & Scratches", group: "texture", order: 86, tags: ["film", "vintage"], description: "Film dust specks and vertical scratches.", defaults: { amount: 0.5 }, apply: (ctx, w, h, t, P, seed) => { const rnd = mulberry32(Math.floor(t * 24) + seed); ctx.save(); ctx.globalAlpha = n(P, "amount"); ctx.fillStyle = "rgba(255,255,255,0.6)"; for (let i = 0; i < 20; i++) ctx.fillRect(rnd() * w, rnd() * h, rnd() * 3, rnd() * 3); ctx.strokeStyle = "rgba(255,255,255,0.25)"; if (rnd() > 0.6) { const x = rnd() * w; ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x + rnd() * 6, h); ctx.stroke(); } ctx.restore(); } });
E({ id: "letterbox", name: "Letterbox", group: "cinematic", order: 90, tags: ["cinematic", "widescreen"], description: "Cinemascope bars (2.39:1) with optional animation.", defaults: { ratio: 2.39, animate: 1 }, apply: (ctx, w, h, t, P) => { const target = w / n(P, "ratio"); const bar = Math.max(0, (h - target) / 2) * (n(P, "animate") ? clamp(t / 1) : 1); ctx.fillStyle = "#000"; ctx.fillRect(0, 0, w, bar); ctx.fillRect(0, h - bar, w, bar); } });
E({ id: "cameraShake", name: "Camera Shake", group: "cinematic", order: 5, tags: ["camera", "impact", "handheld"], description: "Deterministic camera shake / handheld wobble.", defaults: { amount: 6, speed: 1 }, apply: (ctx, w, h, t, P) => { const s = snapshot(ctx, w, h); const a = n(P, "amount"), sp = n(P, "speed"); const dx = (Math.sin(t * 13 * sp) + Math.sin(t * 7.3 * sp) * 0.5) * a, dy = (Math.cos(t * 11 * sp) + Math.sin(t * 5.1 * sp) * 0.5) * a; ctx.save(); ctx.clearRect(0, 0, w, h); ctx.translate(w / 2 + dx, h / 2 + dy); ctx.rotate(Math.sin(t * 3 * sp) * a * 0.0015); ctx.scale(1.03, 1.03); ctx.drawImage(s, -w / 2, -h / 2); ctx.restore(); } });
E({ id: "motionBlur", name: "Motion Blur", group: "lens", order: 24, tags: ["speed", "cinematic"], description: "Directional motion blur (multi-tap).", defaults: { amount: 12, angle: 0 }, apply: (ctx, w, h, _t, P) => { const s = snapshot(ctx, w, h); const a = (n(P, "angle") * Math.PI) / 180; ctx.save(); ctx.clearRect(0, 0, w, h); for (let i = 0; i < 6; i++) { const k = (i / 5 - 0.5) * n(P, "amount"); ctx.globalAlpha = 1 / (i + 1); ctx.drawImage(s, Math.cos(a) * k, Math.sin(a) * k); } ctx.restore(); } });

export type EffectConfigLike = { type: string; params?: Record<string, unknown>; enabled?: boolean };
export function applyEffects(ctx: Ctx2D, w: number, h: number, t: number, effects: EffectConfigLike[] | undefined, seed: number, quality: string) {
  if (!effects?.length) return;
  const sorted = effects.filter((e) => e.enabled !== false && EFFECTS[e.type]).sort((a, b) => EFFECTS[a.type].order - EFFECTS[b.type].order);
  for (const e of sorted) {
    const def = EFFECTS[e.type];
    if (def.heavy && quality === "low") continue;
    ctx.save();
    try { def.apply(ctx, w, h, t, { ...def.defaults, ...(e.params as Record<string, number | string>) }, seed); } finally { ctx.restore(); }
  }
}
