/* Transition engine — composites outgoing scene A and incoming scene B at progress p (0→1). */
import { getEase, hash1, mulberry32, clamp, withAlpha } from "@/core/math";
import { getCanvas, ctxOf, type Ctx2D } from "@/render/core";
import { rgbSplit } from "./post";

type Src = HTMLCanvasElement;
export type TransitionDef = { id: string; name: string; group: "basic" | "motion" | "mask" | "3d" | "digital" | "organic" | "light"; tags: string[]; description: string; ease: string; duration: number; draw: (ctx: Ctx2D, a: Src, b: Src, p: number, w: number, h: number, P: Record<string, unknown>) => void };
export const TRANSITIONS: Record<string, TransitionDef> = {};
const T = (id: string, name: string, group: TransitionDef["group"], tags: string[], description: string, draw: TransitionDef["draw"], ease = "easeInOutCubic", duration = 18) => { TRANSITIONS[id] = { id, name, group, tags, description, ease, duration, draw }; };
const clipDraw = (ctx: Ctx2D, img: Src, path: () => void) => { ctx.save(); ctx.beginPath(); path(); ctx.clip(); ctx.drawImage(img, 0, 0); ctx.restore(); };
const blurred = (img: Src, px: number, w: number, h: number) => { if (px < 0.5) return img; const c = getCanvas("tr_blur", w, h); const g = ctxOf(c); g.clearRect(0, 0, w, h); g.filter = `blur(${px}px)`; g.drawImage(img, 0, 0); g.filter = "none"; return c; };

// Basic
T("cut", "Cut", "basic", ["hard", "fast"], "Instant cut at the midpoint.", (ctx, a, b, p) => ctx.drawImage(p < 0.5 ? a : b, 0, 0), "linear", 2);
T("fade", "Fade Through Black", "basic", ["classic"], "Fade out to black then in.", (ctx, a, b, p, w, h) => { ctx.fillStyle = "#000"; ctx.fillRect(0, 0, w, h); ctx.globalAlpha = p < 0.5 ? 1 - p * 2 : (p - 0.5) * 2; ctx.drawImage(p < 0.5 ? a : b, 0, 0); ctx.globalAlpha = 1; });
T("fadeWhite", "Fade Through White", "basic", ["bright", "dreamy"], "Fade through white.", (ctx, a, b, p, w, h) => { ctx.fillStyle = "#fff"; ctx.fillRect(0, 0, w, h); ctx.globalAlpha = p < 0.5 ? 1 - p * 2 : (p - 0.5) * 2; ctx.drawImage(p < 0.5 ? a : b, 0, 0); ctx.globalAlpha = 1; });
T("crossfade", "Crossfade", "basic", ["smooth", "minimal"], "Dissolve A into B.", (ctx, a, b, p) => { ctx.drawImage(a, 0, 0); ctx.globalAlpha = p; ctx.drawImage(b, 0, 0); ctx.globalAlpha = 1; }, "easeInOutSine");
T("blur", "Blur Dissolve", "basic", ["soft", "cinematic"], "Defocus out, refocus in.", (ctx, a, b, p, w, h) => { const bp = Math.sin(p * Math.PI) * 24; ctx.drawImage(blurred(a, bp, w, h), 0, 0); ctx.globalAlpha = p; ctx.drawImage(blurred(b, bp, w, h), 0, 0); ctx.globalAlpha = 1; });
T("flash", "Flash", "light", ["impact", "music"], "White flash cut.", (ctx, a, b, p, w, h) => { ctx.drawImage(p < 0.5 ? a : b, 0, 0); ctx.fillStyle = `rgba(255,255,255,${Math.max(0, 1 - Math.abs(p - 0.5) * 4)})`; ctx.fillRect(0, 0, w, h); }, "linear", 10);
T("dipColor", "Dip to Color", "basic", ["brand"], "Dip through a brand colour.", (ctx, a, b, p, w, h, P) => { ctx.drawImage(p < 0.5 ? a : b, 0, 0); ctx.fillStyle = withAlpha(String(P.color ?? "#7c8cff"), 1 - Math.abs(p - 0.5) * 2); ctx.fillRect(0, 0, w, h); });
// Motion
const slide = (dx: number, dy: number, push: boolean) => (ctx: Ctx2D, a: Src, b: Src, p: number, w: number, h: number) => { if (push) ctx.drawImage(a, -dx * w * p, -dy * h * p); else ctx.drawImage(a, 0, 0); ctx.drawImage(b, dx * w * (1 - p), dy * h * (1 - p)); };
T("slideLeft", "Slide Left", "motion", ["slide"], "B slides over from the right.", slide(1, 0, false), "emphasized");
T("slideRight", "Slide Right", "motion", ["slide"], "B slides over from the left.", slide(-1, 0, false), "emphasized");
T("slideUp", "Slide Up", "motion", ["slide", "social"], "B slides up over A.", slide(0, 1, false), "emphasized");
T("slideDown", "Slide Down", "motion", ["slide"], "B slides down over A.", slide(0, -1, false), "emphasized");
T("pushLeft", "Push Left", "motion", ["push"], "B pushes A out to the left.", slide(1, 0, true), "easeInOutQuart");
T("pushRight", "Push Right", "motion", ["push"], "B pushes A out to the right.", slide(-1, 0, true), "easeInOutQuart");
T("pushUp", "Push Up", "motion", ["push", "vertical"], "B pushes A upward.", slide(0, 1, true), "easeInOutQuart");
T("pushDown", "Push Down", "motion", ["push"], "B pushes A downward.", slide(0, -1, true), "easeInOutQuart");
T("whip", "Whip Pan", "motion", ["fast", "energetic", "youtube"], "Motion-blurred whip pan.", (ctx, a, b, p, w, h) => { const bl = Math.sin(p * Math.PI) * 40; for (let i = 0; i < 5; i++) { const k = (i - 2) * bl * 0.5; ctx.globalAlpha = 0.3; ctx.drawImage(a, -w * p + k, 0); ctx.drawImage(b, w * (1 - p) + k, 0); } ctx.globalAlpha = 1; void h; }, "easeInOutExpo", 12);
T("zoomIn", "Zoom Through", "motion", ["zoom", "energetic"], "Zoom into A and out of B.", (ctx, a, b, p, w, h) => { const s = p < 0.5 ? 1 + p * 4 : 3 - (p - 0.5) * 4; ctx.save(); ctx.translate(w / 2, h / 2); ctx.scale(s, s); ctx.globalAlpha = p < 0.5 ? 1 - p : p; ctx.drawImage(blurred(p < 0.5 ? a : b, Math.sin(p * Math.PI) * 10, w, h), -w / 2, -h / 2); ctx.restore(); ctx.globalAlpha = 1; }, "easeInOutExpo");
T("zoomOut", "Zoom Out", "motion", ["zoom"], "A shrinks away revealing B.", (ctx, a, b, p, w, h) => { ctx.drawImage(b, 0, 0); ctx.save(); ctx.translate(w / 2, h / 2); ctx.scale(1 - p, 1 - p); ctx.globalAlpha = 1 - p; ctx.drawImage(a, -w / 2, -h / 2); ctx.restore(); ctx.globalAlpha = 1; });
T("camera", "Camera Move", "motion", ["camera", "cinematic"], "Parallax camera dolly between scenes.", (ctx, a, b, p, w, h) => { ctx.save(); ctx.translate(w / 2, h / 2); ctx.scale(1 + p * 0.15, 1 + p * 0.15); ctx.drawImage(a, -w / 2 - p * w * 0.3, -h / 2); ctx.restore(); ctx.save(); ctx.globalAlpha = clamp(p * 2 - 0.3); ctx.translate(w / 2, h / 2); ctx.scale(1.15 - p * 0.15, 1.15 - p * 0.15); ctx.drawImage(b, -w / 2 + (1 - p) * w * 0.3, -h / 2); ctx.restore(); }, "cinematic", 30);
T("spin", "Spin", "motion", ["playful"], "Rotating swap.", (ctx, a, b, p, w, h) => { ctx.save(); ctx.translate(w / 2, h / 2); ctx.rotate(p * Math.PI * 2); const s = 1 - Math.sin(p * Math.PI) * 0.6; ctx.scale(s, s); ctx.drawImage(p < 0.5 ? a : b, -w / 2, -h / 2); ctx.restore(); });
T("stretch", "Stretch", "motion", ["elastic"], "Horizontal stretch swap.", (ctx, a, b, p, w, h) => { const k = Math.sin(p * Math.PI); ctx.save(); ctx.translate(w / 2, h / 2); ctx.scale(1 + k * 2, 1 - k * 0.3); ctx.globalAlpha = 1; ctx.drawImage(blurred(p < 0.5 ? a : b, k * 20, w, h), -w / 2, -h / 2); ctx.restore(); });
// Masks
T("wipeLeft", "Wipe Left", "mask", ["wipe", "clean"], "Hard edge wipe right-to-left.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); clipDraw(ctx, b, () => ctx.rect(w * (1 - p), 0, w * p, h)); });
T("wipeRight", "Wipe Right", "mask", ["wipe", "clean"], "Hard edge wipe left-to-right.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); clipDraw(ctx, b, () => ctx.rect(0, 0, w * p, h)); });
T("wipeUp", "Wipe Up", "mask", ["wipe"], "Vertical wipe upward.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); clipDraw(ctx, b, () => ctx.rect(0, h * (1 - p), w, h * p)); });
T("wipeDiagonal", "Diagonal Wipe", "mask", ["wipe", "dynamic"], "Angled wipe.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const x = -h + (w + h * 2) * p; clipDraw(ctx, b, () => { ctx.moveTo(x - h, 0); ctx.lineTo(x, 0); ctx.lineTo(x - h * 1.5, h); ctx.lineTo(x - h * 2.5, h); ctx.lineTo(-w, h); ctx.lineTo(-w, 0); }); });
T("softWipe", "Soft Wipe", "mask", ["soft", "premium"], "Feathered gradient wipe.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const m = getCanvas("tr_mask", w, h); const g = ctxOf(m); g.clearRect(0, 0, w, h); g.drawImage(b, 0, 0); g.globalCompositeOperation = "destination-in"; const x = -w * 0.3 + p * w * 1.6; const gr = g.createLinearGradient(x - w * 0.3, 0, x, 0); gr.addColorStop(0, "rgba(0,0,0,1)"); gr.addColorStop(1, "rgba(0,0,0,0)"); g.fillStyle = gr; g.fillRect(0, 0, w, h); g.globalCompositeOperation = "source-over"; ctx.drawImage(m, 0, 0); });
T("iris", "Iris", "mask", ["circle", "cinematic"], "Circular iris open.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); clipDraw(ctx, b, () => ctx.arc(w / 2, h / 2, Math.hypot(w, h) / 2 * p + 0.1, 0, Math.PI * 2)); });
T("irisClose", "Iris Close", "mask", ["circle", "retro"], "Close iris on A, open on B.", (ctx, a, b, p, w, h) => { const r = Math.hypot(w, h) / 2 * Math.abs(1 - p * 2); ctx.fillStyle = "#000"; ctx.fillRect(0, 0, w, h); clipDraw(ctx, p < 0.5 ? a : b, () => ctx.arc(w / 2, h / 2, r + 0.1, 0, Math.PI * 2)); });
T("diamond", "Diamond", "mask", ["geometric"], "Diamond aperture.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const r = (w + h) * 0.6 * p; clipDraw(ctx, b, () => { ctx.moveTo(w / 2, h / 2 - r); ctx.lineTo(w / 2 + r, h / 2); ctx.lineTo(w / 2, h / 2 + r); ctx.lineTo(w / 2 - r, h / 2); }); });
T("barn", "Barn Doors", "mask", ["doors", "reveal"], "Split open from centre.", (ctx, a, b, p, w, h) => { ctx.drawImage(b, 0, 0); clipDraw(ctx, a, () => ctx.rect(0, 0, w / 2 * (1 - p), h)); ctx.save(); ctx.beginPath(); ctx.rect(w / 2 + (w / 2) * p, 0, w, h); ctx.clip(); ctx.drawImage(a, 0, 0); ctx.restore(); });
T("blinds", "Venetian Blinds", "mask", ["pattern"], "Horizontal blinds reveal.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const n = 10; clipDraw(ctx, b, () => { for (let i = 0; i < n; i++) ctx.rect(0, (i / n) * h, w, (h / n) * p); }); });
T("stripes", "Stripe Reveal", "mask", ["pattern", "dynamic"], "Staggered vertical stripes.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const n = 12; clipDraw(ctx, b, () => { for (let i = 0; i < n; i++) { const k = clamp(p * 1.6 - (i / n) * 0.6); ctx.rect((i / n) * w, h * (1 - k), w / n + 1, h * k); } }); });
T("checker", "Checkerboard", "mask", ["pattern", "retro"], "Checker tiles reveal.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const n = 8, cw = w / n, ch = h / (n * h / w); const rows = Math.ceil(h / cw); clipDraw(ctx, b, () => { for (let y = 0; y < rows; y++) for (let x = 0; x < n; x++) { const k = clamp(p * 2 - ((x + y) % 2) * 0.5 - 0.25); if (k > 0) ctx.rect(x * cw + (cw * (1 - k)) / 2, y * cw + (cw * (1 - k)) / 2, cw * k, cw * k); } }); void ch; });
T("shapeMorph", "Shape Morph", "mask", ["shape", "brand"], "Rounded shape grows from centre to fill.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const s = Math.hypot(w, h) * p; clipDraw(ctx, b, () => ctx.roundRect(w / 2 - s / 2, h / 2 - s / 2, s, s, s * 0.5 * (1 - p) + 4)); });
T("clock", "Clock Wipe", "mask", ["radial", "retro"], "Radial clock sweep.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); clipDraw(ctx, b, () => { ctx.moveTo(w / 2, h / 2); ctx.arc(w / 2, h / 2, Math.hypot(w, h), -Math.PI / 2, -Math.PI / 2 + p * Math.PI * 2); }); });
T("ink", "Ink Spread", "organic", ["ink", "organic", "artistic"], "Organic ink blobs spreading.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const rnd = mulberry32(7); const blobs = Array.from({ length: 9 }, () => [rnd() * w, rnd() * h, rnd() * 0.4]); clipDraw(ctx, b, () => blobs.forEach(([x, y, d]) => { const r = Math.max(0, p - d) / (1 - d) * Math.hypot(w, h) * 0.6; ctx.moveTo(x + r, y); ctx.arc(x, y, r, 0, Math.PI * 2); })); });
// 3D
T("flip", "Flip", "3d", ["3d", "card"], "Card flip around Y axis.", (ctx, a, b, p, w, h) => { const s = Math.abs(Math.cos(p * Math.PI)); ctx.fillStyle = "#000"; ctx.fillRect(0, 0, w, h); ctx.save(); ctx.translate(w / 2, h / 2); ctx.scale(Math.max(0.001, s), 1 - Math.sin(p * Math.PI) * 0.1); ctx.drawImage(p < 0.5 ? a : b, -w / 2, -h / 2); ctx.restore(); });
T("flipVertical", "Flip Vertical", "3d", ["3d"], "Flip around X axis.", (ctx, a, b, p, w, h) => { const s = Math.abs(Math.cos(p * Math.PI)); ctx.fillStyle = "#000"; ctx.fillRect(0, 0, w, h); ctx.save(); ctx.translate(w / 2, h / 2); ctx.scale(1 - Math.sin(p * Math.PI) * 0.1, Math.max(0.001, s)); ctx.drawImage(p < 0.5 ? a : b, -w / 2, -h / 2); ctx.restore(); });
T("cube", "Cube Rotate", "3d", ["3d", "cube"], "Faux 3D cube rotation.", (ctx, a, b, p, w, h) => { ctx.fillStyle = "#000"; ctx.fillRect(0, 0, w, h); const wa = w * Math.cos(p * Math.PI / 2), wb = w * Math.sin(p * Math.PI / 2); ctx.save(); ctx.globalAlpha = 1 - p * 0.5; ctx.drawImage(a, 0, 0, w, h, 0, 0, Math.max(1, wa), h); ctx.restore(); ctx.save(); ctx.globalAlpha = 0.5 + p * 0.5; ctx.drawImage(b, 0, 0, w, h, wa, 0, Math.max(1, wb), h); ctx.restore(); });
T("doorway", "Doorway", "3d", ["3d", "reveal"], "Doors swing open to reveal B pushing in.", (ctx, a, b, p, w, h) => { ctx.save(); ctx.translate(w / 2, h / 2); const s = 0.8 + p * 0.2; ctx.scale(s, s); ctx.drawImage(b, -w / 2, -h / 2); ctx.restore(); const k = Math.cos(p * Math.PI / 2); ctx.drawImage(a, 0, 0, w / 2, h, 0, 0, (w / 2) * k, h); ctx.drawImage(a, w / 2, 0, w / 2, h, w - (w / 2) * k, 0, (w / 2) * k, h); });
T("pageTurn", "Page Turn", "3d", ["editorial", "book"], "Page curl across.", (ctx, a, b, p, w, h) => { ctx.drawImage(b, 0, 0); const x = w * (1 - p); ctx.save(); ctx.beginPath(); ctx.rect(0, 0, x, h); ctx.clip(); ctx.drawImage(a, 0, 0); ctx.restore(); const g = ctx.createLinearGradient(x - 60, 0, x + 20, 0); g.addColorStop(0, "rgba(0,0,0,0)"); g.addColorStop(0.8, "rgba(0,0,0,0.4)"); g.addColorStop(1, "rgba(255,255,255,0.3)"); ctx.fillStyle = g; ctx.fillRect(x - 60, 0, 80, h); });
// Digital
T("glitch", "Glitch", "digital", ["glitch", "cyber", "tech"], "Slice displacement + RGB split swap.", (ctx, a, b, p, w, h) => { const src = p < 0.5 ? a : b; const k = Math.sin(p * Math.PI); const rnd = mulberry32(Math.floor(p * 20) + 3); ctx.drawImage(src, 0, 0); for (let i = 0; i < 12 * k; i++) { const y = rnd() * h, hh = rnd() * h * 0.1; ctx.drawImage(rnd() > 0.5 ? a : b, 0, y, w, hh, (rnd() - 0.5) * w * 0.15 * k, y, w, hh); } if (k > 0.3) { const s = getCanvas("tr_glitch", w, h); ctxOf(s).drawImage(ctx.canvas, 0, 0); rgbSplit(ctx, s, w, h, k * 14); } }, "linear", 14);
T("pixel", "Pixelate", "digital", ["retro", "8bit"], "Pixelate out then in.", (ctx, a, b, p, w, h) => { const k = Math.sin(p * Math.PI); const sz = Math.max(1, Math.round(k * 60)); const c = getCanvas("tr_pix", Math.ceil(w / sz), Math.ceil(h / sz)); ctxOf(c).drawImage(p < 0.5 ? a : b, 0, 0, c.width, c.height); ctx.imageSmoothingEnabled = false; ctx.drawImage(c, 0, 0, w, h); ctx.imageSmoothingEnabled = true; }, "linear");
T("scanReveal", "Scan Reveal", "digital", ["hud", "tech"], "Bright scanline sweeping down revealing B.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); clipDraw(ctx, b, () => ctx.rect(0, 0, w, h * p)); const y = h * p; const g = ctx.createLinearGradient(0, y - 30, 0, y + 2); g.addColorStop(0, "rgba(120,200,255,0)"); g.addColorStop(1, "rgba(160,220,255,0.9)"); ctx.fillStyle = g; ctx.fillRect(0, y - 30, w, 32); }, "linear");
T("dataMosh", "Datamosh", "digital", ["glitch", "experimental"], "Smeared block datamosh.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const bs = 48; for (let y = 0; y < h; y += bs) for (let x = 0; x < w; x += bs) { const k = hash1(x * 0.1 + y * 0.37); if (k < p) { const dy = Math.sin(p * 10 + x) * bs * 0.5 * (1 - p); ctx.drawImage(b, x, y, bs, bs, x, y + dy, bs, bs); } } }, "linear");
T("noiseDissolve", "Noise Dissolve", "digital", ["dissolve", "organic"], "Blocky noise dissolve.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const bs = 24; clipDraw(ctx, b, () => { for (let y = 0; y < h; y += bs) for (let x = 0; x < w; x += bs) if (hash1(x * 1.3 + y * 7.1) < p) ctx.rect(x, y, bs, bs); }); }, "linear");
// Organic / light
T("liquid", "Liquid", "organic", ["liquid", "fluid", "premium"], "Wavy liquid edge sweeping upward.", (ctx, a, b, p, w, h) => { ctx.drawImage(a, 0, 0); const base = h * (1.1 - p * 1.25); clipDraw(ctx, b, () => { ctx.moveTo(0, h); for (let x = 0; x <= w; x += 20) ctx.lineTo(x, base + Math.sin(x / w * 6 + p * 8) * h * 0.06 * Math.sin(p * Math.PI) + Math.sin(x / w * 13 - p * 5) * h * 0.02); ctx.lineTo(w, h); ctx.closePath(); }); }, "easeInOutCubic", 24);
T("wave", "Wave", "organic", ["wave"], "Sine-displaced rows during swap.", (ctx, a, b, p, w, h) => { const k = Math.sin(p * Math.PI); const src = p < 0.5 ? a : b; for (let y = 0; y < h; y += 6) ctx.drawImage(src, 0, y, w, 6, Math.sin(y * 0.03 + p * 10) * 40 * k, y, w, 6); });
T("particle", "Particle Dissolve", "organic", ["particles", "magic"], "A disintegrates into drifting particles.", (ctx, a, b, p, w, h) => { ctx.drawImage(b, 0, 0); const bs = 16; for (let y = 0; y < h; y += bs) for (let x = 0; x < w; x += bs) { const d = hash1(x * 0.7 + y * 0.13) * 0.7 + (x / w) * 0.3; const k = clamp((p - d * 0.7) / 0.3); if (k >= 1) continue; ctx.globalAlpha = 1 - k; ctx.drawImage(a, x, y, bs, bs, x + k * 80 * (hash1(x + y) - 0.3), y - k * 120, bs * (1 - k * 0.5), bs * (1 - k * 0.5)); } ctx.globalAlpha = 1; }, "linear", 30);
T("distortion", "Heat Distortion", "organic", ["distortion", "warp"], "Warped heat-haze crossfade.", (ctx, a, b, p, w, h) => { const k = Math.sin(p * Math.PI); for (let x = 0; x < w; x += 8) { const dy = Math.sin(x * 0.02 + p * 12) * 30 * k; ctx.drawImage(a, x, 0, 8, h, x, dy, 8, h); } ctx.globalAlpha = p; for (let x = 0; x < w; x += 8) { const dy = Math.sin(x * 0.02 + p * 12) * 30 * k; ctx.drawImage(b, x, 0, 8, h, x, -dy, 8, h); } ctx.globalAlpha = 1; });
T("lightSweep", "Light Sweep", "light", ["premium", "shine"], "Bright diagonal light band carries the cut.", (ctx, a, b, p, w, h) => { const x = -w * 0.4 + p * w * 1.8; ctx.drawImage(a, 0, 0); clipDraw(ctx, b, () => { ctx.moveTo(-w, 0); ctx.lineTo(x, 0); ctx.lineTo(x - h * 0.5, h); ctx.lineTo(-w, h); }); ctx.save(); ctx.globalCompositeOperation = "lighter"; ctx.translate(x, 0); ctx.transform(1, 0, -0.5, 1, 0, 0); const g = ctx.createLinearGradient(-100, 0, 100, 0); g.addColorStop(0, "rgba(255,255,255,0)"); g.addColorStop(0.5, "rgba(255,255,255,0.85)"); g.addColorStop(1, "rgba(255,255,255,0)"); ctx.fillStyle = g; ctx.fillRect(-100, 0, 200, h * 2); ctx.restore(); }, "easeInOutQuart", 22);
T("lensFlareCut", "Flare Cut", "light", ["cinematic", "anamorphic"], "Anamorphic flare burst hides the cut.", (ctx, a, b, p, w, h) => { ctx.drawImage(p < 0.5 ? a : b, 0, 0); const k = Math.max(0, 1 - Math.abs(p - 0.5) * 3); ctx.save(); ctx.globalCompositeOperation = "lighter"; const g = ctx.createLinearGradient(0, h / 2, w, h / 2); g.addColorStop(0, "rgba(150,200,255,0)"); g.addColorStop(0.5, `rgba(200,230,255,${k})`); g.addColorStop(1, "rgba(150,200,255,0)"); ctx.fillStyle = g; ctx.fillRect(0, h / 2 - 60 * k, w, 120 * k); const r = ctx.createRadialGradient(w / 2, h / 2, 0, w / 2, h / 2, w * 0.5); r.addColorStop(0, `rgba(255,255,255,${k * 0.9})`); r.addColorStop(1, "rgba(255,255,255,0)"); ctx.fillStyle = r; ctx.fillRect(0, 0, w, h); ctx.restore(); }, "linear", 16);
T("lumaFade", "Luma Fade", "light", ["premium", "exposure"], "Overexposed crossfade.", (ctx, a, b, p, w, h) => { const k = Math.sin(p * Math.PI); ctx.filter = `brightness(${1 + k * 1.5})`; ctx.drawImage(a, 0, 0); ctx.globalAlpha = p; ctx.drawImage(b, 0, 0); ctx.globalAlpha = 1; ctx.filter = "none"; void w; void h; });

export function drawTransition(ctx: Ctx2D, id: string, a: Src, b: Src, linearP: number, w: number, h: number, params: Record<string, unknown> = {}) {
  const def = TRANSITIONS[id] ?? TRANSITIONS.crossfade;
  const p = getEase((params.ease as string) ?? def.ease)(clamp(linearP));
  ctx.save();
  def.draw(ctx, a, b, p, w, h, params);
  ctx.restore();
}
