// Generated by scripts/vendor-framecn.mjs — slug → framecn customizer config (defaults + controls).
import type { ComponentConfig } from './customizer-config'
import { aiGenerateOverlayConfig as c0 } from './ai-generate-overlay/config'
import { aiGenerationCanvasConfig as c1 } from './ai-generation-canvas/config'
import { animatedBarChartConfig as c2 } from './animated-bar-chart/config'
import { animatedLineChartConfig as c3 } from './animated-line-chart/config'
import { backdropConfig as c4 } from './backdrop/config'
import { blurOutUpConfig as c5 } from './blur-out-up/config'
import { blurRevealConfig as c6 } from './blur-reveal/config'
import { bottomUpLettersConfig as c7 } from './bottom-up-letters/config'
import { boundingBoxSelectorConfig as c8 } from './bounding-box-selector/config'
import { browserFlowConfig as c9 } from './browser-flow/config'
import { captionClipWipeConfig as c10 } from './caption-clip-wipe/config'
import { captionEditorialEmphasisConfig as c11 } from './caption-editorial-emphasis/config'
import { captionEmojiPopConfig as c12 } from './caption-emoji-pop/config'
import { captionGlitchRgbConfig as c13 } from './caption-glitch-rgb/config'
import { captionGradientFillConfig as c14 } from './caption-gradient-fill/config'
import { captionHighlightConfig as c15 } from './caption-highlight/config'
import { captionKineticSlamConfig as c16 } from './caption-kinetic-slam/config'
import { captionMatrixDecodeConfig as c17 } from './caption-matrix-decode/config'
import { captionNeonAccentConfig as c18 } from './caption-neon-accent/config'
import { captionNeonGlowConfig as c19 } from './caption-neon-glow/config'
import { captionParallaxLayersConfig as c20 } from './caption-parallax-layers/config'
import { captionParticleBurstConfig as c21 } from './caption-particle-burst/config'
import { captionPillKaraokeConfig as c22 } from './caption-pill-karaoke/config'
import { captionTextureConfig as c23 } from './caption-texture/config'
import { captionWeightShiftConfig as c24 } from './caption-weight-shift/config'
import { chatToPreviewLayoutConfig as c25 } from './chat-to-preview-layout/config'
import { chromaticAberrationWipeConfig as c26 } from './chromatic-aberration-wipe/config'
import { codeAccordionConfig as c27 } from './code-accordion/config'
import { codeDiffWipeConfig as c28 } from './code-diff-wipe/config'
import { confettiConfig as c29 } from './confetti/config'
import { cursorFlowConfig as c30 } from './cursor-flow/config'
import { dashboardPopulateConfig as c31 } from './dashboard-populate/config'
import { dataFlowPipesConfig as c32 } from './data-flow-pipes/config'
import { deviceMockupZoomConfig as c33 } from './device-mockup-zoom/config'
import { directionalWipeConfig as c34 } from './directional-wipe/config'
import { dragAndDropFlowConfig as c35 } from './drag-and-drop-flow/config'
import { dynamicGridConfig as c36 } from './dynamic-grid/config'
import { ecosystemConstellationConfig as c37 } from './ecosystem-constellation/config'
import { fadeThroughConfig as c38 } from './fade-through/config'
import { focusBlurResolveConfig as c39 } from './focus-blur-resolve/config'
import { frostedGlassWipeConfig as c40 } from './frosted-glass-wipe/config'
import { glassCodeBlockConfig as c41 } from './glass-code-block/config'
import { gridPixelateWipeConfig as c42 } from './grid-pixelate-wipe/config'
import { heroDeviceAssembleConfig as c43 } from './hero-device-assemble/config'
import { imageExpandToFullscreenConfig as c44 } from './image-expand-to-fullscreen/config'
import { infiniteBentoPanConfig as c45 } from './infinite-bento-pan/config'
import { infiniteMarqueeConfig as c46 } from './infinite-marquee/config'
import { inlineHighlightConfig as c47 } from './inline-highlight/config'
import { kineticTypeMaskConfig as c48 } from './kinetic-type-mask/config'
import { landingCodeShowcaseConfig as c49 } from './landing-code-showcase/config'
import { lineByLineSlideConfig as c50 } from './line-by-line-slide/config'
import { liveCodeCompilationConfig as c51 } from './live-code-compilation/config'
import { logoEnterConfig as c52 } from './logo-enter/config'
import { markerHighlightConfig as c53 } from './marker-highlight/config'
import { maskRevealUpConfig as c54 } from './mask-reveal-up/config'
import { maskedSlideRevealConfig as c55 } from './masked-slide-reveal/config'
import { matrixDecodeConfig as c56 } from './matrix-decode/config'
import { meshGradientBgConfig as c57 } from './mesh-gradient-bg/config'
import { microScaleFadeConfig as c58 } from './micro-scale-fade/config'
import { morphingModalConfig as c59 } from './morphing-modal/config'
import { perCharacterRiseConfig as c60 } from './per-character-rise/config'
import { perWordCrossfadeConfig as c61 } from './per-word-crossfade/config'
import { perspectiveMarqueeConfig as c62 } from './perspective-marquee/config'
import { pipelineJourneyConfig as c63 } from './pipeline-journey/config'
import { pricingTierFocusConfig as c64 } from './pricing-tier-focus/config'
import { productLaunchTrailerConfig as c65 } from './product-launch-trailer/config'
import { progressStepsConfig as c66 } from './progress-steps/config'
import { pulsingIndicatorConfig as c67 } from './pulsing-indicator/config'
import { rgbGlitchTextConfig as c68 } from './rgb-glitch-text/config'
import { scaleDownFadeConfig as c69 } from './scale-down-fade/config'
import { shaderColorPanelsConfig as c70 } from './shader-color-panels/config'
import { shaderDitheringConfig as c71 } from './shader-dithering/config'
import { shaderDotOrbitConfig as c72 } from './shader-dot-orbit/config'
import { shaderGodRaysConfig as c73 } from './shader-god-rays/config'
import { shaderGrainGradientConfig as c74 } from './shader-grain-gradient/config'
import { shaderLiquidMetalConfig as c75 } from './shader-liquid-metal/config'
import { shaderMeshGradientConfig as c76 } from './shader-mesh-gradient/config'
import { shaderMetaballsConfig as c77 } from './shader-metaballs/config'
import { shaderNeuroNoiseConfig as c78 } from './shader-neuro-noise/config'
import { shaderPerlinNoiseConfig as c79 } from './shader-perlin-noise/config'
import { shaderPulsingBorderConfig as c80 } from './shader-pulsing-border/config'
import { shaderSimplexNoiseConfig as c81 } from './shader-simplex-noise/config'
import { shaderSmokeRingConfig as c82 } from './shader-smoke-ring/config'
import { shaderSpiralConfig as c83 } from './shader-spiral/config'
import { shaderSwirlConfig as c84 } from './shader-swirl/config'
import { shaderVoronoiConfig as c85 } from './shader-voronoi/config'
import { shaderWarpConfig as c86 } from './shader-warp/config'
import { shaderWaterConfig as c87 } from './shader-water/config'
import { sharedAxisYConfig as c88 } from './shared-axis-y/config'
import { sharedAxisZConfig as c89 } from './shared-axis-z/config'
import { shimmerSweepConfig as c90 } from './shimmer-sweep/config'
import { shortSlideRightConfig as c91 } from './short-slide-right/config'
import { simulatedCursorConfig as c92 } from './simulated-cursor/config'
import { slotMachineRollConfig as c93 } from './slot-machine-roll/config'
import { softBlurInConfig as c94 } from './soft-blur-in/config'
import { spatialPushConfig as c95 } from './spatial-push/config'
import { spotlightCardConfig as c96 } from './spotlight-card/config'
import { springPopInConfig as c97 } from './spring-pop-in/config'
import { springScaleInConfig as c98 } from './spring-scale-in/config'
import { staggeredBentoGridConfig as c99 } from './staggered-bento-grid/config'
import { staggeredFadeUpConfig as c100 } from './staggered-fade-up/config'
import { strikethroughReplaceConfig as c101 } from './strikethrough-replace/config'
import { successConfettiConfig as c102 } from './success-confetti/config'
import { swipeTransitionWipeConfig as c103 } from './swipe-transition-wipe/config'
import { terminalSimulatorConfig as c104 } from './terminal-simulator/config'
import { terminalToBrowserDeployConfig as c105 } from './terminal-to-browser-deploy/config'
import { textFadeReplaceConfig as c106 } from './text-fade-replace/config'
import { toastNotificationConfig as c107 } from './toast-notification/config'
import { topDownLettersConfig as c108 } from './top-down-letters/config'
import { trackingInConfig as c109 } from './tracking-in/config'
import { typewriterConfig as c110 } from './typewriter/config'
import { zoomThroughTransitionConfig as c111 } from './zoom-through-transition/config'

export const FRAMECN_CONFIGS: Record<string, ComponentConfig> = {
  'fc-ai-generate-overlay': c0,
  'fc-ai-generation-canvas': c1,
  'fc-animated-bar-chart': c2,
  'fc-animated-line-chart': c3,
  'fc-backdrop': c4,
  'fc-blur-out-up': c5,
  'fc-blur-reveal': c6,
  'fc-bottom-up-letters': c7,
  'fc-bounding-box-selector': c8,
  'fc-browser-flow': c9,
  'fc-caption-clip-wipe': c10,
  'fc-caption-editorial-emphasis': c11,
  'fc-caption-emoji-pop': c12,
  'fc-caption-glitch-rgb': c13,
  'fc-caption-gradient-fill': c14,
  'fc-caption-highlight': c15,
  'fc-caption-kinetic-slam': c16,
  'fc-caption-matrix-decode': c17,
  'fc-caption-neon-accent': c18,
  'fc-caption-neon-glow': c19,
  'fc-caption-parallax-layers': c20,
  'fc-caption-particle-burst': c21,
  'fc-caption-pill-karaoke': c22,
  'fc-caption-texture': c23,
  'fc-caption-weight-shift': c24,
  'fc-chat-to-preview-layout': c25,
  'fc-chromatic-aberration-wipe': c26,
  'fc-code-accordion': c27,
  'fc-code-diff-wipe': c28,
  'fc-confetti': c29,
  'fc-cursor-flow': c30,
  'fc-dashboard-populate': c31,
  'fc-data-flow-pipes': c32,
  'fc-device-mockup-zoom': c33,
  'fc-directional-wipe': c34,
  'fc-drag-and-drop-flow': c35,
  'fc-dynamic-grid': c36,
  'fc-ecosystem-constellation': c37,
  'fc-fade-through': c38,
  'fc-focus-blur-resolve': c39,
  'fc-frosted-glass-wipe': c40,
  'fc-glass-code-block': c41,
  'fc-grid-pixelate-wipe': c42,
  'fc-hero-device-assemble': c43,
  'fc-image-expand-to-fullscreen': c44,
  'fc-infinite-bento-pan': c45,
  'fc-infinite-marquee': c46,
  'fc-inline-highlight': c47,
  'fc-kinetic-type-mask': c48,
  'fc-landing-code-showcase': c49,
  'fc-line-by-line-slide': c50,
  'fc-live-code-compilation': c51,
  'fc-logo-enter': c52,
  'fc-marker-highlight': c53,
  'fc-mask-reveal-up': c54,
  'fc-masked-slide-reveal': c55,
  'fc-matrix-decode': c56,
  'fc-mesh-gradient-bg': c57,
  'fc-micro-scale-fade': c58,
  'fc-morphing-modal': c59,
  'fc-per-character-rise': c60,
  'fc-per-word-crossfade': c61,
  'fc-perspective-marquee': c62,
  'fc-pipeline-journey': c63,
  'fc-pricing-tier-focus': c64,
  'fc-product-launch-trailer': c65,
  'fc-progress-steps': c66,
  'fc-pulsing-indicator': c67,
  'fc-rgb-glitch-text': c68,
  'fc-scale-down-fade': c69,
  'fc-shader-color-panels': c70,
  'fc-shader-dithering': c71,
  'fc-shader-dot-orbit': c72,
  'fc-shader-god-rays': c73,
  'fc-shader-grain-gradient': c74,
  'fc-shader-liquid-metal': c75,
  'fc-shader-mesh-gradient': c76,
  'fc-shader-metaballs': c77,
  'fc-shader-neuro-noise': c78,
  'fc-shader-perlin-noise': c79,
  'fc-shader-pulsing-border': c80,
  'fc-shader-simplex-noise': c81,
  'fc-shader-smoke-ring': c82,
  'fc-shader-spiral': c83,
  'fc-shader-swirl': c84,
  'fc-shader-voronoi': c85,
  'fc-shader-warp': c86,
  'fc-shader-water': c87,
  'fc-shared-axis-y': c88,
  'fc-shared-axis-z': c89,
  'fc-shimmer-sweep': c90,
  'fc-short-slide-right': c91,
  'fc-simulated-cursor': c92,
  'fc-slot-machine-roll': c93,
  'fc-soft-blur-in': c94,
  'fc-spatial-push': c95,
  'fc-spotlight-card': c96,
  'fc-spring-pop-in': c97,
  'fc-spring-scale-in': c98,
  'fc-staggered-bento-grid': c99,
  'fc-staggered-fade-up': c100,
  'fc-strikethrough-replace': c101,
  'fc-success-confetti': c102,
  'fc-swipe-transition-wipe': c103,
  'fc-terminal-simulator': c104,
  'fc-terminal-to-browser-deploy': c105,
  'fc-text-fade-replace': c106,
  'fc-toast-notification': c107,
  'fc-top-down-letters': c108,
  'fc-tracking-in': c109,
  'fc-typewriter': c110,
  'fc-zoom-through-transition': c111,
}
